### ISSUE TITLE
Definiera prestandabudget

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#100]
# Beskrivning
Vi behöver ha uppsatta mål kring prestandan som vi använder att testa varje PBI mot innan de får anses som färdiga. Exempel på prestandabudget finns här https://webperf.se/articles/prestandabudget-offentlig-sektor/?fbclid=IwAR1OSFRSkrlAHck51hLdvFsgO1GQiboPROl6Elssl9tMY4Ld1I4igsg_QV8

# Acceptanskriterier

**Comment by viktor-sarge** [comment]
Relevant för denna story kan vara datan från noll-läge kring responstid med Azure som finns på 
https://github.com/RegionHalland/general/issues/109

Västra götaland har också många goda tankar på https://github.com/Vastra-Gotalandsregionen/Webbanalys/blob/master/prestandabudgetar/www.vgregion.se.md  (och på det övergripande http://stilguiden.vgregion.se/index.html)  (Inga nyheter eftersom jag tipsades om detta när jag började här, men bra att alla ser länken. )

**Comment by viktor-sarge** [comment]
Vi kommer långt med att bra låna friskt från dessa två och sedan tweaka på det framöver efter egna behov.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Kan du skriva ner detta lite formellt :) Även om vi lånar så kan vi ju skriva den som en egen prestandabudget. Frågan är om den ska ligga ihop med styleguiden?

**Comment by viktor-sarge** [comment]
@JohannaOlin  Absolut! Jag skriver ett utkast som väger samman de två som förekommit hittills och sedan skickar jag på "remiss" för diskussion i arbetsgruppen. Så trimmar vi sedan. 

För min del vill jag ha det versionshanterat så det kan gärna ligga på github. Helst skall det ju också exponeras som en webbsida ihop med komponenterna på samma sätt som VG-regionen gör t.ex. Jag kollar med John som verkar ha något på gång där med Joel. 

**Min "att göra"-lista:** 

- [x] Skriva samman ett utkast till prestandabudget
- [x] Gör utkastet tillgängligt för synpunkter i arbetsgruppen
- [ ] Väga samman synpunkter och stämma av slutversion med produktägare
- [ ] Publicera prestandabudget på vårt Github-konto
- [x] Undersöka möjligheten att publicera prestandabudgeten som webbsida tillsammans med styleguidens exempel och dokumentation

**Comment by viktor-sarge** [comment]
Har testkört sitespeed.io som lokalt program i terminalen. Skall också gå att integrera i Jenkins. (Fick uppdatera npm, men gick ändå inte att installera via npm, däremot yarn fungerade fint - `yarn global add sitespeed.io`). Går definitivt att använda för QA-processen både manuellt och automatiserat. 

Också kikat på Yellow labs tools. Den har en utmärkt webbsida och finns också att köra via terminalen. I det senare fallet så ger den inte (som sitespeed.io) en visuell feedback utan skriver JSON till stout-strömmen. Funderar på om det rentav underlättar för att bygga in det i Jenkins. Hur eller hur är det ett utmärkt verktyg för manuell QA av sajten.

**Comment by viktor-sarge** [comment]
Jag har jobbat en del med den här idag. Jag börjar få ett ganska bra grepp om vad jag tycker den borde innehålla. Det finns också ganska mycket intressanta verktyg vi borde integrera i både manuella kontroller och Jenkins. Strukturen på dokumentet tycker jag bör vara: 
* Målet med prestandabudgeten
* Designkonventioner vi använder
* Övergripande gränsvärden för definierade mål
* Underordnade gränsvärden som stöttar uppfyllnad av respektive mål

För respektive övergripande och underordnat gränsvärde skall anges hur målet skall mätas på ett upprepningsbart sätt (t.ex. med vilket verktyg, med vilka inställningar osv)

Det skall också framgå hur man satt respektive gränsvärde.

Förankring tror jag är viktigt för efterlevnaden och därför planerar jag att involvera övriga utvecklingsteamet i resten av processen.

**Comment by viktor-sarge** [comment]
Jag, John och Roland hade ett möte igår om prestandabudgeten. Det fanns en samsyn kring att målet med prestandabudgeten är att garantera verksamheterna i regionen välfungerande webbplatsern genom att definiera mätbara gränsvärden och metoder för att uppnå dem. En av de tydligaste värdena som kan stötta detta (utöver uppenbara saker som korrekt kod) är snabbhet. Vi vill dock gå längre än VG-regionen och sänka från 3 sekunder till 1 sekund för en sidladdning. Jag renskriver och utökar baserat på våra tankar igår.

**Comment by viktor-sarge** [comment]
Utkast mailat till kollegorna. Behöver nog ta ett varv med kommentarer och sedan skruva lite på det sista.

**Comment by viktor-sarge** [comment]
Börjat fylla på med information som fotnötter om varför vi valt som vi gjort. Återupptar arbetet och låter den stå kvar som "in progress"

**Comment by viktor-sarge** [comment]
Tror det är dags att den här får hamna på review. Jag har försökt att tydliggöra varför alla värden är valda och vad som bör vara flytande saker som diskuteras löpande. Senaste version finns som tidigare på https://rh-my.sharepoint.com/:w:/g/personal/viktor_sarge_regionhalland_se/EWhCN1yRGGtDnlwp4u7a8wUBOA68K7dM00WPrQVdOsZ_vg?e=LeS1vB
