### ISSUE TITLE
Flytta Terapirekommendationerna till vår interna server

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#101]
# Beskrivning
Terapirekommendationerna behöver flyttas från Azure till vår interna server

**Comment by JOHNREGIONHALLAND** [comment]
Har kopierat  till RH utv server.
- Databas
- Upload
-Héla sajten
-Kännedom: vg-azure

Har kikat igenom och gjort några ändrat för att hålla sig till standard.

**Comment by JOHNREGIONHALLAND** [comment]
Viktig notering för att terapirek ska funka på nya uppsättningen
-----------------------------
# .htaccess filen bör finnas detta

RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) wp/$2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ wp/$2 [L]
RewriteRule . index.php [L]

### och på config filen ska dessa inställningar vara.
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', 'vardgivare.regionhalland.se');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

### och på \web\app\themes\terapirekommendationer\config\content.php
/**
* Tell WordPress to load from local wp-content, and not vendor wp.
define('WP_CONTENT_DIR', dirname(dirname(__FILE__)) . '/wp/wp-content');
define('WP_CONTENT_URL', 'https://' . $_SERVER['HTTP_HOST'] . '/wp/wp-content');
#eller
define('WP_CONTENT_URL', env('WP_HOME'). '/wp/wp-content');
*/

**Comment by JohannaOlin** [comment]
Vi väntar på F5 och komponenter för bland annat vänstermeny. Vi sätter upp ett internt möte för att diskutera detta.
