### ISSUE TITLE
Koppla Mediaflow mot Vårdgivarwebben och regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#111]
@JohannaOlin commented on [Tue Nov 20 2018](https://github.com/RegionHalland/halland/issues/333)

# Beskrivning
Regionen har ett nytt bildhanteringsverktyg, Mediaflow, som har en plugin till wordpress. Vi behöver lägga in detta så att redaktörerna kan välja att hämta bilder från Mediaflow till sina sidor.

# Kontaktperson
Cissi.Brusehed@regionhalland.se

# Acceptanskriterier

- [ ] En redaktör ska kunna hämta bilder från Mediaflow och lägga in på sidorna
- [ ] De befintliga bilderna som ligger i Mediabiblioteket ska inte påverkas.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by viktor-sarge** [comment]
Jag har gett @RolandHyden länkarna till nedladdning av MediaFlow pluginsen (2st - båda används). Vi behöver dock också licensnyckeln och server tror jag och de har jag inte (testade bara m demo-kontot). Har Cissi möjligen dessa?

**Comment by RolandHyden** [comment]
För information har jag varit i kontakt med MediaFlow eftersom vi måste ha deras plugin nåbara via Composer, dvs medialows plugin måste ligga på ett repo, ex github. Det visade sig att MediaFlow inte har något repo och planerar heller inte att ha något repo. Deras förslag var att vi installerar gitlab på en egen intern server. Jag föreslog ett privat repo på Region Hallands github. Vi får se vad det landar.

**Comment by viktor-sarge** [comment]
Bra Roland. Om de inte har något emot att vi lägger det i gitlab så borde ett privat repo funka det med. Har du hunnit testa att composer kan plocka upp kod från privata repos?

**Comment by RolandHyden** [comment]
Jo, jag har skapat ett privat repo på vår github som heter test-private-plugin:

https://github.com/RegionHalland/test-private-plugin

Detta är privat och går fint att läsa in med Composer. Har ju en lokal sajt där jag läser in alla plugins allt eftersom jag hinner lägga dom på github. Åtminstone går det fint att läsa in den lokalt eftersom git använder min inloggning. Vet dock inte hur detta fungerar med automatiska deploys. Är ju lite svårt att testa detta just nu :)

Supporten på mediaflowpro frågade även ifall en av deras tekniker kunde få access till regionhalalnds repo. Men det vet jag inte ifall vi tillåter. Vet du det?

**Comment by viktor-sarge** [comment]
Perfekt att det funkar! 

Ang att få access till repot så vet jag faktiskt inte. Men vi har ju haft andra konsulter inne som Digitaliseringsbyrån. Man kan ju styra hur mycket access de får så om man kan sätta read only så borde det ju funka. Vad säger du @JohannaOlin ?

**Comment by RolandHyden** [comment]
Fast räcker read only ifall det är ett privat repo?

**Comment by viktor-sarge** [comment]
Vi får prova :) Jag tycker att det borde räcka. För read only på ett privat borde ju innebära att man faktiskt får se det. Det är ju liksom normalläget för offentliga repos och då borde de kunna komma åt och se att vi inte gör något fuffens med deras kod utan att den blir synlig för allmänheten.

**Comment by JohannaOlin** [comment]
Är det bara read-only så är det inga problem tycker jag

**Comment by RolandHyden** [comment]
@JohannaOlin 
Tack för snabbt svar :)
@regionhallandviktor 
Kan du lägga till Anton Segerkvist som read-only på vår github?
Här hans profil:
https://github.com/antonsegerkvist
Eller ska jag göra det?

**Comment by viktor-sarge** [comment]
Hej! Jag tänkte jag kunde göra det så satte upp två privata repos (mfpconnect och mfpconnectmedia namngivna efter respektive plugin), men när jag skulle lägga till anton som "collaborator" på de specifika repona så var det stopp. Tydligen behöver vi betala $108/år extra eftersom vi redan har fullt antal medelmmar. 

Tänker att vi hur eller hur behöver ge access till bara dessa två repos så att han inte ser övriga privata repos med nycklar o grejer i installationernas privata repos.

**Comment by JohannaOlin** [comment]
Jag har kollar igenom medlemmarna och visst borde vi kunna ta bort österhult. Jag har i alla fall inte fått besked om att han fortsatt ska vara inne och då har vi en plats över. Så småningom behöver vi en plats till konsulten som ska bygga komponenterna, men hen kanske kan ta antons plats sen?

**Comment by viktor-sarge** [comment]
Hm. Hur funkar det idag - betalar vi för alla medlemmarna eller bara de vi själva använder? Jag tänker också att vi kanske skulle gå igenom policyn för vem som har access till vad. Är det rimligt att alla har skrivaccess till alla repos eller kan vi städa upp så att man bara har skrivaccess till det man själv jobbar med och läsaccess till andra gruppers repon? När det gäller repon med nycklar och liknande kanske man inte ens skall ha läsaccess till andra gruppers info. (Vad händer om man glömmer sin dator på bussen och nycklar till sajterna kommer på avvägar)

Magnus vet jag inte om han behöver access. Vi får nästan fråga honom - han kanske har något ihop med labbet tex(?)

**Comment by JohannaOlin** [comment]
Ja, vi betalar för alla. Jag har också sett att vi behöver rensa upp där. Jag kan lägga ett kort att vi tar tag i det nästa sprint. Jag ser att Dskantz också har fått ett konto. Behövs det? Jag tänker att om fler på IT ska in så är det ju inte objektet som ska betala licensen. Just nu gör vi det. Jag kollar med Magnus om jag kan ta bort honom.

**Comment by viktor-sarge** [comment]
Jag gissar att Azure devops borde betyda att vi behöver färre licenser. Men så länge man använder Gihtub så känns det ju rimligare att varje objekt/enhet betalar för sina egna och sina konsulters licenser.

**Comment by JohannaOlin** [comment]
Jag gjorde osterhult till en outsidecollaborator istället, men eftersom han inte låg i några repos så visas han inte. Men nu finns det en plats kvar om vi behöver den för Mediaflow. Eller så kan de ligga som outside collaborators också. Vet inte riktigt vad de får göra då.

**Comment by viktor-sarge** [comment]
Toppen. Nu är Anton från Mediaflow inlagd.

**Comment by viktor-sarge** [comment]
Vi har kikat på det här idag Roland, John och jag. Pluginsen är uppdaterade med composer-stöd och har fått releaser så att vi kan läsa in dem. Fungerade först inte med Forge, men hostade till och kom in sedan trots allt. Nu finns MediaFlow på stage-servern kopplad till dummy-databasen.

**Comment by viktor-sarge** [comment]
För kännedom: Johanna är informerad om hur MediaFlow-pluginet funkar och tar det vidare med redaktörsorganisationen. Viktigast härnäst är att lägga in pluginsen på regionhalland.se - mer än vardgivarwebben. Vi kan ev också visa via t.ex. Teams/Skype hur det funkar. 

Cissi kan tänkas ha vår skarpa nyckel så att jag kan lägga in den. Jag tar kontakt.

**Comment by viktor-sarge** [comment]
(mailat cissi)

**Comment by viktor-sarge** [comment]
Nu är det aktiverat med den nyckel som jag fick av Cissi på stage-vardgivare.se. Nu bör det fungera så fort de har konfigurerat färdigt Mediaflow. Vi kan om så önskas rulla ut Mediaflow till de skarpa servrarna redan nu.

edit: det är stage-vardgivare den ligger på. Korrigerat.

**Comment by viktor-sarge** [comment]
(Jag hade dock personligen väntat med att aktivera Mediaflow på de skarpa servrarna tills de konfigurerat färdigt och testat på stage.)

**Comment by JohannaOlin** [comment]
Nej vi väntar med de skarpa servrarna

**Comment by viktor-sarge** [comment]
@RolandHyden lägger in pluginsen på stage-rh.regionhalland.se. (sprintplanering 30 jan 19)

**Comment by viktor-sarge** [comment]
Flytta till QA när stage-rh har pluginsen. Vi gör nytt kort för skarpa servrarna.
