### ISSUE TITLE
Förberedelse för tryck av terapirek 15 jan 2019 (tidigare "Utskrift av terapirekommendationena - två spalt")

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#114]
# Beskrivning
Terapirekommendationerna kommer nästa år endast att tryckas vid beställning och David har utvecklat en lösning som gör att redaktören (Anton) själv kan initiera ett skapande av en pdf som sedan går att skriva ut. Problemet är att den utskriften endast blir i 1-spalt. När det gjordes ett riktigt tryck så var detta i 2-spalt och boken riskerar nu att vara på 700 sidor.

# Kontaktperson
Anton Hübner

# Acceptanskriterier
- [ ] Utskriften från Pdf:en ska bli i två-spalt

**Comment by viktor-sarge** [comment]
Vet att @RolandHyden har nått en del framgångar här. Är den färdig för QA Roland?

**Comment by JohannaOlin** [comment]
@RolandHyden Kommentar från Anton:

Det är en bit på vägen men det är mycket som inte blir bra.

Här är några synpunkter:
•	Förord kommer efter innehållsföteckningen (ska ligga innan på insidan av omslaget. Den texten är inte ändrad ännu och det ser ut som om kolumnerna är smalare i denna version än förr då förordet endast tar upp en halv sida i förra årets bok men i denna versionen tar upp mer än 1 sida.
•	Symboler har försvunnit exempelvis generika utbytbarhet i rek-listorna i tabellerna.
•	Figurer är borta exempelvis figur 2.1 men bildtext ligger kvar
•	Dessutom har kapitel 2 nu blivit kapitel 3 osv i pagineringen 
•	Viss text i blåa rutor verkar ha fått annat typsnitt exmpelvis blåruta sid 30 i pdfen

Hör gärna av dig när du ser detta så vi får prata mer om hur vi löser det. Vi har nu satt deadline för inskick till tryckeri till 15 januari så detta måste fixas i början på det nya året.

**Comment by RolandHyden** [comment]
Hej Johanna. Då vi har fått besked av Anton att alla 3 filerna är skickade för tryck så kan man väl anta att denna issue äntligen kan stängas :)
