### ISSUE TITLE
Det är möjligt att lägga boxar under vänsternavigationen vilket vi nog faktiskt inte vill.

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#116]
Antagligen vill vi stänga av möjligheten att lägga modularity-boxar i "left"

**Comment by viktor-sarge** [comment]
Värt att veta: Roland har i dagsläget inte installerat modularity på regionhalland.se som annars används på vårdgivarwebben.

**Comment by JohannaOlin** [comment]
Vi ska ta bort Modularity helt och hållet så jag stänger detta
