### ISSUE TITLE
Skilja på lokalt, dev och prod

### ISSUE THREAD

**Issue by RolandHyden** [RegionHalland/general#121]
Peter Larson skickade ett förslag.
På Region Hallands övriga webbar har man alltid en streckad ram runt sidan lokalt, en röd ram runt sidan på dev och ingen ram i produktion. På så vis blandar man inte ihop var det är man tittar. Ett mycket bra förslag kan jag tycka, och inte särskilt svårt att implementera.

[https://app.zenhub.com/files/158801558/9763a2ce-2ac3-47e7-8063-2795266cefe2/download](https://app.zenhub.com/files/158801558/9763a2ce-2ac3-47e7-8063-2795266cefe2/download)

**Comment by viktor-sarge** [comment]
Roland nämnde att .env-filen kan hålla koll på miljön. Om man då sätter en klass på body-taggen så är det sannolikt enkelt att sätta en regel i styleguiden som t.ex. 

.RH-website__vardgivare-stage { 
    border: solid 4px red;
}

.RH-website__vardgivare-local { 
    border: solid 4px yellow;
}

**Comment by JOHNREGIONHALLAND** [comment]
Även på WP-ADMIN bör man som admin konto byta tema färg 
Kännedom: /wp/wp-admin/profile.php
