### ISSUE TITLE
Slå på klick-loggning

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#124]
# Beskrivning
Findwise har lagt in stöd för klick-loggning i söktjänsten, men vi behöver göra en del på frontend-sidan för att detta ska fungera. Se nedan

# Kontaktperson
Johan Björk, johan.bjork@findwise.com

# Acceptanskriterier
Till varje sökresultat finns nu ett "_clickurl"-fält inlagt som innehåller en tagg innehållandes sökmetadata. För att ett klick på en länk ska loggas krävs att ett GET-anrop skickas till en sammansatt URL beståendes av sök-URL:en + "_clickurl"-fältet. Nedan följer ett exempel på hur "_clickurl"-fältet ska användas i frontend för att ett klick ska loggas. Säg till om det är något som är oklart i instruktionerna.

Ett exempel:
Sökning på vårdgivarwebben (http://193.183.15.219:8090/rest/apps/regionhalland/searchers/vardgivarwebben?q=*) genererar bland andra följande träff

 {
      "_clickurl" : "/click?timeOfSearch=1543913322504&stats=%7B%22totalHits%22%3A1050%2C%22searchEngineTimeInMillis%22%3A12%2C%22searchEngineRoundTripTimeInMillis%22%3A17%2C%22searchProcessingTimeInMillis%22%3A21%7D&searchId=8260c417-c426-4150-8c10-b9e5c073da72&userQuery=%22q%3D*%22&query=%22q%3D*%22&misc=%7B%7D&hitNo=1&target=http%3A%2F%2Fvardgivare.regionhalland.se%2F%3Fpost_type%3Dnews%26%23038%3Bp%3D6898&doc=%7B%7D",
      "_id" : "works_6898",
      "_type" : "default",
      "collection" : "vardgivarwebben",
      "content" : "På grund av möte stänger vi för besök den 21 november kl. 9-13.\r\n\r\nPå grund av möte stänger knappvalet ”order och leverans” den 22 november kl. 11:45-16. Övriga knappval är öppna.\r\n\r\nEn tekniker kommer",
      "created" : "2018-11-15 12:14:04",
      "modified" : "2018-11-15 12:14:04",
      "title" : "Hmc har stängt för möte 21/11 och 22/11",
      "type" : "news",
      "url" : "http://vardgivare.regionhalland.se/?post_type=news&#038;p=6898"
    }

Vid ett klick-event på URL:en http://vardgivare.regionhalland.se/?post_type=news&#038;p=6898 ska då ett GET-anrop skickas till http://193.183.15.219:8090/rest/apps/regionhalland/searchers/vardgivarwebben/ + _clickurl =
http://193.183.15.219:8090/rest/apps/regionhalland/searchers/vardgivarwebben/click?timeOfSearch=1543913322504&stats=%7B%22totalHits%22%3A1050%2C%22searchEngineTimeInMillis%22%3A12%2C%22searchEngineRoundTripTimeInMillis%22%3A17%2C%22searchProcessingTimeInMillis%22%3A21%7D&searchId=8260c417-c426-4150-8c10-b9e5c073da72&userQuery=%22q%3D*%22&query=%22q%3D*%22&misc=%7B%7D&hitNo=1&target=http%3A%2F%2Fvardgivare.regionhalland.se%2F%3Fpost_type%3Dnews%26%23038%3Bp%3D6898&doc=%7B%7D

Svaret som fås tillbaka från anropet ska vara tomt, och ett klick är då loggat.

**Comment by JOHNREGIONHALLAND** [comment]
Hej igen Johan!

Port 8090  funkar inte - http://193.183.15.219:8090
Port 8080 funkar  - http://193.183.15.219:8080

Hur är det bestämt??

Vilka portar släpps igenom till server och ska användas??


/ John

**Comment by JOHNREGIONHALLAND** [comment]
Stämmer, det är port 8080 som används för söktjänsten.

Vi har just nu följande portar öppna och konfigurerade:

För indexserver (193.183.15.220):
8080 - Indexservice
8084 - Connectorservice
9200 - Processerings-service

För sökserver (193.183.15.219):
8080 - Sökservice
8090 - Kibana (sökstatistik)
8083 - Search Editor Portal
8083 - Elastic (index)

Jag kan gå igenom mer i detalj nästa vecka vad alla dessa tjänster gör och hur de samverkar.

Mvh,
Johan

**Comment by JohannaOlin** [comment]
Vi får avvakta med detta tills vi har den riktiga servern på plats

**Comment by JOHNREGIONHALLAND** [comment]
## En notis bara: JOHN
-----------------------------
Jag tror bäst att låta det vara ID "https://vardgivare.regionhalland.se/?page_id=4812"
Det kan väl hända om man byter titel så ändras permalänk.
Vi kan styra från vårt håll hur det ska visas

Ja jag tror bäst att hela clickURL innehålla hela URL-pathen.
Det blir enklast så om ni byter ip då byter ni från er källa.
Exempel: "_clickurl" : "http://193.183.15.219:8080/click?timeOfSearch=1549957619099&stats=%7B%22totalHits%22%3A1100%2C%22searchEngineTimeInMillis%22%3A10%2C%22searchEngineRoundTripTimeInMillis%22%3A20%2C%22searchProcessingTimeInMillis%22%3A21%7D&searchId=f52e7460-b583-4ef7-aef5-f54f65b45428&userQuery=%22q%3Dbarn%22&query=%22q%3Dbarn%22&misc=%7B%7D&hitNo=1&target=http%3A%2F%2Fvardgivare.regionhalland.se%2F%3Fpage_id%3D4812&doc=%7B%7D",


Jag tänkte om hur det går med era sökserver?
LTFINDINDEX1
LTFINDSEARCH1
LTFINDSEARCH2
LTFINDSEARCH3
LTFINDINDEXTEST1
LTFINDSEARCHTEST1
LTFINDSEARCHTEST2
LTFINDSEARCHTEST3

Vi har fått våra testserver uppsatta och håller på att installeras.
LTWEBDMZTEST10
LTINTRANETTEST1

 --------------
Hej John,
Ja, hade tänkt att kolla på det idag. Om jag förstod dig rätt så vill du att URL:en för en sida från Wordpress byts ut mot den URL som visas utåt.
Till exempel att URL:en  "https://vardgivare.regionhalland.se/?page_id=4812" ersätts med "https://vardgivare.regionhalland.se/behandlingsstod/smittskydd/vaccinationer/barnvaccination/ovriga-vacciner-barn/" i vårt sök-API. 

Vill du även att clickURL:en innehåller hela URL-pathen och inte bara endpointen?

Vad menar du med "våra" sökservrar? Vi utvecklar och testar just nu allting lokalt på våra datorer, och har ingen uppsättning testservrar.

Mvh,
Johan
