### ISSUE TITLE
Nyheter som inte ska visas på startsidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#125]
# Beskrivning
De senaste tre nyheterna (oavsett hur gamla de är) visas i nyhetslistan på startsidan respektive områdessidan. Detta ställer till problem t ex om nyheten gäller att en enhet stänger en viss dag och det inte publiceras tillräckligt många nyheter för att just denna nyheten ska försvinna från startsidan när den inte längre är aktuell.
Vi kan inte bara kasta nyheten utan den måste finnas kvar på webbplatsen till dess att den så småningom kan gallras.

# Acceptanskriterier
- [ ] Det ska gå att "ta bort" en nyhet från listningen på startsidan respektive områdessidan.

**Comment by viktor-sarge** [comment]
Antingen kan man ju ge nyheterna ett slutdatum från början då de bara blir synliga i arkivet (vilket vi isf får lägga till). Eller om man föredrar mer manuell hantering så blir det en checkbox "visa bara i nyhetsarkivet" och så en extra 
"AND NOT onlyShowInArchive" på bladefilerna (pseudokod)

**Comment by JohannaOlin** [comment]
Jag lägger denna i Icebox så länge. De behöver först ha en dialog kring om de ska ha nyheter på Vårdgivarwebbens startsida.
