### ISSUE TITLE
Som besökare vill jag ha en förbättrad utskrift

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#130]
# Beskrivning
Idag när man använder Skriv ut funktionen som ligger på varje sida på Terapirekommendationerna så tas menyer och sökruta med vid utskrift.

# Kontakt
Anton Hübner, anton.hubner@regionhalland.se

# Acceptanskriterier

- [ ] Vänstermenyn ska inte tas med vid utskriften
- [ ] Hitta på sidan ska inte tas med vid utskriften
- [ ] Sökrutan ska inte tas med vid utskriften

**Comment by JOHNREGIONHALLAND** [comment]
Jag har kikat på den lösningen lagt in det som komponent class, 
men det kan såklart läggas in på det nya komponent som kommer.
class
@media print{
 font-family:Arial;.
 print-show{display:block!important}.
 no-print,.no-print *{display:none!important}
}

**Comment by JohannaOlin** [comment]
När vi uppdaterar artice-komponenten och lägger in den på Terapirekommendationerna så löser detta sig. Stänger därför denna.
