### ISSUE TITLE
Styrt dokument går inte att öppna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#131]
# Beskrivning
Det styrda dokumentet "HMC: Brukaransvar - låneförbindelse" (den svenska versionen) går inte att öppna. http://styrdadokument.regionhalland.se/doc/e805a2cd-aa9c-47ba-aebd-c66ccf0260a5.

Vi hade problem med att detta dokument inte alls kom med från början. Nu visas det i listningarna, men går som sagt inte att öppna.

När jag försöker öppna dokumentet så ser det ut så här:
![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/2db47512-d991-4006-933e-49f9bfaf83ce)

och går jag sedan vidare och försöker öppna det i word så hittas det inte:
![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/bb2b3635-e226-498e-bc29-42b7bae31348)

**Comment by JOHNREGIONHALLAND** [comment]
Hittade felet.
Denna dok finns inte på SQL databas. 
Tror Linda har tagit bort dom  av misstag.

**Comment by JOHNREGIONHALLAND** [comment]
Ja, den kan ha blivit borttagen av misstag då jag tog bort en massa dokument som INTE skulle med den 19 november.

Då reder vi ut detta?

1.	Har du kollat att dokumentets länk till https://intra.regionhalland.se/styrda-dokument/PublishingRepository existerar i listan https://intra.regionhalland.se/Lists/publishtoextranet/AllItems.aspx och att Klassifikation är skiljt från 3?

/Linda
------------------------------

När jag synkar med Mysql till SQL ltsql42 så tars dok ” e805a2cd-aa9c-47ba-aebd-c66ccf0260a5 ”
bort eftersom den inte finns på ltsql42 och då kan man inte öppna den heller då blob data kommer därifrån.
Du kanske har tagit bort den av misstag dok ” e805a2cd-aa9c-47ba-aebd-c66ccf0260a5 ” ??
Leta efter den på ltsql42
SELECT TOP (4000) * FROM [RHControlledDocumentDB].[dbo].[ControlledDocument] WHERE Id LIKE 'e805a2cd-aa9c-47ba-aebd-c66ccf0260a5'

**Comment by JOHNREGIONHALLAND** [comment]
Denna dok har klass 1, därför blir inte denna överfört till ltsql42.

https://intra.regionhalland.se/styrda-dokument/PublishingRepository/Forms/AllItems.aspx?RootFolder=%2Fstyrda-dokument%2FPublishingRepository%2Fe805a2cd-aa9c-47ba-aebd-c66ccf0260a5&FolderCTID=0x012000CC174122B7BF384E9E88DFAA8228E630

**Comment by JohannaOlin** [comment]
Dokument som är klassificerade med 1 och 2 ska exporteras. Det är de som är klassificerade med 3 som inte ska exporteras.

**Comment by JohannaOlin** [comment]
@JOHNREGIONHALLAND Detta dokument går att öppna nu. Jag vet inte om det är för att ni har gjort något eller om det är för att det publicerades om i fredags. Oavsett så kan du flytta detta kort till Review/QA nu.

**Comment by JOHNREGIONHALLAND** [comment]
Linda har lagt in den i databasen igen SQL.
Hon hade råkat ta bort det.
