### ISSUE TITLE
Prototyp för Feedback-funktionalitet

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#132]
# Beskrivning
Idag har vi använt Hotjar för att samla in synpunkter på webbplatsen, men det verktyget är för dyrt så vi behöver ta fram en egen feedback-funktionalitet.

Titta på feedback-funktionaliteten som finns på gov.uk.

**Comment by viktor-sarge** [comment]
Frida och jag diskuterade hur logiken skall utformas så att alla förstår att deras feedback är mottagen och kommentar är ett frivilligt extrasteg. Vi kom fram till att prova följande: 
1) Var informationen till nytt ja/nej
2) Tack för din feedback. Knapp: "Jag vill även lämna en kommentar"
3) Textruta med knapp "Skicka kommentar"

**Comment by viktor-sarge** [comment]
Failed QA så länge så provar vi om den nya logiken känns rimlig. 

Diskuterade även blå knappar. Det gör dem väldigt framträdande trots att funktionen inte egentligen är så viktig att det är motiverat, men vi kan prova det.

**Comment by JohannaOlin** [comment]
Frida tar fram en ny/omarbetad komponent för detta så vi stänger ärendet.
