### ISSUE TITLE
Ikoner visas inte i Terapirekommendationerna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#133]
# Beskrivning
På sidan https://vardgivare.regionhalland.se/terapirek/terapirekommendationer/kapitel-3-allergi-astma-och-kol/kroniskt-obstruktiv-lungsjukdom-kol ska ikoner visas inne i texten på ett stycke.

![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/f818f6ab-8234-49f3-9a46-54d6365db781)

Det syns lättast i IE där dessa ikoner är utbytta mot x. Redaktören tror att något hände när Terapirekommendationerna flyttades.

Går det att hitta ikonerna igen?

# Kontaktperson
Anton Hübner, anton.hubner@regionhalland.se

**Comment by JohannaOlin** [comment]
När jag tittar i egenskaperna så är adresserna till en av ikonerna så här:
https://vardgivare.regionhalland.se/terapirek/terapirekommendationer/kapitel-3-allergi-astma-och-kol/kroniskt-obstruktiv-lungsjukdom-kol/image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAVCAYAAABCIB6VAAAACXBIWXMAAAsSAAALEgHS3X78AAABOklEQVQ4je3VMW6DMBTG8X9Qu1UqGxbPAzcoPUHTrWNuUB8hvQFHyA2a3qBjt3KD5gAdGGzVY3ICdzCpCKJSCoz9JAQW4qeHjR+LEAIAonQJfHCae+dtzYgknet04H4zBu3D/TwBS1HazAm/ADWwAYox8EVvfAAqYNfC12NQOK14B9wQ5/p9CgqnFa+Irz4JPKZbcTEX2odnzT88CBdTIFG6EKV/jESUvhKla+Dxl2dKUXopSg/1km4KoG6bGYs8EwM8n1nYAdg5b5edSktgTdype8A4b1cJcHsmCvE7vxOlK1E6iNIVsQW8Om+3LY4oXSbA1x/goTTAWpTeOm/3xN37kABvE+EU2DhvTbsOBvhchBCO81Qx3OyHYoiL1bRnQ+en4LytCCHMcuSZrPJMmjyTNITAnPBld/wN9jy+mju0gvgAAAAASUVORK5CYII=

**Comment by viktor-sarge** [comment]
Roland har ringat in att det verkar handla om de bilder som ligger inlagda som Base64-kod direkt i HTML-koden i editorn. Jag tog en snabb avkodning av dem via https://codebeautify.org/base64-to-image-converter och bad att Roland som är bra på bilder och tryck kollar om de alls funkar att använda. De är nu förvandlade till vanliga PNG-bilder och kan isf hanteras som vanliga bilder och ligga i mediabiblioteket i WP.

**Comment by viktor-sarge** [comment]
(Sedan är det för all del bra om det kan funka som base64 eftersom det sparar några nätverksrequests så inte självklart att man vill köra dem som vanliga bilder ändå)

**Comment by RolandHyden** [comment]
Hej på er. Jag hittade base64-felet. Det beror på att img src börjar med "image/png;base64", det ska vara "data:image/png;base64". Jag vill inte ändra detta själv, men ska skicka koden till Anton så att han kan ändra det själv (vill inte paja deras workflow)

**Comment by viktor-sarge** [comment]
Roland hittade ett fel i syntaxen för att använda base64 så vi slipper nog att lägga dem som bilder och kan fortsätta att ha dem som de snabbare base64-strängarna :)

Edit: Såg nu att det redan var dokumenterat. Heja Roland o snyggt jobbat m att hitta själva felet!
