### ISSUE TITLE
Ändra utseendet på regionhalland.se till att använda samma utseende som på vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#135]
# Beskrivning
Vi behöver lägga över det utseende som idag finns på vårdgivarwebben till regionhalland.se också.

**Comment by viktor-sarge** [comment]
Jag och @RolandHyden tog en avstämning nu ikväll över teams och har en plan. Förhoppningsvis skarpt läge imorgon.

**Comment by viktor-sarge** [comment]
Roland har flyttat utseendet och jag har lagt några snabba länkar i navigationen för att visa hur det ser ut. Det gick dock inte att flytta nuvarande innehåll på något rimligt sätt eftersom nästan allt var byggt med puffar. Jag gör en användare till Mattias så han kan börja labba @JohannaOlin

**Comment by viktor-sarge** [comment]
Flyttar denna till QA
