### ISSUE TITLE
Separera nyhetsredaktörer från övriga redaktörer

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#136]
@JohannaOlin commented on [Mon Oct 08 2018](https://github.com/RegionHalland/halland/issues/252)
Denna är flyttad från hallands-reposet.

# Beskrivning
Vi behöver kunna lägga in redaktörer som endast får publicera nyheter, dvs inga sidor.

# Acceptanskriterier

- [ ] Vi kan lägga in personer som nyhetsredaktörer
- [ ] Nyhetsredaktörer kan skapa, publicera, ändra och ta bort nyheter
- [ ] Nyhetsredaktörer kan INTE skapa, publicera, ändra eller ta bort sidor
- [ ] De som är redaktörer för sidor ska också ha behörighet att publicera nyheter.

@regionhallandviktor commented on [Wed Oct 10 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-428532250)

Jag tror att nyheter är löst med det som finns som default i gruppen "contributor" i vanliga Wordpress. Följande rättigheter har de:

**Contributor**
delete_posts
edit_posts
read

https://codex.wordpress.org/Roles_and_Capabilities 

---

@regionhallandviktor commented on [Tue Oct 16 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-430148728)

Jag gör några tester för säkerhets skull så är det en sak mindre för dig David. 

---

@regionhallandviktor commented on [Tue Oct 16 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-430162681)

Default för gruppen "medarbetare" är att de kan skriva inlägg och skicka till granskning (inklusive modularity-komponenter) men att de inte kan redigera dem sedan (eller redigera andras inlägg). 

---

@regionhallandviktor commented on [Tue Oct 16 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-430171601)

Funkar bra både att ge "medarbetare" lite utökade befogenheter eller att skapa en helt ny grupp. På stage finns nu gruppen "Nyhetsredaktör" som har följande behörigheter: 

* create_posts
* delete_posts
* edit_others_posts
* edit_published_posts
* publish_posts
* read

Det finns en användare "nyhetsred" att testa med - sätt bara ett nytt lösen som admin vid användning eller skapa en egen användare. 

Hojta om samma inställningar skall replikeras på skarp server. Aktiverade tillfälligt "User role editor" som redan fanns installerat och den finns också på skarpa installationen så snabbt gjort att få det fixat. 

Ett aber bara - kolla att det som @sebastiansson gör med custom post type för nyheter inte stökar till det. 

---

@regionhallandviktor commented on [Tue Oct 16 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-430172115)

För QA: Är beteende på stage det önskade (se ovan)? Isf kan jag eller någon annan lätt återskapa det på prod.

---

@JohannaOlin commented on [Wed Oct 17 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-430509279)

@regionhallandviktor När jag skapar en ny användare med behörigheten "Nyhetsredaktör" på stage så kan den endast redigera befintliga inlägg, inte skapa nya.

---

@regionhallandviktor commented on [Wed Oct 17 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-430621939)

@JohannaOlin Mycket knepigt eftersom jag gav dem både create och publish-behörighet samt verifierade att det funkade. Men jag har utökat så att nyhetsredaktörer har alla behörigheter som över huvud taget finns kring poster (=nyheter) och testkört med nyhetsred. Hoppas att jag bara missade något så det inte är något mer esoteriskt fel :)  Prova gärna igen - jag har testat med en användare med samma behörighetsgrupp som din. 

---

@regionhallandviktor commented on [Wed Nov 28 2018](https://github.com/RegionHalland/halland/issues/252#issuecomment-442440734)

Den här får vi kika på igen :)

**Comment by JohannaOlin** [comment]
Vi kommer behöva lägga in detta både för regionhalland.se och för vårdgivarwebben. Acceptanskriterierna gäller fortfarande

**Comment by viktor-sarge** [comment]
Upptäckte en grej - eftersom nyheter inte längre är en vanlig post så behöver vi kolla att det går att styra på custom post types. Kikar med en gång.

**Comment by viktor-sarge** [comment]
Testade på stage-vardgivare och upptäckte att 1) Man måste ge användarna rättighet att hantera "posts" över huvud taget för att de skall kunna se custom post types. 2) Om man ger användarna access till en viss custom post type så spiller det över på alla övriga också. 

En googling antyder att det kan finnas ett sätt att styra det här genom att sätta en "capability" på varje ny custom post type som man definierar. https://www.role-editor.com/forums/topic/capabilities-in-custom-post-types/ Roland och jag kikar vidare.

**Comment by viktor-sarge** [comment]
Roland och jag snokade vidare igår och Roland byggde om en plugin så att den fick capabilities. Tyvärr segade sig servern (stage-rh) under uppdatering så jag hann aldrig se resultatet, men vi kikar vidare idag. Förhoppningsvis har vi hittat ett sätt att kunna styra behörigheten till enskilda custom post types.

**Comment by viktor-sarge** [comment]
(Om allt funkar så är stage-rh redan förberedd nu så att det bara är lite config kvar att göra)

**Comment by viktor-sarge** [comment]
Jag har satt upp en behörighet "nyhetsredaktör" på stage-rh som bara har behörighet till just nyheterna. Det verkar fungera bra vad jag ser. Vill inte labba för mycket ifall de nu faktiskt använder den, men är det något som är på tok så tror jag att det är en snabb justering. Nu är vi över tröskeln när vi vet hur vi styr access till funktioner som kommer från specifika plugins (och bara dessa). Funktionen är densamma mellan post-types, men man namnger dem olika för att kunna separera behörigheten. 

För att kunna leverera önskad funktion fick jag aktivera "User role editor" också. Men nu kan de prova på stage-rh. Bara att lägga till extra behörighet till de som behöver, eller ge folk bara behörighet till nyheter om det är det enda de skall göra. 

Lägger till QA för bedömning.

**Comment by JohannaOlin** [comment]
Den funkar bra tycker jag. Lägger den till ready for release. Den är ju egentligen produktionssatt på nya regionhalland eftersom vi inte har något separat produktionsmiljö där. Men vi behöver lägga in den på vårdgivarwebbens produktionsmiljö också.

**Comment by viktor-sarge** [comment]
Toppen! Då är det bara att uppdatera composer för vårdgivarwebben och läsa in den där med så kan jag ställa in det.
