### ISSUE TITLE
Mät alla färger i den grafiska profilen mot svart och vitt

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#138]

**Comment by viktor-sarge** [comment]
Nu är jag färdig med genomgången. Alla färger går att få att nå AA-nivå (och de flesta AAA) om man har antingen svart eller vit text. 

I exceldokumentet finns två blad. Det ena om färgernas kontrast mot svart/vit text och det andra om färgernas inbördes kontrast (för att kolla om t.ex. Active state blir tillräckligt tydligt mellan två färger) 

https://rh-my.sharepoint.com/:x:/g/personal/viktor_sarge_regionhalland_se/ERLjvOhPpwNJrrMkMV4gL_cB3CT6VoKNxKktHbFY1jd8IQ?e=cjOCpd

Leverarad. @JohannaOlin   @fridabergentoft

**Comment by viktor-sarge** [comment]
Förresten @fridabergentoft  Den orangea "Soluppgång" från grafiska profilen funkar som active state mot "Djupblå" och "Livskraft" men inte mot de övriga. (Sedan vet jag att det inte är riktigt de nyanserna som används idag)
