### ISSUE TITLE
Ta fram en lista på alla snabbadresser som idag finns på regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#139]
# Beskrivning
På nuvarande regionhalland.se finns idag ett antal sidor som har snabbadresser, ex Vårdcentralen Åsa har adressen http://regionhalland.se/vcasa. Vi behöver lösa så att dessa adresser fungerar även på den nya regionhalland.se

# Acceptanskriterier
- [x] Ta fram en lista på vilka adresser som finns idag
- [ ] Stäm av listan med Kommunikationsavdelningen så att länkarna fortfarande är aktuella

**Comment by viktor-sarge** [comment]
Mailat en lista på de adresser vi har idag till @JohannaOlin Det är 522 i dagsläget.

**Comment by JohannaOlin** [comment]
Kommunikationsavdelningen har fått listan så vi stänger detta ärende. De kan själva lägga in dem på sidorna när de skapas.
