### ISSUE TITLE
Navigationskorten på översiktssidor skall använda excerpt-fält istället för utdrag ur sidans text

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#143]
# Beskrivning
På sektionssidorna på vårdgivarwebben visas idag ett utdrag från texten på navigationskorten, detta ska ändras så att denna text hämtas från en specifikt fält

# Acceptanskriterier
- [ ] Som redaktör kan jag fylla i navigationstext för en sida
- [ ] Som besökare ser jag navigationstexten på navigationskortet på sektionssidan.

**Comment by JohannaOlin** [comment]
Denna tas med i arbetet med Vårdgivarwebben
