### ISSUE TITLE
Prototyp - Komponent för filtrering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#144]
# Beskrivning
Komponent som ska användas på sidor där man kan filtrera innehållet. Exempelvis på söksidan

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut och fungerar i desktop, tablet och mobil

**Comment by viktor-sarge** [comment]
Några tankar: 
* Jag hade spontant gjort alla filterknapparna lika breda  om inte texten tvingar dem att bli extra breda.
* Om inte texten tvingar en drop down att vara bredare än föräldrarutan så hade jag gjort dem lika breda. 
*

**Comment by viktor-sarge** [comment]
Ser bra ut. Och jag gillar att båda de aktiva delarna är oranga.   

Kan vi använda en knapp istället till "Återställ filtrering"? Den kan fortfarande ha ikonen. Tänker på att: 
* det är en central funktion
* klickmålet är litet
* det skulle inte ta mer plats med en knapp
* knappar är för actions på data medan länkar bara flyttar oss till en ny sida

**Comment by viktor-sarge** [comment]
Failed QA men vi är redan överens efter muntlig avstämning
