### ISSUE TITLE
Prototyp - Komponent för träfflistekort

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#145]
# Beskrivning
Ta fram en prototyp för att visa hur en träff i en sökträfflista ser ut.

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut och fungerar i desktop, tablet och mobil
- [ ] Prototypen ska ha med följande för varje träff: Rubrik, länkstig, typ av träff, text från träffen
- [ ] Prototypen ska visa hur besökaren ska klicka för att komma vidare till träffen

**Comment by viktor-sarge** [comment]
Några snabba reflektioner: 
* Vilket datum som visas är en aning oklart. Är det t.ex. publicerat eller uppdaterat? 
* Den blå träffen - är det aktivt kort när man tabbar? (Så inte alla länkar skall se ut så)
* Tänkte mäta den grå för brödsmulorna också.

**Comment by viktor-sarge** [comment]
Efter avstämning tog vi idag bort den blå träffen och beslöt att länkar alla samlas i högerspalten och träfflistan bara har "vanliga" sökresultat.

**Comment by JohannaOlin** [comment]
För min del så är denna ok nu. Är den ok med dig @regionhallandviktor  så kan du dra över den till Ready for release.

**Comment by viktor-sarge** [comment]
Gött. Jag gör det. Passed QA för min del.
