### ISSUE TITLE
Beräkningar för analysförteckningen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#147]
# Beskrivning
I analysförteckningen finns idag två sidor med uträkningar: 
http://www.regionhalland.se/vard-halsa/for-vardgivare/laboratorier/klinisk-kemi-och-transfusionsmedicin/klinisk-kemi/mer-om-analysen1/lathund-for-bestamning-av-provtagningar-vid-iohexolundersokningar-pa-vuxna-/

http://www.regionhalland.se/vard-halsa/for-vardgivare/laboratorier/klinisk-kemi-och-transfusionsmedicin/klinisk-kemi/mer-om-analysen1/berakning-av-absolut-gfr/.

För att kunna stänga analysförteckningen så måste vi lösa dessa beräkningar på vårdgivarwebben.

# Kontakt
Elisabeth Holmqvist

**Comment by viktor-sarge** [comment]
Beräkningarna bor idag på 
https://analysforteckning.regionhalland.se/vard-halsa/for-vardgivare/laboratorier/analysforteckning/berakning-av-absolut-gfr/
 
https://analysforteckning.regionhalland.se/vard-halsa/for-vardgivare/laboratorier/analysforteckning/lathund-for-bestamning-av-provtagningar-vid-iohexolundersokningar-pa-vuxna-/?id=8039

**Comment by JohannaOlin** [comment]
Beräkningarna ska vara enligt nedan:

[https://app.zenhub.com/files/158801558/5c43b889-88cf-4e23-803f-8d5b1ec055e9/download](https://app.zenhub.com/files/158801558/5c43b889-88cf-4e23-803f-8d5b1ec055e9/download)

Absolut GFR:
Ytnormaliserat GFR /1,73 * kroppsyta där
Kroppsyta = vikt^0,425 * längd^0,725 * 0,007184
Vikt i kg, längd i cm och kroppsyta i m^2

**Comment by JohannaOlin** [comment]
Flyttad till DevOps, 2515
