### ISSUE TITLE
Styrda dokument som är i excel går inte att öppna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#148]
# Beskrivning
De flesta styrda dokument är word-filer, men det finns även andra format bland de som exporteras till vårdgivarwebben. Vi har upptäckt att de dokument som är i excel inte går att öppna.

T ex 
http://styrdadokument.regionhalland.se/doc/9E976C87-EE67-4DA4-ADF8-06E8139CAC38
http://styrdadokument.regionhalland.se/doc/DF660717-E5AB-4031-9AA9-80AAD42C9F5A

**Comment by JOHNREGIONHALLAND** [comment]
Nästan OK...
Dokument går att öppna.

**Comment by JohannaOlin** [comment]
Jag sätter denna som ok och skriver ett nytt kort på de justeringar som behöver göras
