### ISSUE TITLE
Prototyp för kalender

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#149]
# Beskrivning
Vi har behov av en kalenderfunktion på många av webbplatserna. Tanken är att vi ska ha en kalenderfunktion och att vi taggar upp det som ska visas, ex Incidentrapporter, Driftinformation, Politiska möten mm. På sidorna kommer vi sedan att visa en kalender och välja vilken typ av aktiviteter som ska visas

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut och fungerar på desktop, tablet och mobil
- [ ] Prototypen ska visa hur vald dag i kalendern ser ut
- [ ] Prototypen ska visa skillnad mellan datum utan aktiviteter och datum med
- [ ] Prototypen ska visa hur man går till föregående månad
- [ ] Prototypen ska visa hur man går till nästa månad
- [ ] Prototypen ska visa hur man kan välja en månad längre fram/bak
- [ ] Prototypen ska visa hur aktiviteterna för vald dag presenteras

**Comment by JohannaOlin** [comment]
@regionhallandviktor och @fridabergentoft Jag tänker att vi tar en diskussion om denna. Jag har lite frågor kring vad som ska ingå i själva komponenten.

De fall där jag tänker att vi så småningom har för kalendern är:
- Driftstörningar
- Politiska möten
- Evenemang
- Ev Utbildningar
Sen vill vi kanske ha möjlighet att visa en gemensam kalender som innehåller allt.

Ska denna komponent innehålla både kalendern och listningen under eller är det två separata komponenter som man sätter ihop. Hur är det med filtreringen, ska den tillhöra komponenten eller bygger vi ihop flera komponenter.

**Comment by JohannaOlin** [comment]
Vi har beslutat att dela upp denna så att själva kalendern är en komponent och det är detta som ingår i detta kortet. Jag lägger ett nytt kort på komponenten Träfflistekort-kalender

**Comment by viktor-sarge** [comment]
Passerad QA för min del. Ser inga saker som behöver tweaks på det här stadiet och klickmålen verkar rimliga. Snygg och lättöverskådlig.

Skulle det framöver visa sig att punkterna som indikerar event i kalendern är svåra att se så kan vi accentuera dagen med en avvikande färg på rutan, men det blir också ganska rörigt så jag vill inte göra det i första steget.
