### ISSUE TITLE
Prototyp för Tabbar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#150]
# Beskrivning
I vissa fall behöver vi dela upp informationen på sidan på olika tabbar. Det kan t ex vara på sidan för driftinformation där vi behöver visa informationen uppdelad på IT, Telefoni och Fastighet

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut och fungerar i desktop, tablet och mobil
- [ ] Prototypen ska visa hur vald/ ej vald tabb ser ut
- [ ] Prototypen ska visa hur en tabb som är i fokus ser ut

**Comment by viktor-sarge** [comment]
Det mesta kring tillgänglighet här handlar om koden. Men jag tycker det är en liten aning otydligt att det är olika tabbar, men det blir knivigt att dra mer streck mellan dem. Kan vi prova att göra siffrorna som anger träffantal med labels istället? Formen kan vara samma som nu bara det att inaktiva tabbar får blå "bubbla" istället. Även de tre punkterna på "Fler kategorier" kan dra nytta av det, idag är det lite otydligt då kontrasten mellan vit och ljusgrå är så låg.

**Comment by viktor-sarge** [comment]
sätter "failed QA" bara för att komma ihåg att vi skall testa med blå label. I övrigt passerad QA för min del.
