### ISSUE TITLE
Prototyp för direktlänk

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#151]
# Beskrivning
I sökfunktionen kommer vi att manuellt kunna lägga in sökord som ska leda till träffar på information som inte finns på webbplatsen. Vi använder detta om sökordet är vanligt förekommande och vi har en tydlig bild av vad användaren är ute efter.

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut på desktop, tablet och mobil
- [ ] Prototypen ska visa en rubrik för träffen
- [ ] Prototypen ska visa information om träffen (text som sökredaktören fyller i)
- [ ] Prototypen ska visa att det går att klicka på träffen

**Comment by JohannaOlin** [comment]
@fridabergentoft Kolla med Viktor om den som finns är ok

**Comment by fridabergentoft** [comment]
Länk till direktlänk: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1204%3A1000&viewport=-1265%2C1093%2C0.290854&scaling=min-zoom

**Comment by viktor-sarge** [comment]
Tror ju fortfarande att de här kanske bor bäst i en box vid sidan av, men vill man ha dem direkt i träfflistan så ser jag inga direkta tokigheter med lösningen som ligger i figma just nu. 
Ok med mig.
