### ISSUE TITLE
Prototyp för Metadatakomponent

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#152]
# Beskrivning
När användaren får träff på ett styrt dokument så kan hen välja att klicka fram mer information om dokumentet. Då visas dokumentets metadatainformation, ex när det publicerades, vem som fastställde, vem som är redaktör mm. 
Denna komponent används även i andra typer av listningar med styrda dokument

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut och fungerar på desktop, tablet och mobil
- [ ] Prototypen ska visa hur komponenten ser ut innan man har valt att visa metadatan
- [ ] Prototypen ska visa hur komponenten ser ut när man har valt att visa metadatan

**Comment by viktor-sarge** [comment]
Jag uppskattar förändringen i att använda + och -. Jag har inga synpunkter på utfällt läge heller.

En möjlig synpunkt att ta under övervägande är att datum och tagg är små och blir svårlästa jämfört vanlig text. Jag uppfattar det som att anledningen är layout. Vore det möjligt att istället lägga datum och tagg högerställt underst på kortet?

**Comment by JohannaOlin** [comment]
@regionhallandviktor Datum och tagg tillhör komponenten Träfflistekort. Är denna ok i övrigt så kan du flytta den. Lägg kommentaren om datum och tagg på nr 145 så kan vi diskutera den.

**Comment by viktor-sarge** [comment]
Ser också att beroende på vad som är i träfflistan så blir den layouten jag föreslog riktigt knepig. Det är nog bättre att vi kikar på eventuella ändringar när vi har lite större variation av riktig data att jobba med. 

Passed QA för mig. Flyttar den.
