### ISSUE TITLE
Prototyp för Paginering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#153]
# Beskrivning
I bland består listor av så många poster så att vi behöver dela upp dem på olika "sidor", dvs att vi t ex hämtar 10 dokument och att man kan klicka sig fram till nästa 10.

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut och fungerar i desktop, tablet och mobil
- [ ] Prototypen ska visa hur vald respektive ej vald sida ser ut
- [ ] Prototypen ska visa hur en sida som är i fokus ser ut

**Comment by viktor-sarge** [comment]
Storleken på klickmål är ett aber. Men den här är betydligt bättre än metadatakomponenten. Jag är inte säker på om den verkligen är 44 CSS-pixlar, men tycker inte den är så liten att vi behöver blocka den i QA. Passerad för min del så kan vi ev. tweaka när vi ser den på stage som implementerad.
