### ISSUE TITLE
Prototyp för Alfabetisk gruppering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#154]
# Beskrivning
I vissa fall är det bäst att lista innehåll utifrån alfabetet. Det kan t ex vara analysförteckningen. Vi behöver en komponent som visar hur bokstäverna ska listas

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut och fungerar på desktop, tablet och mobil
- [ ] Prototypen ska visa hur vald respektive ej vald bokstav ser ut
- [ ] Prototypen ska visa hur en bokstav som är i fokus ser ut
- [ ] Prototypen ska visa hur komponenten ser ut om inte alla bokstäver innehåller information

**Comment by viktor-sarge** [comment]
Över lag ser jag inte några stora fel. Det finns en grafisk gruppering av träffresultaten som fungerar för seende. För användare med skärmläsare så behöver man nog vara lite mer omsorgsfull och förklara rollerna. Att det inte bara är "A" utan kodas så att de hör t.ex. "grupperat på A i alfabetisk listning" eller något liknande.   Jag funderar på om cirklar erbjuder ett sätt att bygga plats för större träffmål, men av naturliga skäl så kommer det såklart att bli utrymmeskrävande. 

Det lilla "i"-tecknet är nog knepigare. Det ser ut som ett väl litet klickmål. Riktlinjen i WCAG är att använda klickmål som är minst 44x44 CSS-pixlar. (Obs - inte skärmpixlar. 96 CSS-pixlar motsvarar en "inch" på högupplösta skärmar och ungefär en inch på lågupplösta. Detta är också i underkant vilket artiklar som denna visar https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/)

Samma sak med storleken på klickmålet för själva alfabetet. Det är lätt att klicka fel i alfabetiska listor. 

Kontrasten i alfabetet är också lite knepig. Man kan hävda att det är en inaktiv del av gränssnittet och därmed inte behöver följa kontrastkraven. För inaktiva bokstäver kommer inte vara synliga alls för många. Frågan är vad man gör med edge case som att t.ex. bara enstaka bokstäver ger träff. Hur tolkas det om man bara ser "            I                       X      "   och inget annat :)

**Comment by viktor-sarge** [comment]
Den nya A-Ö ser ut att vara en klart bättre utgångspunkt - snyggt jobbat! 

Samma med plustecknet som knyter ihop gränssnittet så att liknande funktioner utformas likadant. Blir bra. 

Passerad QA för min del.
