### ISSUE TITLE
Användartesta navigering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#155]
# Beskrivning
Vi behöver testa med några användare så att de förstår navigeringen, dvs huvudmeny, sekundärmeny samt vänsternavigation som börjar om från en Section page

Kontakta några användare och visa upp navigeringen från prototypen. Om du tittar i Intranätbrevlådan under Pågående - Johanna så finns det en mapp som heter Vårdgivarwebben. Där finns några som du kanske skulle kunna använda som testpersoner. De är dock inte vidtalade när det gäller detta specifika ärende.

Ytterligare en som skulle kunna vara bra att testa med är Peter X Johansson (Vårdhygien), han är inte så nöjd med dagens navigation.

**Comment by viktor-sarge** [comment]
Utmärkt! Skall vi vänta tills Fridas nya finns på plats i stage eller kör vi på skisser alt. den nuvarande i prod @JohannaOlin ? Hoppas ju att vi har den nya navigationen på plats i stage inom några dagar.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Det är bra om detta är klart i mitten av januari (beroende på om det går att få tag på några som kan testa), men det är ju klart bättre om vi kan köra testerna i stage så avvakta lite och se om vi får in det där.

**Comment by viktor-sarge** [comment]
Tack för snabbt förtydligande. Känns spontant som det är fullt möjligt. John planerar att lägga in komponenterna i stage om jag minns rätt så det borde vara på plats i tid för att hinna testa tills dess.

**Comment by viktor-sarge** [comment]
För tydlighets skull: jag planerar in tester så fort jag ser att vi har chans att få komponenterna byggda och implementerade på stage, men i dagsläget så får den här ligga kvar i sprint backlog.
