### ISSUE TITLE
Komponent för Bild och bildtext

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#156]
# Beskrivning
Kodandet av prototypen Bild och bildtext

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter:
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=66%3A12&viewport=-1311%2C-756%2C0.524907&scaling=min-zoom

**Comment by viktor-sarge** [comment]
Heja @brightjennie! Hittade bara en sak. Skulle vilja knyta ihop figcaption med bilden så att talsyntes kan fånga upp bildtexten även om ingen alt-text anges. Skulle vilja ändra rh-image-caption.hbs till följande: 

```
<figure class="{{name}}">
    <img src='/images/components/figure/bild.jpg' alt='Text som beskriver bilden' / aria-labelledby="334455">
    <figcaption id="334455">{{caption}}</figcaption>
</figure>
```

**Comment by viktor-sarge** [comment]
Frida hade inga synpunkter på det visuella.

**Comment by viktor-sarge** [comment]
Nu var du allt för snäll @brightjennie :) Det jag postade ovan var ju alldeles koko. Enkelfnuttar blandat med dubbel och en mystisk / mitt i alltihopa. Undrar om jag mådde riktigt bra i förmiddags. Provar om det inte blir rimligare såhär:

```
<figure class="rh-image-caption">
    <img src="/images/components/figure/bild.jpg" alt="Text som beskriver bilden" aria-labelledby="334455">
    <figcaption id="334455">This is a image, with supporting caption</figcaption>
</figure>
```

**Comment by viktor-sarge** [comment]
Sorry @brightjennie  Mitt fel så jag ändrar gärna i branchen, men vill inte ge dig merge-problem om du redan jobbat vidare.

**Comment by brightjennie** [comment]
Ingen fara! Har ändrat nu! Helt klart lättare om jag ändrar för inte få problem med git ;)

**Comment by viktor-sarge** [comment]
Tack! :) Då lägger jag den som ready for release
