### ISSUE TITLE
Deploy-verktyg

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#159]
När vi flyttar till egna servrar behöver vi ett deploy-verktyg som flyttar koden från git-källan till servern och ser till att servern får installerat rätt tredjepartsbibliotek, plugins osv. I dagsläget används Forge vilket fungerar bra, men den behöver access till servern vilket inte verkar fungera pga portar som inte är öppna (och ev inte ens får öppnas). John vet mer. 

I alla händelser behöver vi bestämma hur vi hanterar deploy och vilket verktyg som skall användas när vi flyttat till egna servrar. Att FTP:a kod med Filezilla är inte ett rimligt alternativ. Att sätta upp ett git-repo på servern och sköta deploy med "git pull" på servern är endast marginellt bättre och heller inte ett rimligt alternativ. 

Automatisering behövs i alla händelser för att minska felkällor och få ett snabbt arbetsflöde.

**Comment by viktor-sarge** [comment]
Efter att ha läst lite mer så tror jag att vi vill göra deploy ifrån Jenkins och antagligen som två separata flöden (ett som testar och deployar till stage från en branch och ett som deployar till prod-servern från en annan branch). Eftersom Jenkins är CI/CD-fokuserat och tänkt för kontinuerlig integration/deploy så ser jag inget annat sätt att vänta med deploy till prod än att ha olika flöden. 

Tanken blir isf att vi pushar koden till exempelvis #master branchen och har den som unstable. Jenkins kör alla testar (nu i början har vi inte ens några) och kollar att allt är grönt innan den deployar koden till testservern. Sedan gör vi en manuell koll om sådan behövs och Johanna godkänner. När saker är färdiga så pushar vi till en egen branch (förslagvis #production så att folk inte pushar till #master av gammal vana) och så körs liknande tester en ytterligare vända innan den samlade kodbasen sedan deployas till produktionsservrarna.

**Comment by JOHNREGIONHALLAND** [comment]
Synka med mig med info @regionhallandviktor .
