### ISSUE TITLE
Komponent för Sidinformation

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#161]
# Beskrivning
Komponenten innehåller information om när sidan publicerades och kan innehålla information om vem som är sidansvarig

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari
- [ ] Kontakta sidansvarig ska default inte visas nu. Så småningom kanske vi vill ändra defaultläget dock.

**Comment by fridabergentoft** [comment]
Länkar till komponenter:
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=90%3A117&viewport=-1311%2C-756%2C0.524907&scaling=min-zoom

**Comment by brightjennie** [comment]
Den fick namnet rh-feedback efter namnet den har i Figma. Det blev en komponent men det är ju bara att inte skriva ut all html om man inte vill ha den första delen. I Figma var denna uppritad som två varianter.

**Comment by viktor-sarge** [comment]
Ser rätt ut grafiskt (stämt av med Frida), men jag klurar lite på att det som finns i organismer nog också borde finnas som enskilda molekyler. Därför föreslår jag följande: 

Lägg två molekyler: 
- "Senast uppdaterad" (bara två rader text, tror inte ens de behöver en container)
```
	<p>Senast uppdaterad: <strong>30 augusti 2018</strong></p>
	<p><a>Kontakta sidansvarig</a></p>
```
- "Feedback" 
```
<div class="rh-feedback">
	<hr>
	<p>Fick du hjälp av informationen på sidan?</p>
	<button class="{{btn-class}}" aria-label="Text som förklarar funktionen om man lyssnar med talsyntes utan att se kontexten" role="button">Ja</button>
	<button class="{{btn-class}}" aria-label="Text som förklarar funktionen om man lyssnar med talsyntes utan att se kontexten" role="button">Nej</button>
</div>
```

Den befintliga organismen kan vi köpa till "Senast uppdaterad och feedback" och se om det här funkar: 
```
<p>Senast uppdaterad: <strong>30 augusti 2018</strong></p>
<p><a>Kontakta sidansvarig</a></p>
<div class="rh-feedback">
	<hr>

	<p>Fick du hjälp av informationen på sidan?</p>
	<button class="{{btn-class}}" aria-label="Text som förklarar funktionen om man lyssnar med talsyntes utan att se kontexten" role="button">Ja</button>
	<button class="{{btn-class}}" aria-label="Text som förklarar funktionen om man lyssnar med talsyntes utan att se kontexten" role="button">Nej</button>
</div>
```
Jag tyckte det såg ut som att du inte behöver tweaka CSSen med en sådan lösning, och då kan man fortfarande använda molekylerna separat om någon ritar en design där de inte längre sitter ihop

**Comment by brightjennie** [comment]
Bra tanke! Blev mycker mer "cleant". 

#161 delades upp och blev först två molekyler rh-feedback och rh-last-updated. Organismen som består av båda dessa molekyler heter rh-feedback-last-updated.

**Comment by viktor-sarge** [comment]
Looking good! Ber bara att du slänger på en time-tagg också: 

```
<p>Senast uppdaterad: <strong><time datetime="2018-08-30">30 augusti 2018</time></strong></p>
<p><a>Kontakta sidansvarig</a></p>
```

Eftersom de här kommer genereras maskinellt så kan vi faktiskt vänta oss att det blir korrekt ifyllt och då kan det vara gott att det är upptaggat ordentligt :)

**Comment by brightjennie** [comment]
Åtgärdat!

**Comment by viktor-sarge** [comment]
Tack Jennie! 

Passed QA. Jag lägger till "Ready for release"
