### ISSUE TITLE
Komponent för textfält

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#162]
# Beskrivning
Komponenten används för att lägga in text på sidor

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=31%3A5&viewport=408%2C399%2C0.338725&scaling=min-zoom

**Comment by viktor-sarge** [comment]
@fridabergentoft och jag har kikat och tycker det ser bra ut. 

Passed QA och vi flyttar till ready for relase.
