### ISSUE TITLE
Komponent för tabell

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#163]
# Beskrivning
Komponent för tabeller som ska användas i webbplattformen

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Element till tabell: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=239%3A0&viewport=-640%2C2382%2C0.773945&scaling=min-zoom

Hela tabellen, exempel: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=239%3A48&viewport=-262%2C351%2C0.363391&scaling=min-zoom

Tabellen har lite specialfunktioner, vi kan ta ett möte via teams om det är svårt att förstå hur komponenten ska fungera

**Comment by brightjennie** [comment]
Det finns ett första utkast på tabellen. Komponenten ligger endast som organism och inte som atomer. Rh-table

**Comment by fridabergentoft** [comment]
Tabellen fungerar som den ska men ser lite knasig ut. Scrollbaren är inte under hela tabellen och prickarna i badgen är ihåliga
