### ISSUE TITLE
Komponent för Filmer

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#164]
# Beskrivning
Komponent som ska användas för att bädda in film

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter:
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=66%3A12&viewport=-1311%2C-756%2C0.524907&scaling=min-zoom

**Comment by viktor-sarge** [comment]
Passed QA. 

(Note to self: För tillgängligheten kommer vi att behöva erbjuda t.ex. en likvärdig textversion, men det är lite svårt att här specificera exakt hur det kriteriet skall uppfyllas. En sådan kan presenteras på lite olika sätt. )

**Comment by viktor-sarge** [comment]
Får tyvärr öppna den här igen, vi upptäckte att det inte fungerar i Safari. Kan handla om filformatet. Har ni mac så att ni kan testa? (Annars får vi kika på det)

**Comment by brightjennie** [comment]
Största sannolikhet filmformatet. Testade ett annat samt tog bort max-width så nu skalar den 100%. Kika igen. För mig funkar den nu i Safari.
