### ISSUE TITLE
Komponent för dokument

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#165]
# Beskrivning
Komponent för att visa hur länkar till dokument ser ut och fungerar

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter:
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=31%3A5&viewport=408%2C399%2C0.338725&scaling=min-zoom

**Comment by viktor-sarge** [comment]
(överlappnignen med storyn "länkar" är så stor att jag släcker den här tills vidare. Allt ligger ändå i rh-links)
