### ISSUE TITLE
Komponent för Länkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#166]
# Beskrivning
Komponent för länkar i brödtext

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter:
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=31%3A5&viewport=408%2C399%2C0.338725&scaling=min-zoom

**Comment by viktor-sarge** [comment]
Ändra aria-label på a-taggen till ett title-attribut istället :)

(Jag har testat aria, title, aria+title och försökt avgöra vad som blir bäst i kombination med hur våra redaktörer tänker. Landat i att ett title-attribut på länkar + att jag tjatar på dem om hur de formulerar länkar blir bästa lösningen.)

**Comment by viktor-sarge** [comment]
Hej @brightjennie - lite feedback: 
* Ändrade du aria-label till ett title-attribut? (För mig ser det ut som innan) 
* Klassnamnen behöver BEM:as - "external" och "container" är för generella och behöver bli t.ex. "rh-link--external" eller något liknande. 
* Hur infogas ikonerna? Jag ser bara rh-link.config.json och rh-link.hbs som inte ger några ledtrådar. Jag har snokat runt och försökt se om det ligger utanför i någon annan scss eller js men börjar tro det är snabbare att bara fråga dig :)

**Comment by brightjennie** [comment]
Hej @regionhallandviktor 

Såg inte din tidigare kommentar om title-attribut. Det är fixat nu. 

Jag hade inte satt någon klass på länkar men har gjort det nu och uppdaterat alla länkar som förekommer i andra komponenter. 

Angående ikonerna så har jag skrivit in en länk i _preview.hbs som ligger i rooten på mappen components. Sen använder jag font-family och content för att få in ikonerna där jag vill ha dom. 

Hoppas att det blir lite tydligare nu :)

**Comment by viktor-sarge** [comment]
- [x] Title-attribut istället för aria-label

- [x] BEM:a klassnamn

- [x] Hur ikonerna infogas.

**Comment by viktor-sarge** [comment]
Tack för uppdateringen @brightjennie. Förstod inte var koden för att infoga ikonerna låg när de inte fanns i rh-link som en .scss-fil, men hittade det i typografin. Ur ett övergripande perspektiv är det klokt att den ligger i typografin, men för de som kikar i Fractal-webbplatsen så blir det lite knivigt. 

Passed QA och jag lägger till ready for release så låter vi den vara tills vidare.
