### ISSUE TITLE
Komponent för formulär

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#167]
# Beskrivning
Komponent som ska användas för formulär

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=45%3A0&viewport=3671%2C2814%2C0.186684&scaling=min-zoom

Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=169%3A62&viewport=9975%2C9136%2C0.6518&scaling=min-zoom

**Comment by brightjennie** [comment]
Denna är påbörjad men har en bit innan den är färdig. Finns i rh-form
