### ISSUE TITLE
Komponent för Artikel

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#168]
# Beskrivning
Komponent som ska användas för artikelsidor (nyheter)

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=126%3A111&viewport=-651%2C2076%2C0.782204&scaling=min-zoom

Endast Artikel-komponenterna

**Comment by brightjennie** [comment]
Heter rh-article

**Comment by viktor-sarge** [comment]
Ser helt rimligt ut kodmässigt. Jag låter Frida ha synpunkter på det visuella men lägger över till "ready for release"
