### ISSUE TITLE
Uppdaterat datum ska visas på sidorna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#170]
# Beskrivning
Nu uppdateras datumet på sidan inte när sidan uppdateras, det verkar vara skapat (eller när sidan publicerades första gången) som visas.

# Acceptanskriterier
- [ ] Som redaktör ska jag inte manuellt behöva ändra datumet när sidan publiceras på nytt
- [ ] Som besökare ser jag datum för senast ändrad

**Comment by RolandHyden** [comment]
Ok, då har jag justerat så att datumet = senast ändrat. Detta är justerat både på stage och skarp.
