### ISSUE TITLE
Skiss - Viktigt meddelande i förhållande till övrigt innehåll

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#172]
# Beskrivning
Innan vi kan lägga in komponenten Viktigt meddelande på webbplatserna så behöver vi bestämma hur den ska visas i förhållande till övrig information

# Acceptanskriterier
- [ ] Skissen ska visa hur detta ser ut på desktop, tablet och mobil
- [ ] Skissen ska visa förhållandet mellan Viktigt meddelande och cookienotisen
- [ ] Skissen ska visa förhållandet mellan Viktigt meddelande och sidhuvudet

**Comment by fridabergentoft** [comment]
Hur komponenten viktigt meddelande ser ut i förhållande till övriga komponenter visas här:

Desktop https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=0%3A1&viewport=671%2C-1494%2C0.27202&scaling=min-zoom

Tablet: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=2562%3A1&viewport=431%2C415%2C0.106731&scaling=scale-down

Mobile: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=269%3A4481&viewport=-4239%2C573%2C0.496151&scaling=scale-down

**Comment by viktor-sarge** [comment]
Jag har inga synpunkter. Passed QA för min del.

**Comment by JohannaOlin** [comment]
Ok för mig med
