### ISSUE TITLE
Integration med Varbi

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#174]
# Beskrivning
Regionen ska börja använda rekryteringssystemet Varbi istället för Offentliga jobb. Detta ska integreras med både intranätet och regionhalland.se. Tanken är att detta system ska införas ungefär samtidigt som vi lanserar nya regionhalland.se.

Leverantören har ett testflöde som vi kan testa mot. Jag har fått följande information från leverantören:

Tar och skickar över ett JSON-testflöde direkt. Så har ni detta tillgängligt när ni påbörjar arbetet.

Test-data hittar ni här: 
https://feeds.varbi.com/json/foretaget

Vi har en enklare dokumentation här: https://www.varbi.com/docs

JSON-flödet innehåller all information om annonsen inklusive beskrivning av organisation och underavdelningar (så som det är uppsatt i Varbi). Det finns länkar direkt till inloggnings-läge samt annonsvisning i Varbi.

Har ni några som helst frågor eller funderingar så ställ dessa med fördel till vår Support på support@varbi.com där jag eller någon av mina kollegor kan svara er :-) 

Era riktiga JSON-flöden för produktionsdata:

 - Externa: https://feeds.varbi.com/json/regionhalland/position/
 - Interna: https://feeds.varbi.com/json/regionhalland/position/?token=70117c353fde97237ec4b71a130d841b

**Comment by JohannaOlin** [comment]
Senast i mitten av februari kommer vi att få en spec från Kommunikationsavdelningen/HR på vilka filtermöjligheter man vill ha samt i vilken ordning de ska visas. De kommer även att speca ner hur mycket de vill visa direkt i listningen och vilka fält som ska visas på fullposten.

I detta första steg ska vi endast se till så att vi kan hämta ut informationen från Varbi.

**Comment by RolandHyden** [comment]
Hej Johanna.
Jag har byggt en plugin som (än så länge) bara hämtar ut testdata från Varbi och presenterar arrayen som den är. Jag ville inte göra mer eftersom ingen funktion är bestämd ännu.

Pluginen ligger i repot (privat):
https://github.com/RegionHalland/region-halland-varbi-works
Just nu används release v1.0.0

Exempel på hur sidan på stage-rh ser ut är:
stage-rh.regionhalland.se/jobb-och-karriar/lediga-jobb/

Som sagt, bara data utan design. Men grunden är gjord och vi kan bygga vidare.
