### ISSUE TITLE
Github vulnerability webpack-dev-server

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#178]
We found a potential security vulnerability in a repository for which you have been granted security alert access.
 
RegionHalland/styleguide-v2 

Known low severity security vulnerability detected in webpack-dev-server < 3.1.11 defined in package-lock.json. 

package-lock.json update suggested: webpack-dev-server ~> 3.1.11. 
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by JOHNREGIONHALLAND** [comment]
hmm den filen innehåller en del rader
