### ISSUE TITLE
Prototyp - Komponent för listningar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#179]
# Beskrivning
Vi behöver ta fram en komponent för listningar som t ex ska användas för att lista utbildningarna för Vuxhalland och analyserna i analysförteckningen.
För exempel se https://yrkesutb-skbg.webnode.se/yrkesvux-larling/ samt http://regionhalland.se/vard-halsa/for-vardgivare/laboratorier/analysforteckning/?all=1.

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil

**Comment by JohannaOlin** [comment]
Ok för mig

**Comment by viktor-sarge** [comment]
Jag kikade på bibliotek 2.0 / Moecules / Lists. Inga invändning, men det hade varit tydligare hur utseendet är tänkt om raderna hade olika längder. Som det är nu framgår det inte helt och hållet vad som skall hända när värdena till höger blir olika långa. (vänsterställt, högerställt, centrerad..).

**Comment by viktor-sarge** [comment]
Flyttat till ready for release.
