### ISSUE TITLE
Komponent för filtrering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#180]
# Beskrivning
Byggandet av komponenten Filtrering.

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=133%3A2010&viewport=18874%2C15574%2C1.07211&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-filter

VI har testat den och den funkar i Safari, crome och firefox :)

**Comment by viktor-sarge** [comment]
Snyggt jobbat med att lösa designen! Jag har kikat lite på den och vill ta någon vända till innan vi släpper igenom den. Vill kika lite närmare på tillgängligheten, vad som händer utan JS osv.  Låter den ligga kvar så länge.

Ser du något visuellt Frida?

**Comment by fridabergentoft** [comment]
utseendet är korrekt men funktionen är lite fel.
Pilen är inte klickbar utan enbart rutan.
