### ISSUE TITLE
Komponent för träfflistekort

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#182]
# Beskrivning
Komponent för att visa en träff i en sökträfflista

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länkar till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=150%3A49&viewport=-619%2C742%2C0.21216&scaling=min-zoom

https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1039%3A17&viewport=-619%2C742%2C0.21216&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-search-elements

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd!
