### ISSUE TITLE
Komponent för paginering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#183]
# Beskrivning
Komponent för att visa paginering

# Acceptanskriterier
- [ ] Komponenten ska fungera i desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till atomer: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=144%3A3420&viewport=9385%2C6250%2C0.507414&scaling=min-zoom

Länk till exempel: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=148%3A4&viewport=-1807%2C-731%2C0.500783&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-pagination-elements

rh-pagination

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd med komponenten!
