### ISSUE TITLE
Komponent för alfabetisk gruppering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#184]
# Beskrivning
Komponent för att visa alfabetisk gruppering

# Acceptanskriterier
- [ ] Komponenten ska fungera i desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=151%3A328&viewport=488%2C-1247%2C0.550199&scaling=min-zoom

**Comment by brightjennie** [comment]
rh search

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd!
