### ISSUE TITLE
Komponent för kalender

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#185]
# Beskrivning
Komponent för att visa kalender

# Acceptanskriterier
- [ ] Komponenten ska fungera i desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till molekyler: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=144%3A2055&viewport=-1269%2C731%2C0.530842&scaling=min-zoom

Länk till organism: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=144%3A2904&viewport=-89%2C-27%2C0.294215&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-calendar-element

rh-calendar

**Comment by fridabergentoft** [comment]
Kalendern ser rätt ut när den är frikopplad. När den är tillsammans med korten ser det inte rätt ut. Sedan har är ikonen ihålig och det är inte riktigt rätt
