### ISSUE TITLE
Komponent för tabbar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#187]
# Beskrivning
Komponent för att visa tabbar

# Acceptanskriterier
- [ ] Komponenten ska fungera i desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=76%3A550&viewport=-483%2C616%2C0.628223&scaling=min-zoom

Tabbarna längst ner

**Comment by brightjennie** [comment]
rh-tabs

**Comment by fridabergentoft** [comment]
Det är en bra början men det saknas en version av tabbarna, alltså de som med hjälp av en label visar hur många träffar de innehåller.
