### ISSUE TITLE
Komponent för att visa direktänk

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#188]
# Beskrivning
Komponent för att visa direktlänk (söket)

# Acceptanskriterier
- [ ] Komponenten ska fungera i desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1204%3A1000&viewport=-5713%2C2503%2C0.82142&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-search-external-link

**Comment by fridabergentoft** [comment]
Komponenten ser korrekt ut, är dock lite osäker på om det är rätt bakgrundsfärg, det ska vara 30 % av lightblue. 
Sedan känns det som om det slår över till mobilläge tidigt?
