### ISSUE TITLE
Komponent för listningar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#189]
# Beskrivning
Komponent för att visa listningar

# Acceptanskriterier
- [ ] Komponenten ska fungera i desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=169%3A0&viewport=-1142%2C-222%2C0.490257&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-lists

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd!
