### ISSUE TITLE
Huvumeny Teknisk förslag regionhallan.se / vardgivare.rh

### ISSUE THREAD

**Issue by JOHNREGIONHALLAND** [RegionHalland/general#190]
Huvudmeny 
Teknisk förslag regionhallan.se / vardgivare.rh

Kännedom: 
nav-site.blade.php
{{-- Bottom bar --}}

v.1 Dgbyråns
@if(isset($top_level_pages) && !empty($top_level_pages))
[x] WP-standard varibel https://developer.wordpress.org/reference/classes/wp_posts_list_table/_display_rows_hierarchical/
[x] Finns ingen dropdown
[x] Ingen sortering

v.2 Roland
@php($top_level_pages = get_region_halland_tree_first_level())
@if(isset($top_level_pages) && !empty($top_level_pages))
[x] Finns ingen dropdown
[Q] dokumentation?
[x] sortering manuellt via plugin
[Q] Bugg i steg 2 tappar huvud minne

v.3 Johns WP standard
{{ wp_nav_menu( array('theme_location'=>'Main menu' , 'menu' => 'Main menu', 'container_class' => 'rh-nav-menu', 'menu_class' => 'rh-nav-menu-item' )) }}
eller synkad med automatisk Nestad Pages
{{-- wp_nav_menu( array('theme_location'=>'Main menu' , 'menu' => 'Nested Pages', 'container_class' => 'rh-nav-menu', 'menu_class' => 'rh-nav-menu-item' )) --}}
[x] Väldokumenterad WP-standard
[x] färdiga css stilar för meny utseende
[x] enkelt att sorteras via wp-admin
[x] dropdown 3 child steg eller hur man vill

* Om vi ska hålla oss till standard och väldokumenterad verktyg så  bör hålla oss till standard ramverk och inte röra WP-standard filerna

**Comment by JohannaOlin** [comment]
Funktionsmässigt så finns det egentligen ingen anledning till att redaktörerna själva ska kunna sortera om huvudmenyn. Denna kommer inte att ändras speciellt ofta och om det är en enkel sak för utvecklarna att ändra så kan det vara ok.
De som är redaktörer kommer att ha behörighet att ändra överallt och jag är inte så säker på att Kommunikationsavdelningen vill att alla redaktörer ska kunna sortera om huvudmenyn hur som helst. Så i vilket fall som helst behöver det krävas en administratörsrättighet för att man ska få lov att sortera om huvudmenyn.

I övrigt vill jag att ni tar med prestandaaspekten när ni diskuterar detta, alla ställen där vi kan förbättra prestandan är bra.
