### ISSUE TITLE
Prototyp för kontaktkort

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#191]
# Beskrivning
Vi behöver kunna visa upp vem som är kontaktperson för ett visst ämne. Detta är inte samma sak som innehållsansvarig utan på vissa sidor har man behov av att tydligare signalera kontaktperson/kontaktpersoner. Idag ser det ut så här http://www.regionhalland.se/kultur/vara-arbetsomraden/vara-arbetsomraden/konst/

# Acceptanskriterier
- [ ] Prototypen ska visa kontaktkortet på desktop, tablet och mobil
- [ ] Personens namn ska visas
- [ ] Personens titel och avdelning ska visas
- [ ] Personens kontaktuppgifter (e-post och telefonnummer ska visas)
- [ ] Personens besöksadress ska kunna visas
- [ ] Personens bild ska kunna visas
- [ ] Komponenten ska gå att använda på många placeringar på en sida

Det är inte nödvändigt att visa alla uppgifter direkt utan en del kan visas om man väljer att visa mer. Bilden kommer inte att vara obligatorisk.

**Comment by fridabergentoft** [comment]
![Skärmavbild 2019-01-21 kl. 16.06.51.png](https://images.zenhubusercontent.com/5a5c63994b5806bc2bc2bb1f/2147b18c-2fac-4d68-9724-be84278e2d08)

**Comment by JohannaOlin** [comment]
Ok för min del

**Comment by viktor-sarge** [comment]
Mätt den grå. God marginal. 

Ok för mig - drar den till ready for release.
