### ISSUE TITLE
Komponent för kontaktkort

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#192]
# Beskrivning
Komponent för att visa upp kontaktkort

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter:
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=80%3A60&viewport=-178%2C91%2C0.427458&scaling=min-zoom

**Comment by viktor-sarge** [comment]
Frida lämnar visuell QA separat. Jag kikar på koden och återkommer.

**Comment by viktor-sarge** [comment]
Lite teknisk QA: 

- [ ] Vi behöver koppla loss beroendet till specifika rubriknivåer. Nu måste det t.ex. vara h6 för att CSS:en skall slå igenom. Men rubriknivåerna skall bara användas för att strukturera innehållet - inte för att formatera det. Jag föreslår att man styr på ett BEM:at klassnamn istället, alternativt att man gör en konstruktion med klassnamn "h1", "h2" osv som man kan använda oavsett om det faktiskt är en h-tagg eller någon annan för att ge rätt utseende. På det viset kopplar man helt loss strukturen från utseendet. 

- [ ] En del pixelvärden som vi vill ha relativa mått på istället :)

**Comment by viktor-sarge** [comment]
(Assignar Frida också för synpunkter på utseendet)

**Comment by brightjennie** [comment]
Hoppas att det är bättre struktur på detta nu samt inge pixelvärden :)

**Comment by viktor-sarge** [comment]
Ser bra ut. Jag lägger den till dig @fridabergentoft  om det är något mer visuellt du har på den. Lägg till "Ready for release annars".

**Comment by viktor-sarge** [comment]
(Ändrade mig och lägger till ready for release för konsekvensen skull. Fick ett ryck och lade allt annat i den spalten så blir det likt. Vi öppnar igen om vi ser saker framöver som vi inte vill/kan ändra själva)
