### ISSUE TITLE
Strukturera komponentbiblioteket

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#193]
# Beskrivning
Vi behöver strukturera upp komponentbiblioteket i Figma så att det är enklare att hitta samt göra det tydligare för någon som inte är så insatt.

# Acceptanskriterier
- [ ] Komponenterna ska ha kommentarer
- [ ] Lägg över de färdiga komponenterna i Komponentbibliotek 2.0

**Comment by viktor-sarge** [comment]
Tror inte att jag behöver ha några synpunkter här.
