### ISSUE TITLE
Undersök om databasen för Analysförteckningen går att flytta till vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#194]
# Beskrivning
På regionhalland.se finns Analysförteckningen. Denna ska flyttas till vårdgivarwebben och vi behöver undersöka hur pass stort jobb det är att flytta befintligt innehåll. Enligt uppgift så ska detta vara en egen databas, men det är inte bekräftat. Analysförteckningen finns här http://www.regionhalland.se/analys

# Acceptanskriterier
- [ ] Få fram en lista på vad som behöver göras för att flytta databasen
- [ ] Ta fram en tidsuppskattning för flytten

**Comment by JOHNREGIONHALLAND** [comment]
EPI-Databas kopia från Farzad är på ingående 24 Jan 2019.
Ny databas kopia måste göras innan April också.
1. John konverterar SQL till Mysql.
2. Hämtar ut Analysförteckning data som egen Mysql databas.
3. Se till att det visas på Vårdgivare webben.
4. CMS vertyg för uppdatering & publicering av Analysförteckning är Oklart.

--------------------------------
Farzad: Gällande epi-databasen, den är SQL databas. Ja det går också att exportera data med tabell och struktur men i vanliga fall så tar man egentligen kopia på hela databasen till en bak-fil. Den filen kan man sen använda för att göra restore på hela databasen på SQL server.

![EPI-struktur.jpg](https://images.zenhubusercontent.com/5ba0b47d926ebd396bd72462/67b5d15f-1f6e-4186-b2f9-72dc24a1ecc6)

-------------------------------

**Comment by JOHNREGIONHALLAND** [comment]
Analys var löst… tydligen ligger den i egen databas.
Har du eller Johanna access till mappen E:\MSSQL10.WWW\MSSQL\Backup\ RH-DB backup-190123.zip på RHSQL3

Annars för access så skriver en SD så får du lägga in det på Servicedesk.
Ska också skriva SD om Citrix för Findwise.
John


Från: Farzad Tehrani-Manesh <farzad.tehrani-manesh@advania.com> 
Skickat: den 23 januari 2019 11:39
Till: Stenlund John RGS VS SYSTEMUTV IT <John.Stenlund@regionhalland.se>
Kopia: Edvinsson Erika RGS VS SYSTEMFÖRV IT <Erika.Edvinsson@regionhalland.se>
Ämne: SV: EPI server 

Hej John!

Det finns flera databaser som används. Databasen till själva episdelen är www_regionhalland.
Så jag har nu tagit kopia på alla de databaserna förutom www_solr_statistics som jag inte har rättighet till.
Förutom dessa databaser så finns det också en koppling till AD, alltså LDAP://ltdc1.lthalland.se/DC=lthalland,DC=se

Databaskopiorna ligger zippad i en fil som ligger på denna plats E:\MSSQL10.WWW\MSSQL\Backup\ RH-DB backup-190123.zip på RHSQL3

**Comment by JOHNREGIONHALLAND** [comment]
David har lagt en service desk för att placera SQL databasen som Farzad har zippat ner i testmiljö ltsql34.

http://servicedesk.lthalland.se/WorkOrder.do?woMode=viewWO&woID=578290
------

Sedan kan jag exportera till Mysql för att implantera Analysförteckning på WP eller vad dom nu vill ha på.

**Comment by JohannaOlin** [comment]
Vi kör på wordpress. Jag kommer att lägga upp ett nytt kort med de fält som behövs när det gäller det redaktionella. Sen kommer jag att skapa ett kort för visningen av analyserna för besökarna så när databasen är exporterad till Mysql så kan vi stänga detta kort. 

Jag lägger även ett kort på att hämta databasen på nytt innan vi "lanserar" den nya på vårdgivarwebben och stänger den gamla på regionhalland.se

**Comment by JOHNREGIONHALLAND** [comment]
Ny update från SD 
----
Databaser ligger på ltsql43. Logins är importerade. Ni tog inte med www_solr_statistics. Miss eller korrekt?
/Calle

Du kan följa ärendet via denna länk http://servicedesk.lthalland.se/WorkOrder.do?woMode=viewWO&woID=578290
