### ISSUE TITLE
WP-admin top meny är borta på v.2 sajterna

### ISSUE THREAD

**Issue by JOHNREGIONHALLAND** [RegionHalland/general#195]
Gällande
http://stage-vg.regionhalland.se/wp/wp-admin/
http://stage-rh.regionhalland.se/wp/wp-admin

[x] Admin top menyn är borta när man är inloggad på nya upplägget
[x] Detta blir svårt för redaktören att redigera sidor.
[x] Roland måste återställa detta

* Om vi ska hålla oss till standard och väldokumenterad verktyg så  bör hålla oss till standard ramverk och inte röra WP-standard filerna

**Comment by JohannaOlin** [comment]
Undersök kring säkerhetsproblemet för att se om vi kan lösa det på något annat sätt

**Comment by RolandHyden** [comment]
Jag har undersökt och rekommenderar att vi gör följande.

A) Skapar en blade-fil med en länk för att editera aktuell sida. Denna kan visas högst upp på en sida.

B) Runt denna blade-fil wrappar vi en plugin som returnerar true/false. Returnerar pluginen true visas länken.

C) I pluginen sätter man regler för true, dvs man ska vara inloggad plus kanske något mer. Reglerna får vi komma överens om. Dessutom lägger man en IP-spärr, dvs man MÅSTE besöka sidan via Region Hallands RHWLAN. Jag har undersökt detta med Dennis Persson och det går att via IP-numret se ifall användaren surfar via RHWLAN.

På så vis uppnår vi maximal säkerhet. Bestämmer vi att göra såhär kan Erika lägga en ticket för att få ut korrekt RHWLAN-IP-range. Det är ingen svår operation att hämta ut RHWLAN-IP-rangen via Region Hallands DHCP.

Tidsuppskattning för plugin + blade-fil + upplagt på github är runt 3-4 timmar.

**Comment by JOHNREGIONHALLAND** [comment]
Hur pass förvaltningsbar är den varianten @RolandHyden ???
Jag tycker inte vi ska hålla på och ändra Wordpress ramverket och standarden på det sättet.

Det finns faktisk bättre sätt att göra detta på.
Men självklart så lyssnar jag gärna på ditt förslag  och se hur du vill det ska funka.
