### ISSUE TITLE
Hämta information om kontaktpersoner och enheter

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#196]
# Beskrivning
Vi behöver hämta personer och enheter från Hallandskatalogen. Förslagsvis genom att fortsätta använda Biztak.

# Acceptanskriterier
- [ ] Personer som har skyddad identitet ska inte hämtas in. Attributet hsaProtectedPerson är det som används i Hallandskatalogen. Om detta är satt till Ja så ska vi inte hämta in personen.
- [ ] Endast aktiva personer ska hämtas in, dvs inte de som ligger i Limbo
- [ ] Uppgifterna ska synkas med Hallandskatalogen så om t ex ett namn eller ett telefonnummer ändras så ska detta slå igenom automatiskt
- [ ] Personer som slutar ska försvinna från kontaktkortet

**Comment by JOHNREGIONHALLAND** [comment]
- Möte med Linda onsdag
- Påbörjat skiss ur det kan tänkas fungera HAK
- Ska ta kontakt med Farzad  hur det är löst från EPI

**Comment by JOHNREGIONHALLAND** [comment]
Skickat: den 23 januari 2019 13:41
Hej John

Hallandskatalogen förvaltas av objektet Identiteter och behörigheter där Magnus och jag är objektledare respektive objektledare IT.
Så ja, du har vänt dig till rätt objekt.
Men normalt sett är det OL eller OLIT som tar kontakt med oss om det finns ett behov att konsumera uppgifter från något av våra system.
Jag gissar att det är Erika som är OLIT i detta fall och då ser vi helst att eventuella frågor hålls samman och kanaliseras via henne.

Med vänlig hälsning
Stefan
-------------------
Kika på PDF skissen. 
Jag gissar att det är så det funkar idag med EPI där regionhalland.se kan hämta.

Vi har önskemål att det ska funka så med RH  nya webbplatsen.
Speciellt att nå serven där Hak filen läggs in.
John[https://app.zenhub.com/files/158801558/1424cab3-0808-416f-bc16-5f79fea4b88f/download](https://app.zenhub.com/files/158801558/1424cab3-0808-416f-bc16-5f79fea4b88f/download)

**Comment by JohannaOlin** [comment]
Erika bokar in möte med Biztalkgänget igen för att reda ut om vi kan få en fil till wordpress.

Dölj alla fält förutom HSA.id person namn och bild. Redaktörerna får fylla i användarnamn så länge så kopplar vi det senare.

Lägg till ett kryssruta "Godkänd för publicering". Inte förrän denna är ikryssad får kontaktkortet visas på sidan.

**Comment by JOHNREGIONHALLAND** [comment]
Har fixat delen
....
Dölj alla fält förutom HSA.id person namn och bild. Redaktörerna får fylla i användarnamn så länge så kopplar vi det senare.
....
Se fliken Kontaktkort HSA: http://stage-rh.regionhalland.se/wp/wp-admin/post.php?post=99&action=edit

Bry inte om andra fält flikar bara test, men kika gärna om det önskas fler fält eller nått annat som ska läggas in på sidan.

**Comment by JOHNREGIONHALLAND** [comment]
Memo möte med Stefan via skype 30 jan
- Kanske göra en ny komponent för att integrera HAK till nya webbplatsen
- Fått mail och dokument från 2013 måste läsas.
- anropar via webbtjänst -> hsa tools
- lösningsförlag konsumeras från HSA, Magnus öberg överens, veta syfte
- biztalk kanske göra om till json

John gör en ny runda.

**Comment by JohannaOlin** [comment]
Kopplingen mellan HAK och nuvarande regionhalland.se har ingenting med HSA-tools att göra, den är utbytt sedan länge. Vi ska fortsätta använda Biztalk.

**Comment by JohannaOlin** [comment]
Vi pausar denna till dess att vi vet om vi kan använda Biztalk-filen.

**Comment by JOHNREGIONHALLAND** [comment]
Yes vi kan använda Biztalk som EPI-server gör idag
Enligt Malin så använder HAK samma fil som hämtas från INERA.
Bara man följer en GDPR process

1. Jag bygger på konverter & WP-plugin för att nya webbplatserna ska kunna använda sig av HSA
   Fixar klart konverter i veckan, mailnotifikation för personen som ska godkänna
2. Synka med Biztalk så att data uppdateras 1/dygn.

Bifogar PDF teknisk flöde och noteringar från mötet med GDPR Anna-Sofie
[https://app.zenhub.com/files/158801558/79d36094-c09c-4888-8c86-a40188e40c3a/download](https://app.zenhub.com/files/158801558/79d36094-c09c-4888-8c86-a40188e40c3a/download)

**Comment by JohannaOlin** [comment]
Kontaktpersonerna kan vi pausa lite. Intressenterna vill avvakta med detta tills vi hinner bygga in ett godkännande. En tanke jag fick kring godkännandet var om vi kunde ta detta via e-tjänsteportalen, där kan man ju logga in med bank id. Men som sagt, vi pausar lite, behöver inte vara på plats vid lanseringen.

**Comment by JohannaOlin** [comment]
Uppdatering kring detta. Jag pratade med Linda Malmros idag och vi beslutade att inte göra några förändringar alls, dvs skyddade personer kommer fortfarande att skickas med. Det är inga problem att skicka filen till ett nytt ställe. Linda skulle undersöka om det går att skicka den till två ställen, vilket skulle göra att vi kan testa funktionen, men att den samtidigt funkar på nuvarande webbplats.

Denna fil kommer dock endast att fungera under april så vi behöver fundera på en långsiktig lösning. Jag ska kolla med redaktionen om vi kan låta bli att ta med e-tjänsterna från 1177 efter april vilket skulle göra kopplingen mycket enklare.
