### ISSUE TITLE
Workflow på terapirekommendationerna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#199]
# Beskrivning
Oasis workflow för terapirekommendationerna har gått ut. Vi behöver undersöka hur vi kan uppgradera och vilken kostnad det skulle innebära.

**Comment by viktor-sarge** [comment]
Förlåt om jag kapar, men hade fliken uppe från sprintdemon (https://www.oasisworkflow.com/pricing-purchase). Licenserna verkar som sagt inte så dyra. 

Vad jag kan se så är enda skillnaden mellan olika prisnivåer hur många webbplatser man kan aktivera den på. Funktionaliteten är densamma oavsett. För upp till två webbplatser så räcker Pro-licensen som kostar $79/år för support och uppdateringar. 

Ekonomin bör alltså inte sätta stopp. Däremot om de inte tycker att det fungerar tillräckligt bra så kan ju funktionaliteten vara ett hinder. Min uppfattning är dock att det vore ett stort avbräck att gå tillbaka till normal Wordpress-funktionalitet.

**Comment by viktor-sarge** [comment]
Frågan är alltså om vi är nöjda med att betala för ett nytt år eller om det finns behov av att leta efter en helt annan lösning. Kortet är dock avgränsat till möjligheten att uppgradera och kostnaden för det så jag levererar det.
