### ISSUE TITLE
Mediabiblioteket adress till dokument

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#201]
# Beskrivning
Dokument och bilder som sparas i wordpress får url som innehåller år och månad vilket gör det omöjligt att enkelt byta ut ett dokument eller en bild.

Kolla om det går att ändra detta så att url:en inte innehåller år och månad.

**Comment by viktor-sarge** [comment]
Det går att notera URL:en, radera dokumentet och ladda upp ett nytt dokument som man manuellt ger den gamla URL:en. Men det finns plugins som gör det möjligt att ladda upp ett dokument som ersätter den gamla utan manuell hantering av URL: Tex https://wordpress.org/plugins/enable-media-replace/

**Comment by viktor-sarge** [comment]
Vill helst inte labba med nya plugins på stage så testar den i första hand på min lokala maskin. Men uppdatering av operativsystemet häromdagen drog med sig att jag måste uppdatera VirtualBox o Vagrant än så länge. Hoppas det räcker.

**Comment by viktor-sarge** [comment]
Testat pluginet "Enable media replace" på lokal installation. Den gör det möjligt att ersätta en fil med en annan och behålla samma samma URL. (Den kan också om man vill ersätta filen med en annan typ av fil och peka om gamla URL:er med det är ett annat behov än vad vi har här).

Jag undersöker vidare vad som händer med mediebiblioteket om man sätter en annan URL-struktur än den vi har idag eftersom det är det som är kortets egentliga fokus.

**Comment by viktor-sarge** [comment]
En anmärkning om https://wordpress.org/plugins/enable-media-replace/. Det är ett litet plugin med bara några få filer källkod, har funnits länge och är uppdaterat till moderna versioner av Wordpress. Vill vi ta in det bör det inte vara svårt att granska.

**Comment by viktor-sarge** [comment]
Jag har kollat vidare och URL-strukturen i mediabiblioteket handlar om hur Wordpress organiserar lagringen i filsystemet på servern. Det går att använda plugins för att ändra hur man t.ex. namnger, men det betyder isf att för att ladda upp en ny fil måste man först kopiera filens URL, radera, ladda upp en ny, se till att den nya URL:en har exakt rätt namn och URL som den tidigare. Risken för fel är stor. Chansen att få det rätt är betydligt större när man använder "Enable media replace" eftersom den abstraherar bort allt som kan bli fel. Min rekommendation är att vi snarast använder denna för att möta behovet.

Levererar kortet till QA med det förslaget till lösning.
