### ISSUE TITLE
Ladda upp txt-filer i wordpress

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#202]
# Beskrivning
Det går inte att ladda upp .txt på vårdgivarwebben. Detta ska gå att lösa med ett plugin

**Comment by JohannaOlin** [comment]
@regionhallandviktor Kolla så att detta plugin är ok att ta in

**Comment by RolandHyden** [comment]
@regionhallandviktor 
Här är ett plugin där man kan lägga till fler fil-typer:

https://wordpress.org/plugins/wp-extra-file-types/

Dock behöver vi en process för att kunna sätta OK-stämpel på tredje-parts-plugins.

**Comment by JOHNREGIONHALLAND** [comment]
Jag har testat plugin hjälper inte.
Man kan ladda upp txt utan något plugin på stage-vg.regionhalland.se och stage-rh.regionhalland.se
och även nya versionen av Wp Version 5.0.3. Det är standard för WP att ladda upp .txt filer

Det är nog något spärr på som man måste scanna igenom typen: text/plain 
WordPress’s MIME-type settings
https://stage-vardgivare.regionhalland.se 
och 
https://vardgivare.regionhalland.se

Om det är prio??

**Comment by viktor-sarge** [comment]
Tack @RolandHyden  och @JOHNREGIONHALLAND. Ser att det stämmer att default är på. Finns en funktion som listar tillåtna filtyper och där anges att bl.a. txt är på som default. Frågan är då hur det kommer sig att den inte är tillåten.

https://codex.wordpress.org/Function_Reference/get_allowed_mime_types

**Comment by viktor-sarge** [comment]
@JohannaOlin Visade sig att filtypen inte var tillåten i admin (trots att den borde ha varit det). Jag gick in på stage i Nätverksadmin/Inställningar/Uppladdningsinställningar och lade till txt som tillåten filtyp och sparade. Då fungerade det fint att lägga till en txt-fil i mediebanken. Vill du att jag gör detsamma på skarpa?

**Comment by viktor-sarge** [comment]
Frågade Johanna muntligt och fick ok att ändra på produktion. Det är gjort och verifierat att det funkar.

**Comment by JOHNREGIONHALLAND** [comment]
Aha.. det var det jag  tyckte att jag hade sett det fältet..

______________________________________
John Stenlund RGS IT APP (webbutvecklare : -)
john.stenlund@regionhalland.se
072 084 28 77
Fiskaregatan 12.

________________________________
