### ISSUE TITLE
Sortering av styrda dokument i bokstavsordning

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#204]
# Beskrivning
Redaktörerna blandar korta och långa talstreck i titlarna på styrda dokument. Dessa verkar hanteras olika så när dokumenten visas i bokstavsordning kommer först alla med korta streck och sedan alla med långa.

Exempel på sida
https://vardgivare.regionhalland.se/behandlingsstod/lakemedel/rutiner-blanketter-och-manualer-inom-lakemedelsomradet/rutiner/lakemedelshanteringsrutiner-region-halland-hallands-sjukhus-och-psykiatrin/

# Acceptanskriterier
- [ ] Specialtecken i titlar ska hanteras som blanksteg när det gäller listning i bokstavsordning

**Comment by JOHNREGIONHALLAND** [comment]
Ny uppdatering pågår för att ta bort dubbel strecken och den till ett streck

**Comment by JOHNREGIONHALLAND** [comment]
Har nu uppdaterat om replaca långa streck till vanlig streck
```
$s = str_replace('–','-',$s);
```

**Comment by JOHNREGIONHALLAND** [comment]
Det verka sortera ok???
