### ISSUE TITLE
Prototyp för träfflistekort - kalender

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#210]
# Beskrivning
Prototypen visar det som visas när man klickar på ett datum i komponenten kalender. Dvs den visar kalenderhändelser.

# Acceptanskriterier
- [x] Prototypen ska visa hur komponenten ser ut på desktop, tablet och mobil
- [x] Prototypen ska visa kalenderhändelsens datum
- [x] Prototypen ska visa kalenderhändelsens rubrik
- [x] Prototypen ska visa kalenderhändelsens start- och sluttid
- [x] Prototypen ska visa vad kalenderhändelsen är taggad med
- [x] Prototypen ska visa information om det finns platser kvar eller om evenemanget är fullbokat
- [x] Prototypen ska visa hur man kommer vidare för att se händelsen i sin fullpost
- [x] Prototypen ska visa hur man kan komma vidare och se fler händelser

**Comment by viktor-sarge** [comment]
Ser ut som att första fyra acceptanskriterierna inte är något problem, men att de fyra sista inte är med. Stämde av med Johanna och vi behöver nog ändå ha med t.ex. "platser kvar" och liknande i skissen så att vi tar höjd för det. Lägger till "failed QA" och sprint backlog så får vi stämma av.

**Comment by viktor-sarge** [comment]
Jag har för övrigt inte så mycket synpunkter på det visuella, men däremot vill vi nog definitivt att den här skall bete sig som en "aria"-bestyckad widget enligt WAI-ARIA Authoring practices så att man kan navigera i den med piltangenter osv. Det kommer bli en del stök med javascript i den här för att sätta active state osv när man jobbar i den som slutanvändare.

**Comment by fridabergentoft** [comment]
I mina skisser finns information om platser men med tanke på att ni inte såg den så kanske den är något dold. Jag har dock valt att istället för platser kvar skriva platser finns samt en grön checkbox. 
Vad evenemanget är taggat med visas i blå labels underst.

**Comment by viktor-sarge** [comment]
@fridabergentoft Då kanske jag helt sonika tittar på fel ställe (Komponentbibliotek 2.0 /organism / calendar"?

**Comment by fridabergentoft** [comment]
Jag förstår nu när jag läser vad jag har döpt komponenten till att det var svårt att hitta rätt! Den finns under Molecules/Event/Card

**Comment by viktor-sarge** [comment]
Gött! Då har jag inga invändningar utan är "Passed QA" för min del.  Hur man "Kommer vidare och ser fler händelser" är inte alldeles tydligt, men jag gissar att det ger sig av kontexten.

**Comment by viktor-sarge** [comment]
(Då gäller anmärkningen om att koda som en aria widget heller inte denna story utan den rena kalendern)

**Comment by JohannaOlin** [comment]
Ok för mig med
