### ISSUE TITLE
Prototyp - Komponent för tillbaka navigering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#211]
# Beskrivning
Vi behöver göra det lättare för besökarna att nå en sida högre upp i sidhierarkin

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten fungerar på desktop, tablet och mobil
- [ ] Prototypen ska visa hur besökaren kan komma tillbaka till en sida högre upp i hierarkin

**Comment by JohannaOlin** [comment]
Ok för mig

**Comment by viktor-sarge** [comment]
Ok för mig. "Passed QA". Flyttar till ready for release.
