### ISSUE TITLE
Komponent för träfflistekort - kalender

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#212]
# Beskrivning
Visar en eller flera kalenderhändelser

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1204%3A0&viewport=-443%2C266%2C0.17866&scaling=min-zoom

**Comment by brightjennie** [comment]
rh event card calendar

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd!
