### ISSUE TITLE
Styrda dokument i excel ska gå att öppna i excel

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#213]
# Beskrivning
Nu går det att öppna de styrda excel dokumenten i google docs. Besökarna behöver kunna gå vidare och öppna dessa i klientprogrammet precis som de kan med worddokument

Exempel på styrda dokument i excel
http://styrdadokument.regionhalland.se/doc/9E976C87-EE67-4DA4-ADF8-06E8139CAC38
http://styrdadokument.regionhalland.se/doc/DF660717-E5AB-4031-9AA9-80AAD42C9F5A

# Acceptanskriterier
- [ ] Som besökare kan jag gå vidare och öppna ett styrt exceldokument i klientprogrammet från google docs

**Comment by JOHNREGIONHALLAND** [comment]
Fixad

**Comment by JOHNREGIONHALLAND** [comment]
Fixad! Laddaner visas på toppen
http://styrdadokument.regionhalland.se/doc/9E976C87-EE67-4DA4-ADF8-06E8139CAC38
