### ISSUE TITLE
Lägg in alla webbplatser i Kunskapsbanken

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#214]
# Beskrivning
För att vi ska ha koll på vilka webbplatser och hur man loggar in på den så behöver vi komplettera listan som ligger i Kunskapsbanken. https://rh.sharepoint.com/teams/Objektkommunikation/_layouts/OneNote.aspx?id=%2Fteams%2FObjektkommunikation%2FDelade%20dokument%2FKunskapsbank&wd=target%28Utvecklingsteamet%2FTj%C3%A4nster%20o%20inloggningar.one%7CA97B3082-0299-43A9-81E1-CB535BECBD4B%2FInloggningar%20som%20admin%5C%2Fredakt%C3%B6r%20f%C3%B6r%20v%C3%A5ra%20webbplatser%7CA8ED1744-4FE2-47C0-BFC8-B701A281B45B%2F%29
onenote:https://rh.sharepoint.com/teams/Objektkommunikation/Delade%20dokument/Kunskapsbank/Utvecklingsteamet/Tjänster%20o%20inloggningar.one#Inloggningar%20som%20admin/redaktör%20för%20våra%20webbplatser&section-id={A97B3082-0299-43A9-81E1-CB535BECBD4B}&page-id={A8ED1744-4FE2-47C0-BFC8-B701A281B45B}&end

# Acceptanskriterier
Lägg in de webbplatser vi byggt inom objektet med följande information om samtliga
- [ ] Adress
- [ ] Information om webbplatsen, dvs syftet, om den är intern etc
- [ ] Inloggning för redaktör
- [ ] Inloggning för administratör i de fall det finns

**Comment by viktor-sarge** [comment]
Det som John inte hade lokalt utan som var labb-installationer på server tror jag är släckt när David har rensat på servrarna. Försöker få en överblick över det som faktiskt skall ligga kvar och lista upp det under nästa vecka. Det är egentligen ett fåtal installationer så bör inte vara svårt. Men däremot kan vi behöva samköra vad vi skall ha och vad som faktiskt ligger på servrarna och se om det är några mer övergivna installationer som vi skall forska i.
