### ISSUE TITLE
Sökning på stage-vardgivare.regionhalland.se går mot fel index

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#215]
# Beskrivning
När jag gör en sökning på stage-vardgivare.regionhalland.se så leder alla träffarna till produktionsmiljön. Detta gör det svårt att testa sökfunktionen.

# Acceptanskriterier
- [ ] Vid en sökning på stage-vardgivare.regionhalland.se så ska jag få träffar från den webbplatsen.

**Comment by JOHNREGIONHALLAND** [comment]
AHA... detta beror på att man använder samma API_URL i env filen i stage och prod.
Jag kollar och ordnar det..

**Comment by JOHNREGIONHALLAND** [comment]
Hej Johan!

På test sidan stage-vardgivare.regionhalland.se
https://stage-vardgivare.regionhalland.se/?s=barn

Och på produktion
https://vardgivare.regionhalland.se/?s=barn

Hämtning av sökning görs från denna url
http://193.183.15.219:8080/rest/apps/regionhalland/searchers/halland?q=barn

Går det att specificera push plugin/data vart det kommer ifrån?
Och för hämtning för stage och prod kunde specificeras med en annan sträng url?
Exempel 
test:  http://193.183.15.219:8080/rest/apps/regionhalland/searchers/test-halland?q=barn
Retur url: "url" : "http://stage-vardgivare.regionhalland.se/?page_id=4812"

prod:  http://193.183.15.219:8080/rest/apps/regionhalland/searchers/halland?q=barn
Retur url: "url" : "http://vardgivare.regionhalland.se/?page_id=4812"

Jag gissar att det går med nya servrarna som håller på att sättas upp?
Prod sajter hämtar  LTFINDINDEX1
Testsajter hämtar  LTFINDINDEXTEST1

Detsamma med push data/mysql så anslutar ni till test mysql och prod mysql för att skillja test och prod.

**Comment by JOHNREGIONHALLAND** [comment]
Hej John,

I nuläget har vi ingen test-URL att anropa för sökningar. Detta kommer vi sätta upp senare när vi får tillgång till testservern. Om du behöver en test-URL redan nu kan jag givetvis sätta upp en sådan på nuvarande server.

Jag ska undersöka möjligheterna att extrahera den URL som visas utåt (https://vardgivare.regionhalland.se/behandlingsstod/smittskydd/vaccinationer/barnvaccination/ovriga-vacciner-barn/ för exemplet http://vardgivare.regionhalland.se/?page_id=4812), och återkommer.

Mvh,
Johan

**Comment by JohannaOlin** [comment]
Avvaktar F5

**Comment by JohannaOlin** [comment]
Vi behöver verifiera att detta fungerar när söket flyttats.
