### ISSUE TITLE
FINDWISE F5, sökserver, dabatabas koppling

### ISSUE THREAD

**Issue by JOHNREGIONHALLAND** [RegionHalland/general#216]
Lägga SD ärende så att Findwise kan nån sina sökservrar via Citrix
för kommande F5 uppsättning.

Kontaktperson Johan Björk <johan.bjork@findwise.com> 
----------------------------
Detta är hur vi loggar in på lttempfindindex1 och lttempfindsearch1 just nu:
1. Via regionhalland.se/distans, logga in på intranätservern 10.11.1.28 med hjälp av inloggningsuppgifter + MobilePass-kod.
2. På denna server, SSH:a in till lttempfindindex1 eller lttempfindsearch1 och utveckla på servrarna därifrån.
----------------------------

**Comment by JOHNREGIONHALLAND** [comment]
JOHAN
Vi har stöd för att indexera från sitemaps, vilket skulle kunna vara en lösning då Wordpress-pluginet inte plockar upp allt på sidorna.
 
JOHN
Test pågår på
http://ltwebutv5.lthalland.se/phpmyadmin/
http://stage-vg.regionhalland.se
http://stage-rh.regionhalland.se/

**Comment by JohannaOlin** [comment]
Vi väntar på F5 innan vi kan gå vidare med denna.

**Comment by JOHNREGIONHALLAND** [comment]
Öppningen  3306  är p.g
LTTEMPFINDINDEX1 à 3306 à ltwebutv5
LTTEMPFINDSEARCH1 à 3306 à ltwebutv5  

http://servicedesk.lthalland.se/WorkOrder.do?woMode=viewWO&woID=581470
