### ISSUE TITLE
FINDWISE ansluta till Mysql

### ISSUE THREAD

**Issue by JOHNREGIONHALLAND** [RegionHalland/general#217]
Utreda vad som är bäst för Findwise söklösning att koppla direkt mot webbplatsens databas Mysql och istället för att använda plugin.

Findwise rekommenderar att bästa lösningen är att synka direkt  med webbplatsens databas Mysql

Möte med Stellan tors 13.00 24 Jan 2019

**Comment by JOHNREGIONHALLAND** [comment]
Öppnar David Inlagd på SD
LTTEMPFINDSEARCH1 (193.183.15.219)  port 3306  ltwebutv5

**Comment by JOHNREGIONHALLAND** [comment]
test sitemap alternativ
kika över vilka sitemap i xml format kan användas för findwise sökning
https://wordpress.org/plugins/search/sitemap+xml/

**Comment by JohannaOlin** [comment]
Avvaktar F5
