### ISSUE TITLE
Gå igenom behörigheterna i Github

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#219]
# Beskrivning
Vi behöver gå igenom behörigheterna som ligger i Github idag och rensa bort de som inte behöver finnas där.

**Comment by JohannaOlin** [comment]
https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/

Innebär detta att vi egentligen skulle kunna låta de utomstående konsulterna ligga som outside collaborators?

**Comment by viktor-sarge** [comment]
Ja precis - de bör inte läggas till i organisationen utan bara få access till detta repo. Förklaringen till varför utvecklaren från Mediaflow kostade oss en "plats" verkar vara att det är privat repos. 

> Adding an outside collaborator to a private repository will use one of your organization's paid seats. 

Eftersom styleguide-repot är publikt så betyder det förhoppningsvis att vi inte behöver betala extra för de två konsulterna.

**Comment by viktor-sarge** [comment]
Skrev på Teams igår för att fråga om någon ändrat behörigheterna för konsulterna. Visade sig att de hade behövt byta från "outside collaborator" till vanliga team-medlemmar för att kunna se Zenhub-tavlan. Jag tänkte att jag manuellt kunde ha tagit bort access till känsliga repos, men det visade sig vara omöjlig eftersom vi har default "write"-access på alla medlemmar i teamet. Om vi inte har det så måste vi manuellt ställa accessen till 80+ repos för varje medlem vilket snabbt blir knöligt. Alternativt se om vi kan gruppera folk i team och styra behörigheten den vägen. Det kräver dock att vi kartlägger vilka repos alla skall ha behörighet till och manuellt assignar rätt repos till nya teams så att det speglar hur de faktiskt skall användas. Alternativet är att vi antingen bryter isär oss till olika organisationer eller att vi avvaktar och gör en ny bedömning när vi vet hur Azure devops påverkar.

**Comment by JohannaOlin** [comment]
Jag tycker att vi avvaktar tills vi infört Azure devops. Stänger detta så får vi ta ett nytt tag om rensningen sen.
