### ISSUE TITLE
Kundnöjdhetsmätning på vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#221]
# Beskrivning
Teamet som har ansvar för Vårdgivarwebben vill göra en mätning av kundnöjdheten på webbplatsen för att ha en baseline att utgå från.

De föreslår en NPS-mätning, t ex med https://www.promoter.io/. Kolla annars med Peter Larsson vilket verktyg han brukar använda

Vi behöver undersöka:
- [x] Vad det krävs för (tid, uppsättning) att lägga in det på vårdgivarwebben
- [x] Om det finns någon kostnad för att lägga in det
- [x] Om vi behöver göra något speciellt med tanke på GDPR

**Comment by JohannaOlin** [comment]
@regionhallandviktor Jag skulle vara tacksam om jag kunde få en indikation på dels kostnad och dels om det är ok enligt Gdpr till måndag eftermiddag när jag träffar styrgruppen för Vårdgivarwebben.

**Comment by viktor-sarge** [comment]
Jag har kikat på deras priser och det ser ut som att lägsta nivån (Start) á $79/månad (om man debiterar för ett år) eller $99 (om man betalar månad för månad) räcker. 

https://www.promoter.io/pricing/

Släcker kostnads-checkboxen.

**Comment by viktor-sarge** [comment]
Jag har satt upp ett gratis test av promoter.io. Vad jag kan förstå så är det ett system för att skicka ut epost där mottagaren får ett formulär att fylla i. Det kanske finns adresslistor att använda oss av för ett utskick, men jag hade spontant gissat att vi hellre ville fånga upp användarna direkt på webbplatsen och visa ett formulär den vägen.

**Comment by viktor-sarge** [comment]
(Med reservation för att jag missförstår någonting, men jag hittar ingenting i dokumentationen eller marknadsföringsmaterialet om mer än epost-formulär. När jag kollar dokumentationen för API-koppling så handlar det om att koppla systemet mot t.ex. Slack för att få notiser när man får in epost. Men inte något om alternativa sätt än epost vad jag kan se)

**Comment by viktor-sarge** [comment]
Eftersom man sparar epostadresser och liknande så gissar jag att de vanliga GDPR-reglerna behöver följas på samma sätt som när man skickar ut nyhetsbrev (vilket är den närmaste funktionalitet jag kan komma på)

**Comment by viktor-sarge** [comment]
(Klickar i GDPR-boxen utifrån att jag kan se att vi kommer lagra samma saker som när man gör nyhetsbrev. Epost och en del metadata om deras interaktion med tjänsteleverantören. All data ligger hos leverantören. Men när det gäller GDPR som sådant så vågar jag inte uttala mig utan tänker det är bäst att det dubbelkollas med de som verkligen kan det. Jag ser dock inte att den här erbjuder större utmaningar än andra saker, men vet inte om det går att upprätta avtal med dem)
