### ISSUE TITLE
Nyheter på regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#226]
# Beskrivning
Vi behöver lägga in nyhetsfunktionalitet på nya regionhalland.se. 

# Acceptanskriterier
- [ ] Som redaktör kan jag skapa nyheter på regionhalland.se
- [ ] Som redaktör kan jag kategorisera en nyhet

**Comment by RolandHyden** [comment]
@JohannaOlin 

Hej Johanna.
Nu finns samma nyhetsfunktion på stage-rh som för vårdgivarwebben.

Pluginen är ...

    https://github.com/RegionHalland/region-halland-news-archive-taxonomi-category

... och just nu används version 1.0.0.

Funktionen är exakt likadan som för vårdgivare.
