### ISSUE TITLE
Kulturkatalog

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#227]
# Beskrivning
Kulturen behöver en funktion för att visa upp kulturprogrammet för barn och unga på regionhalland.se. Jag tänker att vi kan använda samma funktion som för vuxhalland.

# Kontaktperson
Linda Tillander, linda.tillander@regionhalland.se

# Acceptanskriterier
- [ ] Det ska gå att tagga ett program med typ av program (Dans, Film, Konst, Kulturarv, Musik, Slöjd och Teater)
- [ ] Det ska finnas ett fritextfält för att fylla i Målgrupp
- [ ] Det ska finnas ett fritextfält för att fylla i Publik
- [ ] Det ska finnas ett fritextfält för att fylla i Speltid
- [ ] Det ska finnas ett fritextfält för att fylla i Lokal
- [ ] Det ska finnas ett fritextfält för att fylla i Turnéperiod
- [ ] Det ska finnas ett fritextfält för att fylla i Pris i Halland
- [ ] Det ska finnas ett textfält där redaktören kan lägga in text, bilder och länkar
- [ ] Det ska gå att lägga in moduler med länkar

**Comment by RolandHyden** [comment]
@JohannaOlin 

Hej Johanna.
Nu finns ett första embryo på kulturkatalogen uppe på stage-rh.

Pluginen är ...

    https://github.com/RegionHalland/region-halland-acf-page-kulturkatalog

... och just nu används version 1.0.0.

Jag visste inte riktigt hur jag skulle styla en enskild kultursida, så jag tog samma design som för nyheter. Ett exempel är ...

    http://stage-rh.regionhalland.se/kulturkatalog/lorem-ipsum/

Designen är inte korrekt, men det ändrar vi enkelt. Detta kort är kanske klart i och med detta. Vi kan ju stämma av på demon.
