### ISSUE TITLE
Kalenderhändelse - Evenemang för Kulturen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#228]
# Beskrivning
Vi kommer att sträva efter att ha en gemensam kalender i regionen. Det är inte säkert att vi kommer att visa upp den totala kalendern någonstans, men möjligheten ska finnas. I första steget är det Kulturevenemangen vi ska bygga det för, men kalendern kommer att användas även för t ex Incidentrapporterna.

# Kontaktperson för Kulturevenemang
Linda Tillander, linda.tillander@regionhalland.se

# Acceptanskriterier
- [ ] Som redaktör kan jag tagga händelsen med Typ (I dagsläget finns endast valet Evenemang)
- [ ] Som redaktör kan jag tagga händelsen med Kategori (I dagsläget finns endast valet Kultur)
- [ ] Som redaktör kan jag tagga händelsen med Underkategori (Dans, Film, Musik etc)
- [ ] Som redaktör kan jag markera om evenemanget är fullbokat
- [ ] Som redaktör kan jag fylla i en starttid för evenemanget
- [ ] Som redaktör kan jag fylla i en sluttid för evenemanget
- [ ] Som redaktör kan jag fylla i en plats för evenemanget
- [ ] Som redaktör kan jag fylla i en sista anmälningsdag för evenemanget
- [ ] Som redaktör kan jag fylla i en målgrupp för evenemanget 
- [ ] Som redaktör kan jag lägga in text, bilder och länkar

**Comment by RolandHyden** [comment]
Hej Johanna.
Nu finns ett första embryo på kulturevenemang uppe på stage-rh.

Pluginen är ...

	https://github.com/RegionHalland/region-halland-acf-page-kulturevenemang

... och just nu används version 1.0.0.

Jag visste inte riktigt hur jag skulle styla en enskild evenemangsida, så (precis som för kulturkatalogen) tog jag samma design som för nyheter. Ett exempel är ...

	http://stage-rh.regionhalland.se/kulturkatalog/lorem-ipsum/

Designen är inte korrekt, men det ändrar vi enkelt.
