### ISSUE TITLE
Lägg in plugin för att byta ut dokument/bild

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#231]
# Beskrivning
Kodgranska och om ok lägg in plugin https://wordpress.org/plugins/enable-media-replace/ på vårdgivarwebben och regionhalland.se

**Comment by JohannaOlin** [comment]
@regionhallandviktor Det är inte så enkelt som att bara kryssa ur den nedersta rutan då?
![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/84e168ed-839c-4e08-a5bc-080f837d80c6)

**Comment by JohannaOlin** [comment]
eller det är för att vi har lagt in pluginet redan? Den fanns inte på stage-vardgivare utan endast på stage-rh

**Comment by viktor-sarge** [comment]
Jag tror faktiskt att det handlar om olika WP-versioner. Stage-rh är uppdaterad till WP 5.0.3 och min lokala sajt helt utan plugins har också inställningen (och ligger också på WP 5.0.3). Men även om man ändrar inställningen så behöver man ju manuellt kontrollera att URL:en verkligen blir rätt, så jag tycker pluginet är en betydligt säkrare väg att byta ut dokument fortfarande.

**Comment by JohannaOlin** [comment]
Vi kör på pluginet

**Comment by viktor-sarge** [comment]
Tror att kodgranskning och inläggning i första hand skall utföras av @JOHNREGIONHALLAND och @RolandHyden så jag vill egentligen koppla loss mig. Men eftersom vi vill få färdigt kravlistan på nya plugins så ber jag att vi sätter ihop och kollar på den här + listan samtidigt.

**Comment by viktor-sarge** [comment]
Lade till er Roland och John för att vi skall komma ihåg att sätta oss med kravlistan på nya plugins. Behöver diskutera med hur vi skall prioritera olika saker, och i ännu högre grad hur vi faktiskt skall utvärdera vissa saker. Att det inte finns någon "phone home"-funktion som läcker data till tredje part är riktigt viktigt, men det känns ju också som något som man måste vara säker på hur man utvärderar eftersom utvecklarna knappast har namngett en funktion till sneakilyLeakUserData()

**Comment by viktor-sarge** [comment]
Vi får ta den här pucken själva @RolandHyden, jag av-assignade John. Jag tror att det av nödvändighet får bli en rätt pragmatisk lösning tills vidare och så får vi istället bygga vidare på den vartefter vi hittar vägar att granska djupare. Att skriva in saker som som vi inte kan uppfylla betyder bara att vi blundar och inte kommer jobba vidare.

**Comment by viktor-sarge** [comment]
(Slår mig också att den här storyn egentligen bara handlar om det enskilda pluginet och då kan vi lösa den än lättare. Den större diskussionen tar vi egentligen i en annan story, det var jag som blev lite entusiastisk)

**Comment by viktor-sarge** [comment]
Vad tror du om att vi tar en kik ihop på måndag @RolandHyden och sedan lägger in den via unpkg om vi inte hittar något som känns skumt? Det är bara några få filer och eftersom vi kanske har en del annat som skall fixas och uppdateras i composer kunde vi samla ihop det lite.

**Comment by RolandHyden** [comment]
Vi kollar på detta på måndag :)

**Comment by viktor-sarge** [comment]
Testar lokalt och håller på med en composer update.

**Comment by viktor-sarge** [comment]
Använder wpackagist för att dra in via composer.

**Comment by viktor-sarge** [comment]
@JohannaOlin  Nu kommer pluginet för att byta ut filer men behålla namnet in på stage-servern för regionhalland.se
