### ISSUE TITLE
Få igång webbserver PROD och TEST server F5

### ISSUE THREAD

**Issue by JOHNREGIONHALLAND** [RegionHalland/general#235]
Få klart webbserver.
Kontakta Oskar när F5 kan sättas upp.
LTWEBDMZTEST10 -> ska nås av alla 
LTINTRANETTEST1 -> Endast internt RH-LAN

John hjälper DAVID installera applikationer till servrarna.
# WEBB APP
- APACHE2
- PHP 7
- MYSQL
- PHPMYADMIN
- ODBC (inte nödvändig, kanske iframtiden )
- COMPOSER
- git
- princexml (terapirek använder detta)

**Comment by JOHNREGIONHALLAND** [comment]
Tjena!

Jag har nu bett Lasse att kontakta konsulten för att fråga status eller om han väntar på uppgifter från Regionen.

Mvh Oskar

**Comment by JOHNREGIONHALLAND** [comment]
David har börjat installerat på riktiga webbserver "LTWEBDMZTEST10 "
men kört fast lite. 
John stöttar David att komma igång.

DAVID
tisdag kan jag ramla neråt.. 
då har vi ändå möte 
så går vi igenom steg för steg och ändrar på det som är klart.. Vi kanske kan sätta oss i ett rum så vi kan jobba ostört :)

**Comment by JOHNREGIONHALLAND** [comment]
UPDATE
-------------
Hej på er!

Nu hoppas jag vara klar med era servrar. AD-inloggning. Kör hårt!

Servernamn
Söksserver
LTFINDINDEX1
LTFINDSEARCH1
LTFINDSEARCH2
LTFINDSEARCH3
LTFINDINDEXTEST1
LTFINDSEARCHTEST1
LTFINDSEARCHTEST2
LTFINDSEARCHTEST3
 
RH UBUNTU
LTINTRANET1
LTINTRANET2
LTINTRANETDB1
LTINTRANETDB2
 
LTWEBDMZ10
LTWEBDMZ11
LTWEBDMZDB10
LTWEBDMZDB11
 
LTWEBDMZTEST10
LTINTRANETTEST1

Trevlig helg!
Mvh Oskar
-------------------------------------------------

Nu återstår att installera applikationerna.
- APACHE2
- PHP 7
- MYSQL
- PHPMYADMIN
- ODBC kunna ansluta till Windows IIS SQL databaser - http://php.net/manual/en/function.odbc-connect.php
- COMPOSER
- git

Jag har gjort/påbörjat en installations guide hur man installera applikationer på UBUNTU,
guiden finns på DEVOPS till DAVID/RH

/ john

**Comment by JohannaOlin** [comment]
Externa sökmotorer ska inte nå sajterna
