### ISSUE TITLE
TinyMCE trasig

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#236]
Går inte att formatera text i TinyMCE.

**Comment by viktor-sarge** [comment]
Den här veckan blev det omöjligt att formatera text i editorn (TinyMCE) pga att den TinyMCE-plugin som aktiverar tabellfunktionaliteten var satt att uppdatera till "latest" hela tiden och gick till 5-serien medan Tiny låg kvar på 4.8.0. Vi styrde om så att pluginen också går mot 4.8.0. Kruxet är att det aktiverade en bugg som gör att det saknas en del js och css som kompileras i hallands-temat. Sätter upp den som en separat bugg.

**Comment by JOHNREGIONHALLAND** [comment]
TESTAT!
--------------
Gällande uppsättning av vardgivare på forge...
Sparade js filen lokalt i tema och anropa lokalt istället från att hämta från unpkg.
Funkar utmärkt att anropa lokalt. 
Detta är ett alternativ för att undvika anropa externa url.

```
FIL: themes/halland/app/Theme/Filters.php
RAD: 64
public function add_table_plugin( $plugins )
	{
		#$plugins['table'] = 'https://unpkg.com/tinymce@4.8.0/plugins/table/plugin.min.js';
		$plugins['table'] =  \App\asset_path('scripts/tinymce.table.4.8.0.plugin.js');
		return $plugins;
	}
```

**Comment by viktor-sarge** [comment]
Om jag minns rätt nu så sade jag och @JohannaOlin att vi kunde spara den här storyn för att komma ihåg att kika på lösningen med att pusha upp de lokalt kompilerade filerna till servern eftersom yarn krånglade på Azure. Det funkar, men frågan är om vi inte borde få koll på varför yarn lagt av. Föreslår att vi släcker den här ändå och skriver ett nytt kort för att göra det lite tydligare.
