### ISSUE TITLE
Saknade .js .css och .svg-filer när man uppdaterar stage. 

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#237]
När vi uppdaterade tinymce så triggade vi en bugg där det saknas fyra filer. Dessa brukar byggas av yarn (vilket vi inte aktiverade igår), men eftersom vi inte gjort ändringar i filer som skulle gjort det nödvändigt med nya versioner så tänkte jag att existerande filer fick ligga kvar. Det är möjligt att det är något i deploy-processen som krånglade ifall de byggs under deploy. (main.css och main.js kompileras i Hallands-temat).

**Comment by viktor-sarge** [comment]
Här är filerna som saknas. 
![image](https://user-images.githubusercontent.com/3371823/52409932-32324000-2ad7-11e9-93ea-769908864786.png)

js och css kommer ju direkt från hallands-temat. Om deploy raderar de gamla så kan det hända att vi behöver köra yarn för att generera nya och committa dessa, men jag kan inte minnas att jag behövt skicka nya filer för orelaterade ändringar tidigare. Känns som det är något annat som krånglar.

**Comment by JOHNREGIONHALLAND** [comment]
OK ska fixa till det.
kännedom i halland repo 
/dist är inlagd på .gitignore 

Enligt info ska detta skap dessa filer, men misstänker att det inte gör på server.
yarn
yarn run build

För att fixa till kanske man bör ta bort /dist från .gitignore
Återkommer

**Comment by JOHNREGIONHALLAND** [comment]
Har fixat på stage-vardgivare.regionhalland.se
Kika så att allt är OK + table formulär innan det pushas till PROD !

Ny ändring på composer.json bör göras om det ska pushas till master PROD med fungerande 4.8.0 tinymce.table.js och dist.

## composer.json
Ändra:  "regionhalland/halland": "dev-master#e314fd3",
Till:     "regionhalland/halland": "dev-master#bb40f0b",

repo: https://github.com/RegionHalland/vardgivare.regionhalland.se

##### 
Felet har uppstått sen 16 Jan på azure server
----------------------------
illuminate/console suggests installing dragonmantank/cron-expression (Required to use scheduling component (^2.0).)
Generating autoload files
yarn install v1.6.0
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
etc...

**Comment by JohannaOlin** [comment]
@JOHNREGIONHALLAND Kan du uppdatera vårdgivarwebben så att textfältet fungerar där igen.

**Comment by JOHNREGIONHALLAND** [comment]
Har ni kollat att stage.vardgivare är OK?
Så pushar jag till prod.

**Comment by JohannaOlin** [comment]
Ja, den ser ok ut nu

**Comment by JOHNREGIONHALLAND** [comment]
Har nu uppdaterat på prod https://vardgivare.regionhalland.se/
