### ISSUE TITLE
Txt-filer på vårdgivarwebben får konstiga tecken i webbläsaren

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#240]
# Beskrivning
Uppladdade txt-filer på vårdgivarwebben får konstiga tecken för å, ä och ö när de öppnas i webbläsaren. Det spelar ingen roll vilken webbläsare jag använder.
De ser däremot ok ut när jag laddar upp dem på stage-rh.regionhalland.se.

# Exempel
- [ ] http://stage-vardgivare.regionhalland.se/app/uploads/2019/02/Standardvillkorstexter-för-ärendetyper-Anteckning-1.txt
- [ ] http://vardgivare.regionhalland.se/app/uploads/2019/01/Standardvillkorstexter-för-ärendetyper-Anteckning-1.txt

**Comment by JOHNREGIONHALLAND** [comment]
Detta beror på hur man sparar .txt filen i Anteckningar.
P.g.a LINUX måste man ha rätt tecken kodning. 
I rutan när man sparar Anteckningar kan man välja kodning: ANSI eller UTF-8 (välj UTF-8)

1. Här funkar om man spara filen som UTF-8 och ladda upp då visas det rätt åäö på server
https://stage-vardgivare.regionhalland.se/app/uploads/2019/02/Standardvillkorstexter-f%C3%B6r-%C3%A4rendetyper-Anteckning-1-UTF-8.txt

2. Om man spara som ANSI och ladda upp blir fel tecken på åäö
- https://stage-vardgivare.regionhalland.se/app/uploads/2019/02/Standardvillkorstexter-f%C3%B6r-%C3%A4rendetyper-Anteckning-1.txt


Se beskrivning
![image.png](https://images.zenhubusercontent.com/5ba0b47d926ebd396bd72462/768040ab-9229-450e-9fc9-f490fd3bbc86)
