### ISSUE TITLE
Puffar - backend

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#241]
# Beskrivning
Som redaktör vill jag kunna puffa upp för olika saker på webbplatsen. 

# Acceptanskriterier
- [ ] Som redaktör ska jag ange en rubrik som ska visas på puffen
- [ ] Som redaktör ska jag ange en text för puffen
- [ ] Som redaktör kan jag välja en bild att visa på puffen (frivilligt)
- [ ] Som redaktör kan jag ange en adress/sida dit puffen ska leda
- [ ] Som redaktör kan jag på en sida på webbplatsen välja att visa puffen
- [ ] En puff ska gå att återanvända på mer än en sida
- [ ] Det ska finnas information om vilken sida en puff används på.

**Comment by viktor-sarge** [comment]
Tar mig friheten att flytta den här till pågående för jag vet att Roland har bra saker på gång :)

**Comment by viktor-sarge** [comment]
Jag har den på min maskin just nu. Backend funkar bra. Kommer ut på test-rh när vi får servern. 

Roland lägger upp på stage-rh så att Johanna kan visa redaktörerna imorgon. OBS! Informationen kommer inte att visas på de faktiska sidorna ännu eftersom det inte hämtas ut i blade-filerna ännu.

**Comment by viktor-sarge** [comment]
Behov av extra fält: 

- [ ] Länk dit puffen skall leda

@RolandHyden

**Comment by RolandHyden** [comment]
OK, nu finns även stöd för en länk vart en puff ska leda.
Detta är i pluginen ...
   
   https://github.com/RegionHalland/region-halland-acf-page-links-blurbs

... och nu har vi nått version 1.2.0 i och med länken

**Comment by JohannaOlin** [comment]
Funktionsmässigt är den ok. Det skiljer sig lite från Acceptanskriterierna, det är t ex det jag skriver in som länktext som visas som rubrik, men det kan vara ok. Rubriken visas inte och det är också ok, den fungerar mer som namn på själva puffsidan. Jag kan inte hitta någon information om på vilken sida puffen används, men det behöver vi inte ta med nu tycker jag. Jag skriver ett nytt kort på detta.

Vi bör däremot fundera på om vi ska sätta en fast höjd på puffarna eftersom de oftast visas bredvid varandra.

Jag sätter över den på dig @regionhallandviktor, du kan sätta den som Closed om du tycker att den är ok. Den ligger ju redan i miljön som fungerar som produktion.
