### ISSUE TITLE
Modul för dokument och länkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#243]
# Beskrivning
Vi behöver lägga in samma modul för dokument och länkar som finns på vårdgivarwebben.

# Acceptanskriterier
- [ ] Som redaktör kan jag lägga in dokument och länkar i en lista på regionhalland.se
- [ ] Modulen ska gå att lägga in på sidor, nyheter och kulturkatalog
- [ ] Listan ska gå att återanvända på fler sidor, nyheter och kulturkatalogssidor

**Comment by RolandHyden** [comment]
Hej Johanna.
Jag har på stage-rh lagt in både modularity & mod-linkgroup, dvs detsamma som finns på vårdgivarwebben.
Dock har jag inte aktiverat dessa plugins ännu. Tänkte att vi kanske kunde diskutera det innan. För börjar vi använda modularity & mod-linkgroup så kan vi inte backa sedan.

**Comment by JohannaOlin** [comment]
Roland kollar detta med Viktor
