### ISSUE TITLE
Nyhetslista på sidor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#246]
# Beskrivning
Vi vill visa upp en delmängd av nyheterna på utvalda sidor (section page) utifrån kategorier. Denna story gäller enbart backend. 

# Acceptanskriterier
- [ ] Som redaktör peka ut en kategori av nyheter som ska visas på aktuell sida

**Comment by viktor-sarge** [comment]
Snokar runt i alla möjliga stories för att få en helhetsbild av läget. Nyheter finns ju så jag gissar att den biten är färdig. Det som behövs är väl ett attribut för sidor som innehåller en "Visa nyheter: ja/nej"-toggle + en checkbox-lista där man kryssar i vilka kategorier man vill ha. I nuläget verkar man inte kunna styra i backend vad som visas (se tex. Utveckling och tillväxt som har nyheter men ingen möjlighet jag hittar att sätta om nyheter visas och isf vilka kategorier)

**Comment by viktor-sarge** [comment]
Roland har den här på gång.

**Comment by RolandHyden** [comment]
OK, detta är klart.

Först la jag till så att man kan använda taxonomi-kategorier på sidor via pluginen ...

   https://github.com/RegionHalland/region-halland-use-taxonomy-category-on-page

.. och det är version 1.0.0 av denna plugin.

Sedan uppdaterade jag nyhets-pluginen till version 1.2.1. Pluginen heter ...

   https://github.com/RegionHalland/region-halland-news-archive-taxonomi-category

Därmed kan man hämta ut nyheter på sidor genom kopplingen taxonomi-kategorier. De kategorier som en sida har ger helt enkelt de nyheter som har samma kategorier.

**Comment by JohannaOlin** [comment]
Funkar bra. Jag sätter över den på dig @regionhallandviktor. Flytta den till Ready for release om den är ok. Jag är lite osäker på om den ligger på stage-rh, tycker inte att den visar rätt nyheter där så vi kan inte stänga den än.
