### ISSUE TITLE
Viktigt meddelande

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#249]
# Beskrivning
Vi har behov att att visa ett Viktigt meddelande på webbplatserna. Detta meddelande är inte nödvändigtvis samma som visas på respektive webbplats så funktionen ska ligga på respektive webbplats. Detta kort gäller endast backend. 

I första steget så kommer vi att göra funktionen enkel, antingen så visas meddelandet överst på alla sidor eller så visas det inte på någon sida. Behovet finns dock av att på regionhalland.se så småningom kunna välja vilken/vilka sidor meddelandet ska visas på.

# Acceptanskriterier
- [x] Som redaktör kan jag skapa ett viktigt meddelande på regionhalland.se
- [x] Som redaktör kan jag skriva in en rubrik för det Viktiga meddelandet
- [x] Som redaktör kan jag skriva in text, och formatera den
- [x] Som redaktör kan jag ange en adress eller sida som länken ska leda till
- [x] Som redaktör kan jag välja om meddelandet ska visas eller inte

**Comment by RolandHyden** [comment]
Hej @JohannaOlin .
Jag har lagt ut en första version av "Viktigt meddelande" på stage-rh ...

	https://github.com/RegionHalland/region-halland-acf-options-page-site-message.git

... och jag använder just nu pluginen med version 1.0.1.

Man kommer åt att skriva "Viktigt meddelande" via vänstermenyn. 
Alla kan ändra detta viktiga meddelande, dvs inte bara admin.

Jag har lagt in det "oformaterat" högst upp på alla sidor (så att man kan se att det fungerar, inkl. länk). Detta syns bara om man har valt i admin att "Viktigt meddelande" ska visas.

**Comment by viktor-sarge** [comment]
@JohannaOlin Vill bara rapportera att jag har testat pluginet under implementationen av den nya desingen. Checkade i relevanta boxar i acceptanskriterierna. 

Obs - det går att formatera med t.ex. en `<strong>`-tagg men det är inte egentligen meningen och finns ingen vanlig editor. Jag tycker nog inte heller att man bör ha det om det inte är absolut nödvändigt.

**Comment by JohannaOlin** [comment]
@regionhallandviktor jag tycker att vi skippar formateringen just nu. Huvudsaken är att de kan lägga in ett meddelande med rubrik, text och länk. Det vi behöver göra är att skapa en behörighetsgrupp för detta, men det ligger på kort 260. Jag tycker att vi tar bort att lägga in det på Vårdgivarwebben också, det tar vi på ett eget kort senare.

Med andra ord så är detta kort ok nu.

**Comment by viktor-sarge** [comment]
Super!
