### ISSUE TITLE
Ändra ordning på huvudmenyn

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#250]
# Beskrivning
Redaktionen vill ändra ordningen på huvudmenyn på regionhalland.se, dvs stage-rh.regionhalland.se.

Ordningen ska vara så här:
- Vården i Halland
- Utveckling och Tillväxt
- Jobb & Karriär
- Kultur
- Våra skolor
- Demokrati & Politik
- Om Region Halland

**Comment by RolandHyden** [comment]
Hej Johanna.
Jag har uppdaterat pluginen ...

   https://github.com/RegionHalland/region-halland-tree-first-level

... så att version 1.1.0 används (stöd för valfri sortering)

Jag uppdaterade regionhalland.se så att denna version används där.

Testade även att sortera om enligt denna issue och det fungerade fint.

Har också justerat inställningar för "nested pages" så att även en redaktör kan ändra sorteringsordningen. Default är att endast "admin" kan sortera sidor. Nu är ju visserligen sidorna i rätt ordning, men be gärna någon redaktör att testa sortera om. Så vet ju ifall denna inställning fungerar.

**Comment by JohannaOlin** [comment]
Jag loggade in som vanlig redaktör och det fungerar att dra och släppa så vi sätter denna som löst.
