### ISSUE TITLE
Ingresstext

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#251]
# Beskrivning
Redaktörerna vill kunna lägga in ingresstext i ett separat fält på regionhalland.se. Texten i fältet ska bli formaterad så som vi bestämmer att den ska formateras. Vi kan lösa själva utseendet på ingresstexten senare.

# Acceptanskriterier
- [ ] Som redaktör har jag ett separat fält för ingresstext som ligger ovanför textfältet
- [ ] Gör texten fetstilt så länge

**Comment by RolandHyden** [comment]
Hej Johanna.
Jag har skapat en plugin med namn ...
	
	https://github.com/RegionHalland/region-halland-acf-page-ingress

... och använder just nu version 1.0.0 av denna plugin

Pluginen skapar ett textfält för ingress som placerar sig högst upp på en sida, dvs ovanför det vanliga "content". Jag har även lagt ut ingressen så att texten blir synligt på en sida som exempelvis ...

	http://stage-rh.regionhalland.se/folkhalsa-och-vard/curabitur-venenatis-semper/

.. och jag gjorde texten "italic" för att man ska kunna se att det är en annan typ av text. Det exakta utseendet justerar vi när komponenterna blir klara.

**Comment by JohannaOlin** [comment]
Ok för mig. @regionhallandviktor  Vill du kolla på denna innan vi stänger den?

**Comment by viktor-sarge** [comment]
Jag kikar. Tar med i implementationen av nya designen. Jag har pluginet på min egen maskin och det funkar bra så skall bara kika så att jag kan hämta ut och visa den i frontend.
