### ISSUE TITLE
Lägg till kategorier på nyheter

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#254]
# Beskrivning
Redaktörerna kan själv lägga till nyhetskategorier, men när de har lagt till en kategori så måste de uppdatera sidan för att den ska visas.

Går det att lösa så att Kategorin visas i listan när man har klickat på knappen "Lägg till ny kategori"

**Comment by RolandHyden** [comment]
Detta är så som wordpress fungerar, dvs de kategorier som finns är standard i wordpress.
Men jag har sett samma beteende, men vet inte om man kan göra något åt det.
