### ISSUE TITLE
Kontaktkort för enhet

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#255]
# Beskrivning
Vi behöver visa upp kontaktkort för enheter, typ som det som ligger till höger på denna sida http://www.regionhalland.se/vcgetinge. Uppgifterna hämtas från Hak och Inera via Biztalk idag och hänger lite samman med issue #196.

Detta kort gäller endast backend och hämtning av data. Visningen hanteras på ett eget kort eftersom vi först måste bygga komponent för detta. Jag lägger även ett separat kort för hämtningen av e-tjänsterna från 1177 eftersom dessa inte var nödvändiga att ha på plats vid en lansering, dock var de önskvärda.

# Acceptanskriterier
- [ ] Som redaktör kan jag välja en enhet genom att ange namn eller HSA-id. Detta ska in på mallen Standardmall
- [ ] Inte bara objekten utan även funktionerna i Hallandskatalogen ska vara valbara.
- [ ] Som redaktör kan jag välja om öppettiderna ska visas på kontaktkortet
- [ ] Övriga uppgifter som ska visas på kontaktkortet (om de är ifyllda i Hak) är Enhetens namn, Besöksadress, Telefonnummer och Telefontid
- [ ] Det ska finnas en länk "Mer information" som leder till den adress de skrivit i på fältet 1177.se (länk till kontaktkort" i Hak

**Comment by JohannaOlin** [comment]
I steg 1 så fixar vi så att redaktörerna kan fylla i enhetens namn. Kopplingen sker senare.

**Comment by viktor-sarge** [comment]
Möte 5mars

Behöver bli möjligt att välja en enhet för redaktörerna. 

Besked fr GDPR-ansvarig efter möte med Johanna o Roland: 

- Har man godkänt anställning har man också godkänt att stå med namn och epost som ansvarig.

- Bild kräver separat godkännande.

**Comment by viktor-sarge** [comment]
Vill minnas att jag gjorde kontaktkorten så de ligger tillgängliga i partials i repot. Vet att Roland jobbar med backendbitarna. Sätter oss båda på denna

**Comment by JohannaOlin** [comment]
@regionhallandviktor Jag har kollat på denna i stage nu du kan se på sidan http://stage-rh.regionhalland.se/halsa-och-vard/varden-i-halland/vard-nara-dig/vardcentralen-halland/vara-vardcentraler/vardcentralen-getinge/ och har följande kommentarer:

- [ ] Det är liten text på rubriken
- [ ] Detta kontaktkort hamnar för nära kontaktkortet för person
- [ ] Strecket ska vara ifyllt
- [ ] Det saknas en rubrik för Telefon
- [ ] Telefonnumret ska inte visas med +46
- [ ] Uppdateringar verkar inte komma med, te x är det fel telefontider till Vårdcentralen Fjärås

Jag har fler ändringar som vi behöver titta på så småningom, men när dessa är gjorda så kan det vara ok för redaktörerna att titta och kanske ok för en leverans.

**Comment by JohannaOlin** [comment]
@RolandHyden och @regionhallandviktor Närsjukvården är väldigt angelägna om att få in detta i produktion, men vi kan ju inte gärna släppa ut det innan vi har verifierat att uppdateringarna kommer med. Dessutom tycker jag att de utseendemässiga förändringarna (som jag nämner ovan) behöver fixas innan produktionssättning. Framför allt textstorleken och att det ska vara lite utrymme mellan de olika kontaktkorten.

**Comment by viktor-sarge** [comment]
Tack för uppdatering. Jag kikar på det så snart jag kan. Det verkar inte vara några komplicerade ändringar på frontend-bitarna

**Comment by viktor-sarge** [comment]
Fixat. Ligger i dev + master branch. Lägger till QA
