### ISSUE TITLE
Prototyp - Komponent för kontaktkort enheter

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#256]
# Beskrivning
Vi behöver visa ett kontaktkort för enheter på regionhalland.se. Ungefär som det som ligger till höger på sidan http://www.regionhalland.se/vcgetinge.

# Acceptanskriterier
- [ ] Prototypen ska visa enhetens namn
- [ ] Prototypen ska visa enhetens besöksadress
- [ ] Prototypen ska visa öppettiderna (kan vara olika från dag till dag)
- [ ] Prototypen ska visa telefonnummer
- [ ] Prototypen ska visa telefontider
- [ ] Prototypen ska visa en länk för Mer information
- [ ] Prototypen ska visa de e-tjänster som enheten erbjuder
- [ ] Prototypen ska visa en länk för att logga in i e-tjänsterna.
- [ ] Prototypen ska visa hur komponenten ser ut på desktop, tablet och mobil

**Comment by fridabergentoft** [comment]
Länk till kontaktkort: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1189%3A3983&viewport=-952%2C-230%2C0.469741&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Ok för mig. Tänker att verksamheten kanske har synpunkter, men i detta läge så får vi fixa det efter lanseringen.

**Comment by viktor-sarge** [comment]
Jag tycker det gör ett ganska rörigt intryck med tiderna. Först en grupp med mån, ons, fre 8-17 och sedan tisdag samma tid på en egen rad och så fredag. 

Länken "Mer information" ger för lite information. Information om vad? "Mer information om Vårdcentralen i Getinge" vore bättre. Och ännu mer specifikt om det går. Är det information om de tjänster som erbjuds, vilka prover man kan ta, hur man hittar dit? Eller "Mer information på Vårdcentralen i Getinges egen webbplats"

**Comment by viktor-sarge** [comment]
Rent kontrastmässigt så lirar det dock bra. Jag skickar tillbaka för en diskussion. Är det rena redaktörsfrågor så är det inte så mycket att göra men vi kanske kan trimma exemplet lite ändå :)
