### ISSUE TITLE
Komponent för kontaktkort enheter

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#257]
# Beskrivning
Ta fram en komponent utifrån prototypen

# Acceptanskriterier
- [ ] Komponenten ska byggas för desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1189%3A3983&viewport=-199%2C44%2C0.130403&scaling=min-zoom

**Comment by brightjennie** [comment]
rh unit info

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd med komponenten!
