### ISSUE TITLE
Skicka in synpunkter på webbplatsen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#259]
# Beskrivning
Innan vi har en riktigt feedbackfunktionalitet på plats så behöver vi erbjuda möjligheten att lämna feedback på webbplatsen via en e-post länk.

# Acceptanskriterier
- [x] På varje sida på webbplatsen ska det finnas en länk "Lämna synpunkt"
- [x] När besökaren klickar på länken öppnas mailklienten
- [x] Mailen skickas till infomaster@regionhalland.se
- [x] Som Ämne i mailet står det "Synpunkt på sajtens namn"
- [x] I mailbodyn finns en länk till sidan som besökaren stod på när hen klickade på länken.

**Comment by viktor-sarge** [comment]
Gäller det bara stage-rh? 

Det här kan vi nog lösa vid sittande bord på en liten stund så länge det inte är mer akuta saker vi behöver fixa.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Ja, just nu gäller den endast stage-rh, men vi behöver byta ut Hojar på vårdgivarwebben också snart, det får dock blir ett eget kort.

Det är ingen panik med detta, mer än att det måste vara klart innan lanseringen.

**Comment by viktor-sarge** [comment]
Justerat acceptanskriterierna muntligt ihop med Johanna o Roland. Inlagt på pages och nyheter.
