### ISSUE TITLE
Separera redaktörer för viktigt meddelande från övriga redaktörer

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#260]
# Beskrivning
Nu när regionen inför funktionen Kommunikatör i beredskap så behöver vi se till så att dessa kan lägga in viktiga meddelanden, men inte redigera vanliga sidor. Detta förutsätter att man kan ha mer än en roll på en webbplats eftersom vissa ska vara både nyhetsredaktörer och redaktörer för viktigt meddelande, medan andra endast ska vara nyhetsredaktörer. Vissa ska vara redaktörer för allt

# Acceptanskriterier
- [ ] Som administratör kan jag ge en användare rollen som redaktör för viktigt meddelande
- [ ] En vanlig redaktör ska även vara redaktör för viktigt meddelande

**Comment by viktor-sarge** [comment]
Hej @RolandHyden Har du möjlighet att uppdatera pluginen för viktigt meddelande med egna capabilities och uppdatera den på stage-rh så kan jag sätta upp en ny roll för det sedan? Annars får jag tjuvkika på vilken fil det var vi redigerade för nyhetspluginen :)

**Comment by viktor-sarge** [comment]
Stämt av med Roland. Viktigt meddelande är inte en custom post type så den kan inte styras på samma sätt som de övriga. Men vi har en hypotes om att vi kan dölja den visuellt för de som inte skall ha access och tittar mer på det under måndag.

**Comment by JohannaOlin** [comment]
Denna är inte jättehögt prioriterad så jag flyttar tillbaka den till backloggen.

**Comment by JohannaOlin** [comment]
Flyttad till DevOps, 2439, stängs här
