### ISSUE TITLE
Prototyp - Komponent för ingress

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#261]
# Beskrivning
Vi har lagt in ett separat fält för ingress på regionhalland.se. Vi behöver ta fram en komponent för hur denna ska se ut på webbplatsen.

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut på desktop, tablet och mobil

**Comment by fridabergentoft** [comment]
Länk till komponent
Desktop: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=31%3A5&viewport=378%2C351%2C0.405717&scaling=min-zoom

Tablet: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=108%3A365&viewport=378%2C351%2C0.405717&scaling=min-zoom

Mobile: https://www.figma.com/file/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=108%3A379

Komponenten finns längst ner på sidan precis innan länkarna.

**Comment by JohannaOlin** [comment]
Ok för mig
