### ISSUE TITLE
Prototyp på Terapirekommendationerna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#262]
# Beskrivning
Tanken är att vi ska lägga in Terapirekommendationerna som en del av vårdgivarwebben och vi behöver visa upp hur detta skulle kunna se ut. Ta fram en prototyp med följande Acceptanskriterier

# Acceptanskriterier
- [x] Prototypen ska ha Vårdgivarwebbens sidhuvud och sidfot, huvudnavigation, länkstig mm
- [x] Prototypen ska visa startsidan för Terapirekommendationerna på en Sektionssida
- [x] Prototypen visa sökrutan på alla sidor
- [x] Prototypen ska visa kapitel 25 (https://vardgivare.regionhalland.se/terapirek/terapirekommendationer/kapitel25/) inklusive undersidor
- [x] Prototypen ska visa Tillbaka-länken

**Comment by fridabergentoft** [comment]
https://www.figma.com/file/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=2950%3A1137
- Blev det rörigt med alla ingångar?
- Ska jag skärma av sökrutan med blå bakgrundsplatta?
