### ISSUE TITLE
Prototyp - Komponent för direktlänk till 1177

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#263]
# Beskrivning
På nuvarande regionhalland.se så indexerar vi även innehåll från 1177. Vi kommer inte att göra det på nya regionhalland.se, men då behöver vi meddela besökarna att de hittar vårdinformation på 1177.se

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut på desktop, tablet och mobil
- [ ] Prototypen ska visa hur besökarna når information från 1177 på söksidan

**Comment by fridabergentoft** [comment]
Kan det fungera att ha det såhär: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1408%3A5069&viewport=-4389%2C1618%2C0.675303&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Ok för mig

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1408%3A5069&viewport=-5397%2C1831%2C0.820502&scaling=min-zoom
