### ISSUE TITLE
Komponent för ingress

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#266]
# Beskrivning
Länk till komponent
Desktop: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=31%3A5&viewport=378%2C351%2C0.405717&scaling=min-zoom

Tablet: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=108%3A365&viewport=378%2C351%2C0.405717&scaling=min-zoom

Mobile: https://www.figma.com/file/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=108%3A379

Komponenten finns längst ner på sidan precis innan länkarna.

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop och tablet
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Precis som där alla textkomponenter finns kan ni hitta ingressen: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=31%3A5&viewport=311%2C263%2C0.277149&scaling=min-zoom

**Comment by brightjennie** [comment]
Denna ligger i RH-text komponenten som den gör i skissen.

**Comment by viktor-sarge** [comment]
Ser ut att stämma med skiss. Uppdaterat så den finns på live-sajten under rh-text. 

Jag av-assignar mig. Frida - lägg till "ready for release" om du är nöjd.
