### ISSUE TITLE
Komponent för direktlänk till 1177

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#267]
# Beskrivning

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska fungera i Internet explorer, Safari, Edge och Chrome

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1408%3A5069&viewport=-5397%2C1831%2C0.820502&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-external-link-1177

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd!
