### ISSUE TITLE
Skiss - Listning av kulturarrangemang

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#272]
# Beskrivning
Vi behöver ta fram en skiss för hur listningssidan för kulturarrangemangen ska se ut för att se hur komponenterna förhåller sig till varandra

# Acceptanskriterier
- [x] Skissen ska visa hur sidan ser ut på desktop, tablet och mobil
- [x] Skissen ska visa sidhuvudet
- [x] Skissen ska visa länkastig - flytta upp
- [x] Skissen ska visa tillbaka-länk (endast mobil ev tablet)
- [x] Skissen ska visa rubrik
- [x] Skissen ska visa ingress, textfält
- [x] Skissen ska visa filtreringsmöjligheter
- [ ] Skissen ska visa sökruta
- [x] Skissen ska visa eventcard
- [x] Skissen ska visa paginering
- [x] Skissen ska visa kontakt-länk
- [x] Skissen ska visa kontaktkort person
- [x] Skissen ska visa sidfot

**Comment by fridabergentoft** [comment]
- Jag funderar över om det verkligen behövs en sökruta. Ska jag lägga in det eller inte?
- Är det konstigt att jag använder så mycket blått? I Event-card återkommer det i skiss för arrangemanssidan

**Comment by JohannaOlin** [comment]
@fridabergentoft Jag tycker att du kan skippa sökrutan. Jag tycker också att det är ok med så mycket blått.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Sätter över denna på dig. Flytta den till Ready for release om du tycker att den är ok
