### ISSUE TITLE
Konfigurera vårdgivarwebben för separata nyhetsredaktörer

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#275]

**Comment by viktor-sarge** [comment]
Deadline från Johanna är slutet av mars när de går live med nyheter.

**Comment by JohannaOlin** [comment]
Vi pausar denna och tar med den när vi flyttar in vårdgivarwebben och lägger in de nya komponenterna. Jag har gett Kib:arna redaktörsbehörighet till Vårdgivarwebben så länge. Flyttar tillbaka kortet till backloggen.

**Comment by JohannaOlin** [comment]
Flyttad till DevOps
