### ISSUE TITLE
Prototyp - Komponent för Cookie-notis

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#278]
# Beskrivning
Vi behöver ta fram en prototyp för hur komponenten Cookie-notis ska se ut.

# Acceptanskriterier
- [ ] Prototypen ska visa hur komponenten ser ut på desktop, tablet och mobil
- [ ] Prototypen ska innehålla text och knapp

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1426%3A0&viewport=-361%2C156%2C0.415948&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Ok för mig
