### ISSUE TITLE
Komponent för Cookie-notis

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#279]
# Beskrivning
Komponent för att visa Cookie-notisen på webbplatsen

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i Internet explorer, Edge, Chrome och safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1426%3A0&viewport=-480%2C106%2C0.558458&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-cookie-notice

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd! Dock är det en grå ram runt knappen, är det rätt?
