### ISSUE TITLE
Komponent för A-Ö filtrering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#285]
# Beskrivning
Vi behöver en komponent som visar hur en A-Ö filtrering ser ut.

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i Internet explorer, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1408%3A4056&viewport=-4044%2C-2660%2C0.788411&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-filter-alphabet

**Comment by fridabergentoft** [comment]
Komponenten är nästintill klar. De bokstäver som är närmst kanten på filtreringen är blir fyrkantiga menen hörnen på filtret är runda. Det blir lite knas samt att den blå kanten inte går hela vägen ut på högerkanten.
