### ISSUE TITLE
Herobild på alla sidor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#291]
# Beskrivning
Redaktörerna vill ha möjlighet att lägga in Hero-bild på alla sidtyper på Vuxhalland

# Acceptanskriterier
- [x] Lägg till fältet för Herobild på alla sidtyper på Vuxhalland
- [x] Om det inte finns någon uppladdad bild i fältet så ska det heller inte ta plats på sidan.

**Comment by viktor-sarge** [comment]
Det är inlagt så att om det finns en bild så visas hero-komponenten inklusive labeln, men utan bild visas inte något. Finns på alla sidor på sajten. Syns när vi plockar upp masterbranchen på miljön. Lägger till qa så hämtar vi upp på stage/test så fort som möjligt,

**Comment by viktor-sarge** [comment]
(Ang. acceptanskriterierna så används inte något fält i backend utan vanliga "utvald bild" + sidans titel)
