### ISSUE TITLE
Skisser Vuxhalland

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#294]
# Beskrivning
Vi behöver ta fram uppdaterade skisser för Vuxhalland. Dels för att våra komponenter kan ha ändrats lite och dels för att intressenterna har kommit med nya inspel.

# Acceptanskriterier
- [x] se bifogade bilder
- [x] Uppdatera även listningssidan med rätta komponenter

![startsida.PNG](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/bb1e2074-37d7-4255-ba71-131fa1641f37)

![yrkesvux.PNG](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/ac3fb33d-d33b-4238-b298-1e5117c0710e)

![Hitta din grej.PNG](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/7d373783-7bd4-4a49-a369-bed4510f0d37)

**Comment by fridabergentoft** [comment]
Länk till skiss: https://www.figma.com/file/UcCKUeD0rOMIfw6vE81JxADM/vuxhalland-wireframe?node-id=85%3A1922
