### ISSUE TITLE
Innehåll i sidfot

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#295]
# Beskrivning
Redaktionen vill ha bifogat innehåll i sidfoten på regionhalland.se.
[https://app.zenhub.com/files/158801558/6064ee3c-8ff9-49da-ae97-8df88b83ac47/download](https://app.zenhub.com/files/158801558/6064ee3c-8ff9-49da-ae97-8df88b83ac47/download)

# Acceptanskriterier
- [ ] Lägg in bifogat innehåll i sidfoten för regionhalland.se

**Comment by viktor-sarge** [comment]
Innehåll i sidfot är inlagt enligt bifogad fil och två plugin används för att hämta sidträden dynamiskt. Underlaget behöver dock kompletteras så kan vi fixa till det sista. De kan se resultatet nästa gång vi uppdaterar test-rh.
