### ISSUE TITLE
Hela puffen ska vara klickbar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#302]
# Beskrivning
Vi behöver göra hela puffen klickbar. När komponenten sen byggs om ska den justeras så att den ser ut som på skisserna. Vi behöver även lägga till en container så att hela sidan blir som på Fridas skiss över t ex startsidan på regionhalland.se.

# Acceptanskriterier
- [x] Som besökare kan jag klicka var som helt på puffen (Bild, rubrik, text) för att komma vidare
- [x] Komponenten behöver en tydligare hooverstate 
- [x] Det finns en skiss en Figma som visar desktop, tablet och mobil
- [ ] Den uppdaterade komponenten finns i stilguiden för desktop, tablet och mobil
- [ ] Den uppdaterade komponenten fungerar i IE, Edge, Safari och Chrome
- [ ] Bilden i komponenten har måtten 416x195
- [ ] Hela komponenten är 416x381
- [ ] Se till så att komponenten motsvarar skissen (rundade hörn, rubrik och text mm)

**Comment by fridabergentoft** [comment]
Är detta rimlig hover-state eller är den allt för diskret?

Länk: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2065%3A4374&viewport=226%2C531%2C0.10978616774082184&scaling=min-zoom

**Comment by viktor-sarge** [comment]
Ihop med bild är det gränsfall till för diskret. Men det är helt klart en bra början. Tror att tekniken att hela puffen får en focus-state kommer antingen behöva göras med javascript eller att det går att bygga tillsammans med att man gör hela länken klickbar. 

Vi kan börja såhär och kika på hur det känns när man använder det live.

**Comment by JohannaOlin** [comment]
Flyttad till devops 2673
