### ISSUE TITLE
Byt namn på Kulturevenemang till Arrangemang

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#305]
# Beskrivning
Kulturen vill att det ska heta arrangemang istället för Evenemang

# Acceptanskriterier
- [ ] I länkstigen ska det stå Kulturarrangemang
- [ ] Rubriken för listningen ska vara Kulturarrangemang

**Comment by RolandHyden** [comment]
Fixat.

Plugin: https://github.com/RegionHalland/region-halland-acf-page-kulturarrangemang
Version 2.1.1
