### ISSUE TITLE
A-Ö sida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#306]
# Beskrivning
Vi behöver ta fram en sidtyp där vi kan presentera A-Ö listor

# Acceptanskriterier
- [ ] Sidan ska fungera på desktop, tablet och mobil
- [ ] Sidan ska fungera i Internet explorer, Edge, Safari och Chrome
- [ ] Sidan ska följa den skiss Frida har tagit fram för komponenterna
- [ ] Sidan ska innehålla rubrik, ingress och textfält
- [ ] Sidan ska innehålla en A-Ö filtrering
- [ ] Redaktören ska kunna peka ut varifrån innehållet som ska populera listan ska hämtas. Det kan vara undersidor till en viss nod, det kan vara länkar som redaktören lägger in.
- [ ] Som redaktör kan jag välja Kontaktkort person
- [ ] Som redaktör kan jag välja Innehållsansvarig för sidan.

**Comment by viktor-sarge** [comment]
A-Ö finns implementerat på stage för regionhalland.se. Roland har byggt backend, jag har gjort blade-filen baserat på Rolands dokumentation och exempel-bladefil och Fridas skisser. Martin hittade en bugg som fixades idag och jag tror den här är redo för leverans.
