### ISSUE TITLE
Slå ihop mallarna för Section Overview och Section Page

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#307]
# Beskrivning
Vi behöver endast en av dessa mallar så slå ihop det till en och samma mall. Namnet ska vara Sektionssida

# Acceptanskriterier
- [ ] De sidor som redan använder någon av mallarna ska fortfarande fungera

**Comment by viktor-sarge** [comment]
Detta är ändrat på regionhalland.se och driftsatt. Jag har ändrat mallarnas namn till svenska och sedan hjälpte Roland mig att byta alla sidor i databasen som använde fel mal. Jag har raderat den gamla mallen i git.
