### ISSUE TITLE
Kontaktkort för person

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#308]
# Beskrivning
Vi behöver kunna lägga in kontaktkort för personer på sidorna. Informationen ska hämtas från Hallandskatalogen och denna hämtning hanteras i ett separatkort. Detta kort gäller möjligheten för redaktören att välja kontaktperson i adminläget.

# Acceptanskriterier
- [ ] Som redaktör kan jag välja en person i Hallandskatalogen att visa upp som kontaktperson på sidan
- [ ] Fältet ska finnas tillgängligt på följande mallar: standardmall, nyhet, kulturarrangemang, kulturprogram
- [ ] Det som ska visas på sidan är Namn, Titel och Mobilnummer i steg 1

**Comment by viktor-sarge** [comment]
Själva kontaktkortet tror jag är färdigt om jag minns rätt. Vet att Roland jobbar på backendgrejorna. Jag sätter oss båda på den här.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Jag har kollat på denna på stage nu, se t ex sidan http://stage-rh.regionhalland.se/halsa-och-vard/varden-i-halland/vard-nara-dig/vardcentralen-halland/vara-vardcentraler/vardcentralen-getinge/ och har följande kommentarer.

- [ ] Det är väldigt liten text, både namnet och titeln

**Comment by viktor-sarge** [comment]
Jag kikar varför men gissar att det är relativt enkelt att fixa. Jag kunde ju inte se hur det blev förut utan har bara lagt in brights komponenter. Nu kan vi sätta igång och fixa till dem :)

**Comment by viktor-sarge** [comment]
Fixat. Ligger i dev + master-branch. Lägger till QA.
