### ISSUE TITLE
Kulturarrangemang ompekning av sida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#311]
# Beskrivning
I steg 1 så har vi ingen filtrering och vi listar endast alla aktuella arrangemang från dagens datum och framåt. Ingen paginering heller.

- [x] Vi löser så att Lindas sida http://stage-rh.regionhalland.se/kultur/konst-och-kulturupplevelser/ direkt leder till http://stage-rh.regionhalland.se/kulturevenemang/ (fast adressen ska byta till kulturarrangemang) men inställningen att visa arrangemang taggade med Kultur

- [x] De kalenderpuffar som ska visas på sidan http://stage-rh.regionhalland.se/kultur/ läggs in på sidan http://stage-rh.regionhalland.se/kultur/konst-och-kulturupplevelser/.

- [x] Sidan http://stage-rh.regionhalland.se/kultur/konst-och-kulturupplevelser/ görs om till en sektionssida (eftersom puffmöjligheten så småningom ska försvinna på vanliga sidor)

**Comment by viktor-sarge** [comment]
Har inte bytt sidmall på stage. Men testat på test-rh och allt verkar funka.
