### ISSUE TITLE
I-Frame sida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#316]
# Beskrivning
Vi behöver lägga till en mall för I-frame som man kan visa över hela bredden, se t ex http://regionhalland.se/utveckling-och-tillvaxt/en-tillvaxtstrategi-vaxer-fram/uppfoljning-av-tillvaxtstrategin/uppfoljning-2018/hog-attraktivitet/.

# Acceptanskriterier
- [ ] Sidan ska visas över hela bredden
- [ ] Sidan ska visa sidhuvud
- [ ] Sidan ska visa länkstig
- [ ] Sidan ska visa sidfot
- [ ] Som redaktör kan jag peka ut en adress till det som ska bäddas in

**Comment by RolandHyden** [comment]
Det finns nu en plguin för detta:

https://github.com/RegionHalland/region-halland-acf-page-i-frame

Det som används nu är version 1.1.0.

Det fungerar som så att inne i admin så kan man välja en template (mall) som heter "I-frame sida". Då visas en ruta där man kan skriva in en länk. Denna länk öppnas sedan i en i-frame med just nu höjd 700px.

Vi kan ju finjustera lite om behov finns. Denna plugin är uppladdad på stage-rh.
