### ISSUE TITLE
404-sida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#317]
# Beskrivning
Redaktionen vill ha in nedanstående innehåll på 404-sidan på regionhalland.se

# Det här kan du göra
•	Gå till startsidan www.regionhalland.se och försök klicka dig fram till informationen du söker.
•	Använd den här webbplatsens sökfunktion.
•	Sök via en extern sökmotor som till exempel Google eller Bing.
•	Ladda om sidan för att se om det var ett tillfälligt fel.
•	Kontrollera om du skrivit in adressen rätt.

# Ansökningsperiod skolor
Information och ansökan till lantbruksgymnasium och folkhögskolor

# Hjälp oss att bli bättre
Att sidan inte hittades kan bero på flera saker. Det kan vara så att vi gjort fel eller så är det fel någon annanstans. Välkommen att höra av dig via e-post så har vi större chans att rätta till det. 

- [x] "höra av dig via e-post" ska vara en mailto länk till infomaster@regionhalland.se.
- [x] www.regionhalland.se ska så klart vara länkat
- [x] "Information och ansökan till lantbruksgymnasium och folkhögskolor" ska länkas till http://regionhalland.se/vara-skolor/

**Comment by viktor-sarge** [comment]
Den här är gjord. Skall uppdatera stage-rh med det senare och lägger den till QA då

**Comment by viktor-sarge** [comment]
Upplagd på stage. 
(Listan med bullets syns inte pga reset-filen så den behöver ett återbesök efter att storyn om listor är gjord för att se att det blir bra.)
