### ISSUE TITLE
Förändring av kalenderpuff - skiss

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#319]
# Beskrivning
Vi har fått synpunkter från redaktörer att de vill ha en bättre puff för kalenderhändelser. Just nu använder de istället de vanliga puffarna, men detta blir då ett manuellt arbete.

Vi behöver ta fram en puff för kalenderhändelser som fungerar både med och utan bild och där datumet är tydligt.

**Comment by fridabergentoft** [comment]
Kan jag återanvända puffen från Musik Hallandia som kalenderpuff?
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=1909%3A4219&viewport=-1259%2C2089%2C0.5318861603736877&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Det tycker jag absolut att vi kan göra.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Tittar du på denna? Komponenten är väl byggd redan för Musikhallandia, men verkar inte ligga i stilguiden. Dels ska ju komponenten byggas och sen ska den läggas in på regionhalland.se. Det krävs lite backend utveckling också för att få funktionaliteten på plats, men komponenten behöver ju vara byggd först.

**Comment by JohannaOlin** [comment]
Jag stänger detta och lägger upp ett nytt kort på att bygga själva komponenten. Sen blir det ett eget kort att lägga in komponenten på regionhalland.se där det även ska till en del back-end justeringar.
