### ISSUE TITLE
Korr på regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#322]
# Beskrivning
Detta kort används för att skriva ner justeringar på det nya utseendet.

# Färdigt
- [x] Fältet Navigationstext ska användas även på startsidan
- [x] På sektionssidan http://stage-rh.regionhalland.se/utveckling-och-tillvaxt/ så finns ett glapp i navigationen
- [x] Hitta på sidan ej stylad
- [x] Länkarna under Ämnesområden i sidfoten ligger för tätt
- [x] När rubriken ligger på två rader så är det mycket mellanrum mellan raderna och extremt i mobilläget, gäller även andra nivåer av rubriker http://stage-rh.regionhalland.se/utveckling-och-tillvaxt/skolutveckling-utbildning-och-kompetensforsorjning/sprakstart/darfor-satsar-vi-pa-sma-barns-sprakutveckling/. http://test-rh.regionhalland.se/kultur/kulturformer-och-utvecklingsomraden/litteratur/game-jam-design-and-writing/
- [x] Navigationskorten på sektionssidorna ligger för långt till vänster, de borde vara jämnt fördelade över rutan
- [x] Alla nyheter inom en viss kategori visas nu på sektionssidorna. Det ska endast vara 4 st
- [x] Flytta ner texten senast ändrad så att den separeras från innehållet lite mer
- [x] Kan vi ändra så att hela raden i vänsternavigationen är klickbar i mobilläget. Nu är bara texten klickbar
- [x] Det är väldigt långt mellan "vänstermenyn" och sidans rubrik i mobilläget
- [x] 5 puffar på startisdan (tre olika beteenden från puffarna. Alltid små, flexande och alltid stor). Hårdkoda. 
- [x] Punktlistor visas inte med punkterna, se sidan http://stage-rh.regionhalland.se/utveckling-och-tillvaxt/skolutveckling-utbildning-och-kompetensforsorjning/sprakstart/darfor-satsar-vi-pa-sma-barns-sprakutveckling/

- [x] Styla kontaktkort enhet samt Kontaktkort person

- [x] Navigationskorten hamnar inte i tre kolumner på sektionssidorna i IE

- [x] Listan med Kulturprogram spricker i IE, http://stage-rh.regionhalland.se/kulturprogram/

- [x] När man lägger in 3 puffar på en sektionssida så hamnar den tredje puffen på en egen rad i IE

- [x] Navigationskorten hoppar lite lustigt när man minskar och ökar sidan, gäller sektionssidor

- [x] sektionssidor skall ha nya pufftypen.

- [x] Byt breadcrumbs plugin till den som bara är pages .(visar puffrubriker idag)

- [x] Kulturens startsidesmall med extra puffrad kopplad mot en egen sida. (Fixad, men behöver lite backendfunktionalitet för att visa rätt puffar)

- [x] Ingen styling på söket

- [x] Ändra innehåll i sidfoten - issue 331

- [x] Ändra innehållet på 404-sidan - issue 317
- [x] Vänstermenyn ska stylas om
- [x] Loggan är liten i IE, ska även bytas ut se issue 336
- [x] Arrangemangskalender, ta bort det nedre datumet, http://stage-rh.regionhalland.se/kulturarrangemang/
- [x] Listan med Kulturprogram ser lite rörig. Snabbaste lösningen är att ta bort målgrupp och bara lista rubrikerna.
- [x] Pilarna i navigationen ska vara gröna, Själva pilarna ska vara vita, men den runda plattan grön
- [x] Sökknappen ska vara grön även i sidhuvudet
- [x] Labels i nyhetslistan ska vara gröna
- [x] När man skalar ner (eller har mindre skärm) så finns det ingen marginal i vänsterkant på sidfoten. Det kanske inte finns någon i högerkanten heller, men det märks inte
- [x] Nyhetsarkivet i IE ligger väldigt långt till vänster
- [x] Kan vi testa att centrera sidfoten eller göra den till 4 kolumner
- [x] Ska länkarna i sidfoten vara blå eller svarta?
- [x] Nyhetssidorna är väldigt breda, blir de inte lite svårlästa?
- [x] Lägg in sortering av nyheter - issue 326
- [x] Lägg in sidmall för iframe-sida - issue 316
- [x] Ändra ikon för Topplänk
- [x] Ändring på 404-sidan. Under rubriken "Hjälp oss att bli bättre" ska texten vara: "Att sidan inte hittades kan bero på flera saker. Det kan vara vi som har gjort fel eller det kan vara felaktiga länkar till vår webbplats någon annanstans. Välkommen att höra av dig via e-post så att vi får reda på vad som inte fungerar.”

- [x] Ändra text på 404-sidan. Det ska stå "naturbruksgymnasium" istället för "lantbruksgymnasium"

- [x] Pilen i tillbaka länken ska också vara vit på grön platta

- [x] Det är dubbla "Andra webbplatser" i sidfoten nu, ta bort den som ligger under "Aktuellt"
- [x] Lägg in kontaktlänk - issue 259
- [x] Lägg till ingressfält på Kulturarrangemangen - issue 340
- [x] Ingressen är inte rätt stylad
- [x] Söksidan går över hela bredden i IE
- [x] Peka om sidan för Kulturprogrammen - issue 339
- [x] Sökknappen ser lustig ut i IE. Den verkar vara lägre än sökrutan och texten ligger inte centrerad.
- [x] Ändra stylingen på ingressen på Kulturarrangemangen så att den blir samma som på sektionssidorna
- [x] Arrangemangsssida och Programsida, ta bort kommatecknet efter den sista kategorin som visas
- [x] Lägg in ingressfält för nyheter - issue 281
- [x] Kan vi ha en svart länk på Tillbaka-länken?
- [x] Footern i mobilen, vissa rubriker ligger väldigt nära texten ovanför
- [x] Footern i tablet - se över mellanrummen mellan rubrikerna, de verkar inte vara jämna
- [x] Kan vi hårdkoda in en Tillbaka-knapp på listningarna för Kulturarrangemang respektive Kulturprogram så att de kan nå strukturen under Kultur där?
- [x] När jag hoovrar över vänstermenyn så blir den blå, den borde bli grön
- [x] Det är blå hoover i pagineringen
- [x] Flytta ner senast ändrad lite på en arrangemangssida och programsida
- [x] Vid sökning som ger många träffar så lägger sig pagineringen ovanpå varandra i IE. Testa att söka på Vård
- [x] När man skalar ner sidan så att sökknappen blir ett förstoringsglas så går det inte att söka, inget händer när jag klickar på knappen
- [x] Ta bort länkstigen i mobilen
- [x] Rubriker i löptext som blir på två rader, se ex http://stage-rh.regionhalland.se/kultur/kulturformer-och-utvecklingsomraden/kulturaktorer-med-regionalt-uppdrag/, har för långt avstånd mellan raderna
- [x] Rubriker som blir på två rader i nyhetslistan har för långt avstånd mellan raderna, se ex nyhetslistan på http://test-rh.regionhalland.se/jobb-och-karriar/
- [x] Lägg gärna lite marginal i nederkanten på navigationskorten så som det är på puffarna. Det märks framför allt i mobilen där sista navigationskortet hamnar lite utanför boxen.
- [x] Nu när puffarna har en fast höjd så blir det tokigt i mobilen där rubriken ofta hamnar på två rader. Då får inte all text plats.
- [x] Det är väldigt tätt mellan sista raden pufftext och den gröna linjen i mobilen. Kanske kan detta lösas genom att flytta upp rubriken lite för den ligger ganska långt under bilden.
- [x] Lägg in komponenten för 1177 i söket, https://stilguide.regionhalland.se/components/detail/rh--rh-search-external-link-1177.html 
Text från redaktionen:
Text till söksidan för länkning vidare till 1177:
Rubrik ska vara "1177 Vårdguiden" och denna ska vara länkad. Texten under ska vara:
” Kontaktuppgifter, öppettider och övrig information om vård- och tandvårdsmottagningar hittar du på 1177.se. Där finns också information om hälsa, sjukdomar, besvär och rättigheter.”
- [x] Ta bort sekunder från senast ändrad i sökresultatet
- [x] Lägg lite luft mellan länken Lämna synpunkter och sidfoten
- [x] Rubriker som är på två rader i navigationskorten behöver mer mellanrum mellan raderna. Nu går rad två in i cirkeln med pilen.
- [x] Aktivera Matomo - issue 333
- [x] Sökknappen på söksidan i IE är inte lika stor som sökrutan
- [x] Ändra länk i sidfot, den som heter "Region Halland i sociala medier" ska gå till http://stage-rh.regionhalland.se/om-region-halland/kontakt/socialamedier/
- [x] Bilderna och filmer som läggs i textfältet skalar inte ner i mobil, se ex http://test-rh.regionhalland.se/vara-skolor/munkagard/boende-och-fritid/ samt http://test-rh.regionhalland.se/om-region-halland/kontakt/hak-test/
- [x] Alla bilder verkar inte visas i mobilläget, http://test-rh.regionhalland.se/kultur/kulturformer-och-utvecklingsomraden/litteratur/hallandsk-bokmassa/ 
- [x] Puffbilderna verkar ha fel höjd nu
- [x] Active state på sökrutan i sidhuvudet får en blå ram, ändra denna till en svart ram istället

# Prio 1

- [ ] Förstoringsglaset är inte centrerat i sökknappen på mobilen och den ska vara grön. Gör den större också så att den i alla fall är lika stor som talande webb

# Prio 2

- [ ] Pilarna (i navigationen och i länkstigen) blir ibland kinesiska (?) tecken

- [ ] Listan med kulturprogram ligger centrerad i IE, men inte i övriga webbläsare, det är bättre med vänsterställd

- [ ] Listan med kulturprogram fyller hela bredden, dvs ligger för långt till vänster och höger jämfört med sidfot och sidhuvud i IE

- [ ] I listan med kulturprogram så ska varannan kategori vara vit och varannan grå

- [ ] Hitta på sidan blir för bred när man scrollar och man har en lång rubrik, se sidan http://stage-rh.regionhalland.se/kultur/kulturformer-och-utvecklingsomraden/kulturaktorer-med-regionalt-uppdrag/

- [ ] Det går inte att klicka Enter vid sökning i Edge - Denna går inte att fixa verkar det som

**Comment by viktor-sarge** [comment]
Släckte "fältet navigationstext ska användas även på startsidan". Har pushat till repot och kommer med nästa gång som stage-rh uppdateras.

**Comment by viktor-sarge** [comment]
Glapp i navigation - jag har precis pushat en version av styleguide + lagt in i regionhalland.se där maxbredden på navkort är borttagen i styleguiden så att blade-filerna kan styra med sin kolumn-logik istället. Då blir de inte dubbla system som styr layouten.

**Comment by viktor-sarge** [comment]
- [x] Flytta pilar på navigationskort till vänster.

Har ändrat i styleguidens CSS + exempel och lagt in en ny version på regionhalland.se och uppdaterat template-filerna.

**Comment by viktor-sarge** [comment]
Släckte "Navigationskorten på sektionssidor ligger för långt till vänster" eftersom detta också löstes när navigationskorten inte längre har en maxbredd.

**Comment by viktor-sarge** [comment]
Punktlistor och rubrik på två rader beror på att vi tömmer allt utseende i reset.scss. Sitter med det nu men har lite svårt att få webbläsaren att acceptera att mina undantagsregler skall slå igenom.

**Comment by viktor-sarge** [comment]
- [ ] Navigationskorten ser konstiga ut i IE + Edge. 

Verkar bero på användningen av "flex" i styleguiden. Jag kollar över och tar bort flex.

**Comment by viktor-sarge** [comment]
- [x] Finns för många mallar.

**Comment by viktor-sarge** [comment]
(Många mallar beror på att vi hade en "views-old" med gamla filer kvar)

**Comment by viktor-sarge** [comment]
Roland rensat gamla mallar. Jag har verifierat att det nu är endast de som skall användas som syns.

**Comment by viktor-sarge** [comment]
Puffar på startisdan. Gjorde dem idag, men även den nya implementationen från scratch har en bugg i IE som gör att de inte flyter korrekt. Får kika på det igen.

**Comment by viktor-sarge** [comment]
Finns nu en speciell sida "Förstasidan" på stage-rh.regionhalland.se som de knyter puffar till. Dessa visas automatiskt på förstasidan i den ordning som redaktionen väljer. Vill de använda ingresser, content, nyheter osv är det också på den sidan de lägger in det (och säger till oss så att vi hämtar upp det)

**Comment by viktor-sarge** [comment]
Sett till att bara fyra nyheter visas på sektionssidan.

**Comment by viktor-sarge** [comment]
Hela vänsternavigationen är nu klickbar.

**Comment by viktor-sarge** [comment]
Avståndet mellan vänsternav och rubrik i mobilläge är minskat.

**Comment by viktor-sarge** [comment]
"Senast ändrad"-texten är nu bättre placerad med lite avstånd till texten.

**Comment by viktor-sarge** [comment]
Länkarna i sidfoten ligger för tätt - fixat. Ändrade line height för allt på hela sajten till 1.4 som en snabb fix. Är de inte nöjda med det kan vi ta det komponent för komponent, men behövde få en "quick and dirty"-lösning på plats åtminstone.

**Comment by viktor-sarge** [comment]
Kulturens mall fungerar nu. Den har också extra puffraden, men det behövs lite extra backend-funktionalitet i pluginet för att hämta alla puffar från en specifik sida. Just nu kan man hårdkoda in utvalda puffar, men det täcker inte caset.

**Comment by viktor-sarge** [comment]
Det snabba line-height hacket gjorde att rubriker på två rader också är fixat.

**Comment by viktor-sarge** [comment]
Puffar på startsidan har funkar nu i IE

**Comment by viktor-sarge** [comment]
Att loggan (och andra SVG-filer) är för små: har konstaterat att det beror på att IE inte hanterar SVG:er korrekt. Har hittat artiklar som ger vägledning men behöver läsa på. Tar först saker som är mer synligt fel tills vidare.

**Comment by viktor-sarge** [comment]
Roland och jag har fixat hitta på sidan. Den är nu stylad på ett tillfresdsställande sätt och vi har också lagt till ett beteende där den krymper ihop för att ta mindre plats när den hamnar över footern. Som ett sista steg tänkte vi också lägga till olika indrag beroende på rubriknivå.

**Comment by viktor-sarge** [comment]
Nu har hitta på sidan också indrag för underliggande rubriker.

**Comment by viktor-sarge** [comment]
Grundläggande styling av söket är inlagt, men det behövs lite mer även för en första version. Jag jobbar vidare med det, men den är iaf funktionell på stage-rh nu.

**Comment by viktor-sarge** [comment]
Kulturens specialmall är färdig och har fått rätt backendfunktionalitet.

**Comment by viktor-sarge** [comment]
Breadcrumbs är fixade på stage-rh vad jag kan se nu. Uppdaterat till Rolands nya version av den tidigare pluginen, han hittade en bugg i den som relaterade till andra ändringar.

**Comment by viktor-sarge** [comment]
Lite fix kvar på träfflistan i söket men det är fullt ok och funktionellt ändå.

**Comment by viktor-sarge** [comment]
Stylade om vänstermenyn eftersom det var en snabb grej. Men grönt och grått gav väldigt dålig kontrast så fick dra upp storleken rejält för att passera AA-nivå. Inte säker på att vi vill ha det såhär, men nu syns den på stage-rh iaf.

**Comment by viktor-sarge** [comment]
Problemet med listan på kulturprogram är att IE inte stöder "flex". Jag får göra en ny implementation utan flex.

**Comment by JohannaOlin** [comment]
@regionhallandviktor och @fridabergentoft Nej, vänstermenyn blev inte jättesnygg. Kan vi göra en snabb fix och dra ner storleken igen och ändra den gröna texten till att vara svart och bold istället? Så får vi fundera vidare efter lanseringen.

**Comment by viktor-sarge** [comment]
@JohannaOlin Vänstermenyn har mindre och svart text nu.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Det blev bättre, så får det vara så länge

**Comment by viktor-sarge** [comment]
@JohannaOlin  Gott, då lämnar vi vänsternav så tills vidare. 

Jag är "färdig" med söket. Finns saker som behöver omsorg, men nu är det bra nog att beta av andra saker under tiden.

**Comment by viktor-sarge** [comment]
"Det går inte att klicka Enter vid sökning i Edge" - Jag kan inte replikera den buggen. Har testat Edge och IE på stage-rh med senaste koden. Släcker tills vidare.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Det gäller bara Edge och sökrutan i sidhuvudet. Både jag och Frida kan återskapa det. Det funkar om man klickar Enter 2 gånger. Inte så prioriterat dock, det kan vi fixa efter tisdag.

**Comment by viktor-sarge** [comment]
Sidfoten skall vara fixad. Har leverarat storyn

**Comment by viktor-sarge** [comment]
Puffarna på sektionssidor utbytta till samma som startsidan. Inklusive kulturens specialtemplate. Verifierat att det funkar i IE. Vi kan tweaka lite på paddings senare om de så önskar.

**Comment by viktor-sarge** [comment]
Att det ibland blir kinesiska tecken beror på det CDN som vi hämtar feather ifrån. Kanske bättre att vi lägger det lokalt eller på eget CDN.

**Comment by viktor-sarge** [comment]
Punktlistor är genomgångna. Löst med en liten inlinestyle i head + att alla ställen som skall ha bullets får klassen rh-article. Contentsidor, och olika speciella single-page mallar är fixade samt 404-sidan.

**Comment by viktor-sarge** [comment]
Numrerade listor är fixade nu - samma beteende som de onumrerade.

**Comment by viktor-sarge** [comment]
Gått igenom typografin och tagit bort den minsta fontstorleken.

**Comment by viktor-sarge** [comment]
Kontaktkorten är stylade och det finns nu en ny partial-fil. När vi har rätt API så är det bara att infoga partial-filen där vi vill ha kontaktkort. De visas heller inte om de inte innehåller någon data.

**Comment by viktor-sarge** [comment]
Kulturarrangemang fick lite omsorg. Labels.

**Comment by viktor-sarge** [comment]
Kulturprogram fixades till med en lite bättre layout

**Comment by viktor-sarge** [comment]
Gröna detaljer istället för blå är fixat. Ändrat direkt i styleguiden.

**Comment by viktor-sarge** [comment]
(Ändrat till smalare nyhetssidor, men composer kör så kan inte lägga upp det ännu)

**Comment by viktor-sarge** [comment]
Nyhetssidorna smalare - updpaterat på stage.

**Comment by viktor-sarge** [comment]
Bytt till `<footer>` istället för div på footern.

**Comment by viktor-sarge** [comment]
Fyra kolumner sidfot. 
Svarta länkar i sidfot.

**Comment by viktor-sarge** [comment]
Nyhetsarkivet fick nu helsvarta länkar istället för svart med blå understrykning.

**Comment by viktor-sarge** [comment]
Nyhetsarkivet - vänsterliggande är fixat. (verkar som IE inte tolererar main-taggen. Bytt till en div och wrappar allt i main istället)

**Comment by viktor-sarge** [comment]
Ingressfält på nyheter inlagt i backend.

**Comment by viktor-sarge** [comment]
Tightat till söksidan så den har lite mer luft mellan spalterna.

**Comment by viktor-sarge** [comment]
Marginaler på sidfot fixat.

**Comment by viktor-sarge** [comment]
Roland har fixat iframe-sidan så släcker den storyn här också

**Comment by viktor-sarge** [comment]
Roland och jag kikat snabbt på bilder som inte skalas. Provade att sätta bredd 100% men eftersom vi inte har kontroll över vilken kod Wordpress infogar bilderna med så behöver vi nog ändå gå mot fasta bredder baserat på brytpunkter som jag först trodde.

**Comment by viktor-sarge** [comment]
Bytt ikon för talande webb (var snabbt gjort)

**Comment by viktor-sarge** [comment]
404 korrigerad då det var så snabbt gjort.

**Comment by viktor-sarge** [comment]
Fixat dubletten på "Andra webbplatser" i footern.

**Comment by viktor-sarge** [comment]
(Avstår från att försöka lägga till de svarta strecken i footern eftersom det blir lite tight när vi kör fyra spalter)

**Comment by viktor-sarge** [comment]
Tillbaka-pilen är fixad grön + vit.

**Comment by viktor-sarge** [comment]
Kontaktlänk inlagd på pagesidor och nyheter

**Comment by viktor-sarge** [comment]
Ingress. Vi diskuterade. Behåller fetstilad på page-sidor. Men har dragit upp storleken på översiktssidorna.

**Comment by viktor-sarge** [comment]
Sidan för kulturprogram ompekad och övriga punkter åtgärdade på kortet. Upplagt på stage. De behöver flytta informationen till en annan sida.

**Comment by viktor-sarge** [comment]
Sökknappen är fixad i IE. Visade sig att knapp och textfält inte blev lika stora i IE när man satte identisk padding och fontstorlek så bytte till en fast höjd (+bredd för knappen).

**Comment by viktor-sarge** [comment]
Ingress på kulturarrangemang fixad.

**Comment by viktor-sarge** [comment]
Undersöker puffbilderna. Ser att de är korrekt uppmärkta i backend i puffen med höjd 195px. Men när jag hämtar ut dem får jag större bilder. Frågan är alltså om vi kan få ut en färdigskalad bild i rätt format. Om inte får vi antingen skala dem korrekt fysiskt innan vi lägger upp dem eller ladda för stora bilder och göra dem mindre i frontend. Sistnämnda är den dålig lösning, men jag tror det går att få dem korrekta fr Worpress. Pratat lite med Roland om det.

**Comment by viktor-sarge** [comment]
Sökruta på mobil - har labbat lite. Den sätts till "display: none" under en viss breakpoint. Det går utmärkt att trigga så att den visas när man klickar på knappen, men layouten blir knepig. För att få det att bli snyggt tror jag att jag får implementera om huvudet med grid-systemet istället. Då kan vi sätta den till col-12 på mobil och bara toggla display med knappen.

**Comment by viktor-sarge** [comment]
Tagit bort sista kommat på program och arrangemang.

**Comment by viktor-sarge** [comment]
Dubbla klick i Edge. Undersökt lite. Funderar på om det är ett beteende i Edge att man först måste godkänna förslaget man får och sedan skicka själva sökningen, men det verkar inte vara fallet. Kikar vidare.

**Comment by viktor-sarge** [comment]
Dubbla klick i Edge. Hittat en diskussion på https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13479607/ där det anges att det är förväntat beteende att Edge kräver att man först godkänner ett sökförslag och att det beror på inställningen "spara formulär". Inte säkert att vi kan göra något åt det.

**Comment by viktor-sarge** [comment]
Gått igenom footern. Fått till  jämna mellanrum på mindre viewports. Behövde ändra beteendet från 3 till 2 responsiva lägen. Antingen är det fyrspalt eller enspalt. Ser bättre ut än tidigare så rent pragmatiskt är det bästa valet just nu.

**Comment by viktor-sarge** [comment]
@JohannaOlin Har undersökt puffarna och att det blir tight i mobilen. Att det skulle finnas mer plats är en synvilla. Det beror på att bilderna har ett format som gör att de inte tar upp hela sin container. Det syns väldigt tydligt om man lägger bakgrundplatta bakom bilden, men det blir väldigt fult. Fast höjd är ju nödvändigt för att det skall se bra ut i desktop/tablet när, men funkar mindre bra i mobilläget. Frågan är om man inte behöver skriva om dem så att de får helt olika regler baserat på breakpoints. De blir så smala så de behöver mer höjd i mobilläget. Jag har ökat utrymmet lite på höjden som en "gott nog just nu" men det är fortfarande inte bra. Behövs ändras mer i deras grundbeteende.

**Comment by viktor-sarge** [comment]
Senast ändrad på arrangemang- och programsida är nedflyttat.

**Comment by viktor-sarge** [comment]
Jag har justerat puffarna något på stage så att de har lite mer space. Det gör det en aning bättre i mobilen. Hinner jag så försöker jag ge dem ett nytt beteende så att de har flexibel höjd på mobil. (Men behåller fix höjd så länge de förväntas ligga horisontellt)

**Comment by viktor-sarge** [comment]
Vänstermenyn har grön hoverstate.

**Comment by viktor-sarge** [comment]
Ändrat färgen på pagination, men det slår inte igenom som önksat. Men ser rätt ut i filen. Avvaktar något och ser om det är cache-fråga. Kan ev. byta sökväg så att det tvingas fram en ändring.

**Comment by viktor-sarge** [comment]
Blå paginering fixad.

**Comment by viktor-sarge** [comment]
Svart "tillbaka" är fixad.

**Comment by viktor-sarge** [comment]
Hårdkodad tillbaka-knapp fixad på kulturprogram och arrangemang.

**Comment by viktor-sarge** [comment]
Puffar och navigationskort har nu fått ett nytt beteende. Vid minsta breakpoint där de förväntas stacka vertikalt så har de variabel höjd så att allt får plats. När de ligger horisontellt så har de fast höjd (och tabletläget som är lite smalare har lite högre höjd). Ett övergående problem är att breakpoints för grid-systemet och styleguiden i övrigt inte går i synk så de får variabel höjd något för tidigt. Men det blir klart bättre i mobilen. Kan säkert behöva trimmas in, men principen är den bästa vi hittat än så länge.

**Comment by viktor-sarge** [comment]
Paginering i sök som lade sig ovanpå varandra är fixad.

**Comment by viktor-sarge** [comment]
(släckte frågan om att flytta upp text i navkorten eftersom den nya designen löser det problemet men på ett annat sätt än det föreslagna)

**Comment by viktor-sarge** [comment]
Länkstigen döljs nu i mobilen

**Comment by viktor-sarge** [comment]
Flimrande hitta på sidan är fixad.

**Comment by viktor-sarge** [comment]
Hitta på sidan döljs i mobilen.

**Comment by viktor-sarge** [comment]
Rubriker i löptext och i nyhetslistan genomgångna. De har en mindre line height internt men lite padding mot omgivande text för att kompensera. Har stämt av med Frida.

**Comment by viktor-sarge** [comment]
Nu visas sökrutan när man klickar på förstoringsglaset. Notera dock att ett sådant beteende är beroende av javascript och att användare utan javascript inte kommer att kunna göra en sökning. Bättre vore alltså att visa den hela tiden alternativt att döljandet av den i små enheter på något vis görs med javascript så att användare utan javascript fortfarande kan söka på mobilen.

**Comment by viktor-sarge** [comment]
Rubriker på två rader i navigationskort är fixade.

**Comment by viktor-sarge** [comment]
1177 i träfflistan är fixad.

**Comment by viktor-sarge** [comment]
Matomo är inlagt. (Om nu Matomo i sig självt faktiskt fungerar)

**Comment by viktor-sarge** [comment]
Luft mellan sidfot och "Läman feedback"-länk är fixat på page sidor.

**Comment by viktor-sarge** [comment]
Talande webb är aktiverat på stage.

**Comment by viktor-sarge** [comment]
Sekunder borta från sökresultatet.

**Comment by viktor-sarge** [comment]
Analytics är inlagt.

**Comment by viktor-sarge** [comment]
Länk till sociala medier är fixad i sidfoten.

**Comment by viktor-sarge** [comment]
Cookie-notis är inlagd och omstylad för att bli grön

**Comment by viktor-sarge** [comment]
Söksidan: 
* Sökträffars rubriker är gröna
* Brödsmulor har fått line height 1.4
* Brödsmulor är mindre än övrig text.
* Marginalerna som pajade utseendet är fixat
* Rubrikerna har en line height på 1.3

**Comment by viktor-sarge** [comment]
Sökknappen på söksidan är nu lika stor som själva rutan.

**Comment by viktor-sarge** [comment]
Puffarna har fått ett nytt beteende för att åtgärda problemet med bilderna. De har nu en maxbredd och kapar i sidled när man skalar ner. Jag skall förvandla dem till en ordentlig komponent i styleguiden, men det tar lite längre tid.

**Comment by viktor-sarge** [comment]
Bilder i textfält skalar nu ner i mobil (på stage - vi behöver uppdatera prod)

**Comment by viktor-sarge** [comment]
Bilder som inte visades verkar vara löst.

**Comment by viktor-sarge** [comment]
Sökrutan har svart active state nu

**Comment by JohannaOlin** [comment]
Jag har lagt resterande som egna issues, förutom den att det inte går att klicka Enter i Edge. Stänger detta ärende.
