### ISSUE TITLE
Skisser - Musik Hallandia

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#323]
# Beskrivning
Vi behöver göra om de skisser som Start tagit fram så att de använder våra komponenter istället.

**Comment by fridabergentoft** [comment]
Länk till skiss: https://www.figma.com/proto/FAbN8b1miI00Sfl3TtNWtVhX/MusikHallandia?node-id=14%3A2107&viewport=572%2C298%2C0.179008&scaling=min-zoom
