### ISSUE TITLE
Sortering av nyheter på sektionssidor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#326]
# Beskrivning
Nyheterna som visas på sektionssidor sorteras inte idag

# Acceptanskriterier
- [ ] Nyheter ska sorteras efter Publicerat-datum. Senast publicerad överst.

**Comment by RolandHyden** [comment]
Detta är åtgärdat. Nyheterna sorteras efter publiceratdatum + att default antal som hämtas ut är 4. Man kan dock när man anropar funktionen ange valfritt antal.
