### ISSUE TITLE
Skiss - blocksida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#327]
# Beskrivning
Vi behöver ta fram en skiss på en blocksida, dvs den sida som besökaren möts av om hen inte får gå in på sidan. Detta kan gälla både interna och externa besökare.

Göteborgs stad har t ex en sida som ser ut så här https://pedagog.goteborg.se/etc/passwd.

# Acceptanskriterier
- [x] Användaren ska uppmuntras att skicka med support-ID

**Comment by fridabergentoft** [comment]
Länk till skiss: https://www.figma.com/file/JdrL2M8xMFlwOFUstErPYmqg/regionhalland.se?node-id=1515%3A0

Osäker på vad mer som kan/ska adderas
