### ISSUE TITLE
Prototyp tabbar driftinfosajt

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#328]
# Beskrivning
För att vi ska kunna bygga färdigt driftinfosajten så behöver vi ta fram en komponent för dubbla tabbar, se t ex Skånes sida https://driftinfo.skane.se/Sidor/list_all.aspx

# Acceptanskriterier
- [x] Prototypen ska visa hur komponenten ser ut i desktop, tablet och mobil
- [x] Prototypen ska visa tabbar för Pågående, Kommande och Avslutade
- [x] Prototypen ska visa tabbar för Alla, IT, Telefoni och Fastighet
- [x] Prototypen ska visa siffor vid tabbarna Alla, IT, Telefoni och Fastighet

**Comment by fridabergentoft** [comment]
Jag använder mig av samma tabbar som till söket, med och utan siffer-label.
