### ISSUE TITLE
Prototyp driftinfosajt

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#329]
# Beskrivning
Nu när vi har byggt upp vårt komponentbibliotek så behöver vi ta fram en ny prototyp för driftinfosajten som använder de nya komponenterna

# Acceptanskriterier
- [x] Prototypen ska visa hur sajtens olika sidor ser ut på desktop, tablet och mobil
- [x] Prototypen ska visa sajtens sidhuvud
- [x] Prototypen ska tabbarna
- [x] Prototypen ska visa listan med driftstörningar
- [x] Prototypen ska visa Label för Akut respektive Enligt plan
- [x] Listan ska innehålla följande: Rubrik för driftstörningen, datum och klockslag när den uppdaterades, startdatum och klockslag för när den startade, startdatum och kockslag för beräknat klart (om detta saknas så står det Okänt)
- [x] Det ska vara möjligt att klicka på en driftstörning för att få fram mer information om den, det som visas då är mer text om driftstörningen samt när den skapades.

**Comment by fridabergentoft** [comment]
Länk till skiss: https://www.figma.com/file/QkTSfoJrMkchPdJo2Jj7zk3D/driftinfo?node-id=18%3A137
