### ISSUE TITLE
Ändringar i sidfoten

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#331]
# Beskrivning
Sidfoten ska se ut enligt nedan

Ordningen enligt bild, information enligt nedan
![IMG_0116.JPG](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/ec7c3e1b-3489-48cc-98ac-a841d06d628a)

Kontakta oss
Region Halland
Box 517
301 80 Halmstad
 
Telefon: 035 - 13 48 00
E-post: regionen@regionhalland.se
 
Fler kontaktvägar (http://stage-rh.regionhalland.se/om-region-halland/kontakt/)
Anmäl misstanke om jäv, mutor eller tjänstefel (http://stage-rh.regionhalland.se/om-region-halland/kontakt/anmal-misstanke-om-jav-mutor-eller-tjanstefel/)
 
 
Aktuellt
•	Nyhetsarkiv (http://stage-rh.regionhalland.se/nyheter/)
•	Pressrum (http://press.regionhalland.se/)
•	Region Halland i sociala medier (http://stage-rh.regionhalland.se/om-region-halland/kontakt/region-halland-i-sociala-medier/)
•	Anslagstavla (http://stage-rh.regionhalland.se/demokrati-och-politik/anslagstavla/)
•	Möten och handlingar (http://stage-rh.regionhalland.se/demokrati-och-politik/moten-och-handlingar/)
 
 
Om webbplatsen
Information om cookies (http://stage-rh.regionhalland.se/om-region-halland/om-webbplatsen/)
Behandling av personuppgifter (http://stage-rh.regionhalland.se/om-region-halland/dataskydd/)
 
 
Ämnesområden 
Utveckling och tillväxt http://stage-rh.regionhalland.se/utveckling-och-tillvaxt/
Hälsa och vård http://stage-rh.regionhalland.se/halsa-och-vard/
Kultur http://stage-rh.regionhalland.se/kultur/http://stage-rh.regionhalland.se/kultur/
Jobb och karriär http://stage-rh.regionhalland.se/jobb-och-karriar/
Våra skolor http://stage-rh.regionhalland.se/vara-skolor/
Demokrati och politik http://stage-rh.regionhalland.se/demokrati-och-politik/
Om Region Halland http://stage-rh.regionhalland.se/om-region-halland/
 
 
Andra webbplatser:
1177 https://www.1177.se/Halland
Vårdgivarwebben https://vardgivare.regionhalland.se/
Hallandstrafiken https://www.hallandstrafiken.se/
Visit Halland https://www.visithalland.com/
Teater Halland http://www.teaterhalland.nu/

**Comment by viktor-sarge** [comment]
Footern är klar och allt innehåll är inlagt och kollat. "Ämnesområden" genereras fortfarande automatiskt, men övrigt innehåll är hårdkodat.

**Comment by viktor-sarge** [comment]
Skickar till QA
