### ISSUE TITLE
Varbi integration - ändra till produktionsflöden

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#338]
# Beskrivning
HR är redo att börja testa Varbi integrationen så vi behöver koppla om till produktionsflödena på mallen för Varbi.

# Acceptanskriterier
- [ ] Hämta information från https://feeds.varbi.com/json/regionhalland/position/ istället
- [ ] Sidan ska inte vara nåbar utifrån, eller i alla fall inte sökbar

**Comment by JohannaOlin** [comment]
@RolandHyden Denna är gjord väl? Visst är det ovanstående feed du har använt. Vi får med tjänster som de har markerat som interna, men jag tror att felet ligger hos Varbi

**Comment by viktor-sarge** [comment]
Tror detta är fixat och versionshistoriken antyder att interna jobb är bortplockade. L
