### ISSUE TITLE
Peka om sida till Kulturprogrammen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#339]
# Beskrivning
Kulturprogrammen ska hittas i navigationen under Kulturens sidor. Vi behöver därför peka om en sida så att den leder till listningen av kulturprogrammen.

# Acceptanskriterier
- [x] Sidan http://stage-rh.regionhalland.se/kultur/kulturbarnunga/kulturprogram-for-barn-och-unga/ ska leda till sidan http://stage-rh.regionhalland.se/kulturprogram/
- [x] Rubriken på sidan ska vara Kulturprogram för barn och unga
- [x] Ovanför listningen ska följande text visas som ingress: "Förskola, skola och andra arrangörer kan köpa subventionerade kulturprogram för barn och unga 2-18 år, för skolföreställningar eller offentliga föreställningar i Halland."
- [x] Under ingresstexten ska följande länkar visas: 
"Så här bokar och redovisar du subventionerade kulturprogram för barn och unga"
http://stage-rh.regionhalland.se/kultur/kulturbarnunga/bokning-av-kulturprogram-for-barn-och-unga/
"Läs mer om regionala subventioner till kultur för barn och unga"
http://stage-rh.regionhalland.se/kultur/kulturbarnunga/regionala-subventioner-till-kultur-for-barn-och-unga/

**Comment by viktor-sarge** [comment]
Upplagt och testat på stage.
