### ISSUE TITLE
Ingresstext på sidan med Kulturarrangemang

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#340]
# Beskrivning
Vi behöver lägga till ingresstext på sidan som listar Kulturarrangemangen samt ändra rubriken. Så småningom behöver vi tänka till med visningen av sidan eftersom vi vill att den ska kunna användas för fler arrangemang, men vi gör nedanstående ändringar i alla fall. 

# Acceptanskriterier
- [x] Följande ingresstext "Region Halland gör många olika kulturarrangemang, ofta i samarbete med andra arrangörer. Välkommen till föreställningar, konserter, samtal och andra aktiviteter!" visas under rubriken på sidan http://stage-rh.regionhalland.se/kulturarrangemang/
- [x] Ändra rubriken på sidan till Kulturarrangemang.

**Comment by viktor-sarge** [comment]
Finns på stage.
