### ISSUE TITLE
Nya skisser för Analysförteckningen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#343]
# Beskrivning
Vi behöver uppdatera skisserna för Analysförteckningen så att de använder de nya komponenterna. Eftersom detta är lite akut så är det viktigt att vi inte skapar nya komponenter just nu. Utgår från de nuvarande skisserna samt den befintliga analysförteckningen för att se vilka fält som behövs. http://www.regionhalland.se/analys

# Acceptanskriterier
- [ ] Skissen ska visa hur Analysförteckningen ser ut i desktop, tablet och mobil
- [ ] Skissen ska visa startsidan för Analysförteckningen
- [ ] Skissen ska visa sökruta och filtreringsmöjligheter
- [ ] Skissen ska visa listning av analyser
- [ ] Skissen ska visa en fullpost på en analys

**Comment by fridabergentoft** [comment]
Vad tror ni om att presentera analysförteckningen på följande vis: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3044%3A1&viewport=474%2C356%2C0.151353&scaling=min-zoom
