### ISSUE TITLE
Sidmall för listning av lediga jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#347]
# Beskrivning
Vi behöver styla sidan som listar lediga jobb. Sidmallen heter Lediga jobb via Varbi

# Skiss
https://www.figma.com/proto/JdrL2M8xMFlwOFUstErPYmqg/regionhalland.se?node-id=967%3A360&scaling=min-zoom

# Acceptanskriterier
- [x] Sidan ska fungera i IE, Edge, Chrome och Safari
- [x] Sidan ska fungera på desktop, tablet och mobil
- [x] Sidan ska innehålla ingress och textfält
- [ ] Sidan ska innehålla sökfält och sökknapp
- [ ] Sidan ska innehålla dropdownlistor för yrkesområde, yrke/titel och ort
- [x] Sidan ska visa listningen av de aktuella jobben sorterade efter senast publicerad överst
- [x] Innehållet in listan ska vara som skissen
- [x] Alla aktuella annonser visas direkt i listan, dvs ingen paginering
- [ ] Under listan ska det finnas ett textfält där redaktören kan lägga in text och länkar
- [x] Sidan ska INTE visa när den är publicerad och/eller ändrad
- [x] Sidan ska ha vänsternavigering

**Comment by viktor-sarge** [comment]
Just nu tror jag "the content" visas överst eftersom de redan hade innehåll där. I förlängningen kan vi ändra så att vi visar ingressen överst istället och lägger "the content" underst om man fortfarande vill ha ett fält under annonserna för länkar etc.

**Comment by viktor-sarge** [comment]
Avvaktar med att lägga till QA tills vi byggt sorteringen i backend.

**Comment by JohannaOlin** [comment]
Det är ok att content visas ovanför listan, det som ligger där nu kommer att tas bort när Offentliga jobb stängs. Jag lägger nya kort på filtreringen och sök istället.
