### ISSUE TITLE
Populera droplistorna för lediga jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#348]
# Beskrivning
Vi ska hämta de lediga jobben från Varbi och i listningen ska användaren kunna filtrera på Yrkesområde, yrke/titel samt ort.

# Acceptanskriterier
- [ ] Om det går så vill vi att endast de alternativ som har minst ett ledigt jobb knutet till sig ska visas i listan
- [ ] Besökarna måste först filtrera på yrkesområde innan hen kan välja yrke/titel eftersom dessa är knutna till varandra.
- [ ] Det ska gå att kombinera urvalet på Yrkesområde (samt yrke/titel) och ort, dvs om jag har gjort val i alla så ser jag endast de annonser som träffas av alla urval

**Comment by viktor-sarge** [comment]
Vet vi säkert att "ort" bara har de sex olika kommunerna som val? Annars funkar det inte att hårdkoda de sex kommunerna som val när det t.ex. dyker upp jobb på naturbruksgymnasiet. Om det verkligen är ort och inte kommun så är det bättre att vi genererar listan dynamiskt även om det betyder att vi inte visar alla sex kommuner hela tiden.    Någon som vet @JohannaOlin   @RolandHyden

**Comment by JohannaOlin** [comment]
@regionhallandviktor I dagens lösning är det endast kommun som används, men jag har ställt frågan vidare för att vara på den säkra sidan.

**Comment by viktor-sarge** [comment]
Tack.

**Comment by viktor-sarge** [comment]
Har kikat på detta idag och jag vill hellre att vi bygger det i backend än gör hela funktionen beroende av javascript. Bättre vi postar till sidan så får vi automatiskt delbara URL:er till sökningarna också. Jag har resonerat med Roland och vi har en plan och kikar på det ihop så snart vi kan. Analysförteckninge går före dock.
