### ISSUE TITLE
Skapa sida för att presentera ett ledigt jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#349]
# Beskrivning
Vi hämtar de lediga jobben från Varbi, men tanken är att även själva tjänsten presenteras på regionhalland.se. Detta är den sida man kommer till när man klickar på en ledigt jobb på sidan som byggs i Issue 347

# Skiss
https://www.figma.com/proto/JdrL2M8xMFlwOFUstErPYmqg/regionhalland.se?node-id=975%3A1&scaling=min-zoom

# Acceptanskriterier
- [ ] Sidan ska fungera i IE, Edge, Safari och Chrome
- [ ] Sidan ska fungera för desktop, tablet och mobil
- [ ] Sidan ska innehålla knapp för att ansöka
- [ ] Sidan ska visa innehåll från respektive tjänst i Varbi
- [ ] Tomma rubriker ska inte visas på sidan

**Comment by JohannaOlin** [comment]
@regionhallandviktor Vi behöver lägga till rutan med info om t ex kontaktperson mm på tjänsten samt fälten med "Om oss" och "Till bemannings..."

**Comment by viktor-sarge** [comment]
Den här tror jag vi kan lägga i QA.
