### ISSUE TITLE
Analysförteckning - hämta innehåll från API

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#350]
# Beskrivning
Analysförteckningen flyttas till ett API som Linda bygger. Vi behöver hämta in detta så att vi kan presentera innehållet. I steg 1 kommer vi att bygga upp detta på nya regionhalland.se, men det ska inte vara sökbart där eller nåbart i strukturen där. Besökarna ska heller inte se att de är på regionhalland.se. 
I steg 2 kommer detta sedan att integreras med Vårdgivarwebben.

# Acceptanskriterier
- [x] Innehållet ska presenteras i en lista utifrån bokstav
- [x] Det ska vara möjligt att lista analyserna utifrån Specialitet
- [x] Det ska vara möjligt att lista samtliga analyser
- [x] Det ska gå att söka på en analys
- [x] Det ska gå att se respektive analys fullpost

**Comment by viktor-sarge** [comment]
Jag har kryssat i alla acceptanskriter utom möjligheten att söka på en analys. Kvar är också att hänvisningar skall visas ordentligt och att vi skall kunna bygga namnen utifrån de fält som krävs.
