### ISSUE TITLE
Analysförteckning - skapande av listningssida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#351]
# Beskrivning
Vi behöver skapa sidmallen som ska användas för listningen av Analysförteckningen. Denna ska till en början ligga på regionhalland.se, men helst med färgerna för Vårdgivarwebben eftersom den så småningom ska flytta dit

# Skisser
- [ ] Desktop: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3044%3A1&viewport=474%2C356%2C0.151353&scaling=min-zoom
- [ ] Tablet: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3044%3A520&viewport=474%2C356%2C0.151353&scaling=min-zoom
- [ ] Mobil: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3062%3A29353&viewport=474%2C356%2C0.151353&scaling=min-zoom

# Acceptanskriterier
- [x] Sidan ska fungera i IE, Edge, Chrome och Safari
- [x] Sidan ska fungera på dekstop, tablet och mobil
- [x] Sidan ska visa rubriken Analysförteckning
- [ ] Sidan ska visa ett ingressfält
- [x] Sidan ska visa en dropdownlista med Specialiteter
- [x] Sidan ska visa A-Ö filtrering
- [x] Användaren ska ha möjlighet att lista samtliga analyser
- [x] Listningen ska visa analyser från vald bokstav, varannan rad vit och varannan rad blå
- [x] Sidan ska INTE visa när den senaste ändrades eller publicerades

**Comment by viktor-sarge** [comment]
(Undrar om inte denna är färdig - stämmer av på kontoret när vi ses)

**Comment by JohannaOlin** [comment]
@regionhallandviktor 
Det går ju inte att testa den i mobil och tablet, men när jag minskar fönstret så funkar det till en viss gräns, men den bryter inte själva listningen utan där kapar den. Välj t ex bokstaven A ![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/d24f0b08-9ceb-4638-882d-e7d753b006c9)
Jag har heller inte testat i Safari, den måste över till test-www först
Jag kan inte kolla om det finns något ingressfält heller, men det är inte helt nödvändigt i första steget heller.

**Comment by JohannaOlin** [comment]
Jag stänger denna, la till den sista punkten på 445 istället.
