### ISSUE TITLE
Större caption på herobild 

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#358]
# Beskrivning
Herobilden används idag på kulturarrangemang och Kulturprogram. Caption som visas där är mycket mindre än den som är på skissen

# Acceptanskriterier
- [ ] Caption på en Hero-bild ska vara lika stor som på skissen

**Comment by viktor-sarge** [comment]
Har ringat in vad problemet var och fixar det i styleguiden. (De hade lagt rubriken i caption som en H5, men den skall inte vara rubrik alls så jag tar bort rubriken semantiskt och märker upp den stort rent grafiskt istället)

**Comment by viktor-sarge** [comment]
Actions för denna story 
- [x] Ta bort caption-hero-title och flytta reglerna till caption-hero
- [x] Knyt rubrikstorleken till h2-variabel och gör den responsiv
- [x] Ta bort felaktig h5-markup ur caption-hero
- [x] Gör om .hbs-filen för image-hero och inkludera caption-hero
- [x] Strukturera .scss för caption-hero i rätt ordning och gruppera reglerna
- [x] Strukturera .scss för image-hero i rätt ordning och gruppera reglerna
- [x] Öka upp versionsnumret på styleguiden
- [x] Kompilera en ny styleguide
- [x] Uppdatera productionbranchen på styleguiden och pusha så det syns på stilguide.regionhalland.se
- [x] Lägg in ny version av styleguiden i devbranchen för regionhalland.se
- [x] Uppdatera alla förekomster av hero-komponenten i regionhalland.se
- [x] Uppdatera dev-branchen på stage
- [x] För in ändringarna i master-branchen
- [x] Posta ändringar till release notes-listan för styleguiden
- [x] Posta ändringar till release notes-listan för regionhalland.se

**Comment by viktor-sarge** [comment]
Nu är allt fixat med denna. Men tror det kanske blev lite väl blaffigt. Åtminstone på min skärm :) Diskuterar när vi ses allihopa igen och tweakar på den då.

**Comment by viktor-sarge** [comment]
(rundade hörn är inte inlagt eftersom det inte är en del av storyn - tar det separat)

**Comment by viktor-sarge** [comment]
Behåller mig och lägger er Frida o Johanna på storyn i QA-spalten eftersom jag tror det är bra om vi tar en visuell avstämning här och tweakar lite live tills vi är nöjda. Men nu knyts den mot storleken på h2-rubriker så det blir mer konsekvent tvärsöver webbplatsen. Sedan kanske vi vill gå ner till h3-storlek istället men det kikar vi på

**Comment by JohannaOlin** [comment]
@fridabergentoft och @regionhallandviktor Jag håller med om att den blev väldigt blaffig, men det kanske är en vanesak?
