### ISSUE TITLE
Skisser på Vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#363]
# Beskrivning
Vi behöver ta fram skisser på Vårdgivarwebben med de nya komponenterna.

# Acceptanskriterier
- [x] En skiss på startsidan
- [x] En skiss på en sektionssida
- [x] En skiss på sektionssidan för Läkemedel
- [x] En skiss på en vanlig undersida till Läkemedel

**Comment by fridabergentoft** [comment]
Länk till desktop: https://www.figma.com/file/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3120%3A28158

Länk till tablet: https://www.figma.com/file/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=1349%3A211

Länk till mobile: https://www.figma.com/file/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=275%3A5601
