### ISSUE TITLE
Skiss på fasta puffar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#368]
# Beskrivning
Vi behöver ta fram skisser på de fasta puffarna som ligger på startsidan. Redaktionen vill att dessa ser annorlunda ut jämfört med de vanliga puffarna.

# Acceptanskriterier
- [x] Skissen ska visa hur puffen ser ut i desktop, tablet och mobil
- [x] Puffen ska innehålla en bild
- [x] Puffen ska innehålla text
- [x] Hela puffen ska vara klickbar

**Comment by fridabergentoft** [comment]
Länk till skiss: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2027%3A4335&viewport=-1998%2C2542%2C0.5354741215705872&scaling=min-zoom

**Comment by JohannaOlin** [comment]
@regionhallandviktor Tittar du på denna så att vi kan fixa komponenten sen?

**Comment by viktor-sarge** [comment]
Bakläxa. Inte semi-transparenta textplattor ovanpå bilder. Svårläst.

**Comment by fridabergentoft** [comment]
Nu är det åtgärdat: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2027%3A4335&viewport=-769%2C1444%2C0.3556930422782898&scaling=min-zoom

**Comment by JohannaOlin** [comment]
@regionhallandviktor Är denna ok nu?

**Comment by viktor-sarge** [comment]
Looking good, men länkarna behöver nog alltid vara understrukna, och särskilt om de är svarta.

**Comment by viktor-sarge** [comment]
(failed QA bara för att komma ihåg att ändra länkarna till understrukna, men tar max en minut)
