### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#374]
# Beskrivning
Det saknas en favicon på nya regionhalland.se

# Acceptanskriterier
- [ ] Lägg in loggan som favicon

**Comment by viktor-sarge** [comment]
Verkar som vi har rätt hänvisningar i head, men att filerna inte ligger där de skall. Kikar på det.

**Comment by viktor-sarge** [comment]
Favicons finns nu på stage, jag förbereder master branchen med samma.

**Comment by viktor-sarge** [comment]
Favicons finns nu och väntar på release 1.3.0 i även master-branchen på regionhalland.se
