### ISSUE TITLE
Sökknappen i mobilen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#376]
# Beskrivning
Förstoringsglaset är inte centrerat i sökknappen på mobilen och den ska vara grön. Gör den större också så att den i alla fall är lika stor som talande webb

# Acceptanskriterier
- [ ] Förstoringsglaset ska vara centrerat i sökknappen i mobilen
- [ ] Sökknappen ska vara grön
- [ ] Sökknappen ska vara lika stor som ikonen för Talande webb

**Comment by viktor-sarge** [comment]
Gör nog om huvudet helt och tar loggan också om jag hinner, den behöver bli mindre i mobilen. Behöver också göra en modifier för de runda knapparna typ --hollow eller liknande.

**Comment by viktor-sarge** [comment]
I högsta grad pågående. Har gjort en hel del jobb på detta och skall bara paketera det sista. Men behövde stämma av saker med Roland medan vi var på kontoret bägge två.

**Comment by viktor-sarge** [comment]
Den här är releasad men lägger den i QA så att du kan kika på att den blev rätt @JohannaOlin Lägg till baka om det är några ändringar.
