### ISSUE TITLE
Prototyp - Komponent för sidhuvud

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#38]
# Beskrivning
Vi behöver en komponent som ska användas som sidhuvud på webbplatser mm.

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska gå att förstora till 200 % utan att utseendet spricker
- [ ] Komponenten ska innehålla en logotyp
- [ ] Komponenten ska innehålla "sajtnamn"
- [ ] Komponenten ska innehålla topplänkar
- [ ] Komponenten ska klara av ett flertal topplänkar
- [ ] Komponenten ska innehålla sökruta

**Comment by viktor-sarge** [comment]
Färgen "Soluppgång" ger tillräcklig kontrast mot "Djupblå" för att fungera som active state. Man kunde vara mer generös för all del, men den får ändå godkänt. Däremot funderar jag lite mer över utseendet på hamburgerikonen i mobilläget: Den ljusgrå får underkänt med 1.27:1 emot vitt och tillåts inte ens för aktiva gränssnittskomponenter. För mig är dock kruxet lite ett annat. De ser ut som två helt olika ikoner. En blå med vita streck och en ljusgrå med ett kryss har inte en omedelbar samhörighet som olika states på samma knapp. Ljusgrått signalerar inte heller att något är aktivt och klickat för mig utan mer att det är inaktivt.

**Comment by viktor-sarge** [comment]
Frida och jag gick igenom idag och vi testar ett annat upplägg för hamburgerikonen på mobil. Tar bort "failed QA" och anser den passerad så kan du dra vidare om du är nöjd @JohannaOlin
