### ISSUE TITLE
Kulturarrangemangslista i mobilläget

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#382]
# Beskrivning
Listan med Kulturarrangemangen är väldigt smal i mobilen. Dels har varje kort en väldigt stor vänstermarginal, hänger säkert ihop med 372, dels har sidan dvs korten och ingressen för stor högermarginal, och dels är det väldigt mycket marginal till vänster i själva korten och ingen marginal till höger

# Acceptanskriterier
- [ ] Korten är för smala, de ska fylla nästan hela bredden i mobilen, se https://stilguide.regionhalland.se/components/detail/rh-event-card-calendar.html (observera att vi tagit bort kortet med datumet)
- [ ] Minska vänstermarginalen i själva korten

**Comment by viktor-sarge** [comment]
@nguyenkhois Var är bästa stället att kolla på koden/resultatet för den här? :)

**Comment by viktor-sarge** [comment]
Om det är https://stilguide.netlify.com/eventcalendarblock/ så ser det redan betydligt bättre ut :)

**Comment by JohannaOlin** [comment]
Stänger denna, den tas med i den allmänna genomgången av komponenterna
