### ISSUE TITLE
Herobilder skalar inte ner korrekt i mobil

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#383]
# Beskrivning
Herobilderna blir väldigt ihoptryckta i mobilen. Proportionerna verkar inte vara korrekta.

# Acceptanskriterier
- [ ] Herobilderna behåller sina proportioner när de skalar ner
- [ ] Captionrutan ska ligga nedanför herobilden i mobil
- [ ] Komponenten ska sedan läggas in på regionhalland.se, vuxhalland.se och musikhallandia

**Comment by viktor-sarge** [comment]
Jag har hittat boven. Det är reglerna för att bilderna på en sida skall skala korrekt som blandar sig i delar av reglerna för hero-komponenten. Eftersom det är en bild som ligger inuti "rh-article"-klassen. Det blir problem eftersom vi inte kan köra BEM 100% pga Wordpress. Men lösningen blir nog att prova om vi kan lägga hero-komponenten utanför article-klassen helt sonika.

**Comment by viktor-sarge** [comment]
Jag har kikat på koden och hero-komponenten ligger redan utanför rh-article. Den borde inte påverkas av de reglerna, men när jag inspekterar hur browsern applicerar reglerna så är det tydligt att koden för bilder inuti rh-article ändå appliceras på hero-bilderna. Frågan är nu varför. Så vitt jag kan se så är regeln i development.css korrekt skriven.

**Comment by viktor-sarge** [comment]
Ser ut som regeln hade fel syntax trots allt. Actions är då: 

- [x] Ändra syntaxen i dev-branchen för bildregeln i development.css 
- [x] Plocka upp ändringen på stage
- [ ] Verifiera att det är önskat beteende
- [ ] Gör ändringen även i masterbranchen på regionhalland.se
- [ ] Uppdatera test-servern
- [ ] Verifiera att det fortfarande fungerar
- [ ] Posta ändringen till release notes

**Comment by viktor-sarge** [comment]
@JohannaOlin Nu är detta ändrat på stage och det fungerar nu som avsett. Regeln som störde de som bright har definierat är trimmad. Jag skickar till QA och om du är nöjd så lägg tillbaka till mig så gör jag samma uppdatering i master-branchen så den är redo för att plockas upp i 1.3.0 av regionhalland.se

**Comment by JohannaOlin** [comment]
@regionhallandviktor När jag testar detta så kapas bilden nu istället, den går att skala ner en bit, men sen kapas den på bredden istället. 

![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/62ad23a9-00a8-47d5-b8aa-0b42054555ed)

**Comment by viktor-sarge** [comment]
(Värt att notera om du jobbar med den här Khoi - Herobilder skall få ett nytt beteende jämfört med nu. På mobil skall de behålla sina proportioner och en caption-platta skall visas under bilden istället för ovanpå den.)

**Comment by nguyenkhois** [comment]
Jag har pushat upp på ny branch och jag försöker ändra så lite som möjligt.
* Demo: https://stilguide.netlify.com/imagehero/
* Källkod: https://github.com/RegionHalland/styleguide/tree/khoile/hotfix-molecules-image-hero

Hör av er för feedback innan jag fortsätter skriva om två komponenterna `Atom/caption-hero` och `Molecules/image-hero`. Jobben kommer vara:
- [ ] Komponent strukturer _(bara HTML & SCSS)_
- [ ] Konfiguering för komponenterna med: `*.settings.scss` och `*.hbs` för återanvändning i annan komponent.
- [ ] Testning _(olika webbläsare på mobil, surfplatta, dator)_

**Comment by viktor-sarge** [comment]
@nguyenkhois Jag kollade demon och den funkar bra, men i mobilläget så har den inte den nya funktionen (se min kommentar 31 juli ovan). Jag har bett att @fridabergentoft uppdaterar i komponentbiblioteket så det finns snart en ny skiss i Figma att gå efter för just mobilläget.

**Comment by JohannaOlin** [comment]
Stänger denna, den tas med i den allmänna genomgången av komponenterna
