### ISSUE TITLE
Ny programtyp för kulturprogrammen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#384]
# Beskrivning
Vi behöver lägga in ytterligare en programtyp i Kulturprogrammen

# Acceptanskriterier
- [ ] Programtypen "Litteratur" finns som val på Kulturprogrammen

**Comment by RolandHyden** [comment]
Jag har lagt till Litteratur som programtyp.
När jag ändå höll på så sorterade jag även om de enskilda programmen o bokstavsordning.
För detta används version 2.1.0 av pluginen:

https://github.com/RegionHalland/region-halland-acf-page-kulturprogram

Resultatet är synligt på.

http://stage-rh.regionhalland.se/kulturprogram/

**Comment by JohannaOlin** [comment]
@RolandHyden Går det att lägga valen för programtyp i bokstavsordning (i adminläget), nu kommer Litteratur sist, eller är det då vi behöver gå in och manuellt tagga om alla befintliga?

**Comment by RolandHyden** [comment]
Hej @JohannaOlin Som tur var gick det att lägga programtyperna i bokstavsordning utan att behöva spara om allt. Blir då version 2.1.1 av pluginen. Finns uppladdat på stage. Jag la även i in litteratur på rätt plats på sidan som visar alla programmen.
