### ISSUE TITLE
Byt till scala sans på stage-rh

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#387]
# Beskrivning
Kommunikationsavdelningen vill se om det går att använda Scala sans på webbplatserna. När vi har uppfyllt acceptanskriterierna så kommer vi att lämna över detta till Kommunikationsavdelningen för koll, förutsatt att typsnittet är ok enligt tillgänglighet/användbarhet samt prestandamässigt. Sen är det upp till dem att kontrollera resten och komma med en åtgärdslista samt ett beslut på om det nya webbtypsnittet ska vara Scala sans.

# Acceptanskriterier
- [ ] Byt typsnitt till Scala sans på stage-rh
- [ ] Gå igenom och ändra storleken där det behövs för att det ska bli tillgängligt
- [ ] Mät prestandan

**Comment by JohannaOlin** [comment]
@regionhallandviktor Kan du göra rubrikerna på Navigationskorten lite större nu är de samma storlek som navigationstexten. Även rubriken för puffarna behöver ökas upp lite.

Ändra även storleken på Arial på test-rh så att vi har tre varianter att titta på

**Comment by viktor-sarge** [comment]
@JohannaOlin Skall vi ta bort Scala igen från stage eller låta det ligga kvar?

**Comment by JohannaOlin** [comment]
@regionhallandviktor Ta bort det igen tycker jag. Kontaktkorten fungerar nu på stage och vi skulle behöva låta intressenterna titta på dem och sen eventuellt ta med dem i nästa produktionssättning, men det ser ju lite konstigt ut med Scala sans i dem nu (storlekar).

**Comment by JohannaOlin** [comment]
@regionhallandviktor 

Jag stänger detta ärende så skapar jag ett nytt för det nya typsnittet istället.
