### ISSUE TITLE
Lägg in komponenterna på Vuxhalland

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#391]
# Beskrivning
Vuxhalland ska lanseras i slutet av maj och vi behöver lägga in de nya komponenterna på sajten enligt Fridas skisser, https://www.figma.com/proto/UcCKUeD0rOMIfw6vE81JxADM/vuxhalland---wireframe?node-id=85%3A1922&scaling=min-zoom

Vi behöver ta en diskussion kring hur sidorna läggs i strukturen för att få det som de önskar.

# Acceptanskriterier
- [x] Sidhuvudet ska vara utan logga och endast ha en text, länk till Talande webb och en knapp. Texten ska vara länkad till startsidan för sajten. Knappen ska vara länkad till en vanlig sida
- [ ] Startsidan ska ha en Herobild, Puffsektion med rubrik samt navigationskomponenten under puffarna. I denna navigation ska endast två av undersidorna visas
- [ ] Det ska finnas en mall som har Herobild, navigationskomponent om det finns undersidor samt puffsektion
- [ ] Det ska finnas en mall för en vanlig sida som kan ha en Herobild samt text
- [x] Det ska finnas en mall som listar utbildningarna
- [x] Sidfoten ska innehålla loggorna

**Comment by viktor-sarge** [comment]
Vuxhalland är nära nog klar. Det är färg på några pilar i styleguiden som skall fixas + en variant på hero-komponenten. Jag o Roland felsöker varför inte the_content visas på vanliga sidor, men sedan är det klart. Vi kan ta upp koden från master på stage/test och provköra med skarp data på måndag.

**Comment by viktor-sarge** [comment]
Nu är "det sista" justerat på vuxhalland. Det finns säkert någon detalj här och där, men nu är jag ok med att lämna ifrån mig. Så släcker vi buggar vartefter vi hittar.
