### ISSUE TITLE
Meta decription och Meta keyword

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#393]
# Beskrivning
Vi behöver lägga in denna information så att den kommer med när man t ex googlar. Martin kollar med Kommunikation vilken info som ska läggas in.

# Acceptanskriterier
- [ ] Metadescription ska vara "Region Halland arbetar för att erbjuda en god hälso- och sjukvård och främja en hållbar utveckling i regionen. Vår vision är att göra Halland till den bästa livsplatsen."

**Comment by viktor-sarge** [comment]
Description ligger i master branchen på regionhalland.se och inväntar release av regionhalland.se version 1.3.0

**Comment by JohannaOlin** [comment]
Denna är väl lite svår att kolla i test så jag lägger över den till Ready för release
