### ISSUE TITLE
Fel titel visas på fliken i webbläsaren

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#394]
# Beskrivning
På sidorna för Kulturarrangemangen och Kulturprogrammen visas fel titel på fliken. Den verkar hämta från ett arrangemang respektive program.

# Acceptanskriterier
- [ ] På sidan som som listan Kulturprogrammen så ska det stå "Kulturprogam - Region Halland"
- [ ] På sidan som listar Kulturarrangemangen så ska det stå "Kulturarrangemang - Region Halland"

**Comment by viktor-sarge** [comment]
@RolandHyden Den här pratar jag gärna med dig om en vända. Misstänker att det är archive/single som bråkar.

**Comment by viktor-sarge** [comment]
Tog hjälp av Roland och felet var att de sidorna inte har någon titel. Däremot så kan vi använda posttypens namn för att bygga en logik som fixar det. Roland har fixat koden så gör jag en commit strax.

**Comment by viktor-sarge** [comment]
Finns nu i både master och dev-branch. Jag uppdaterar på stage strax. Sedan väntar den på relase 1.3.0 av regionhalland.se.
