### ISSUE TITLE
Prenumerera och logga in på lediga jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#395]
# Beskrivning
Intressenterna vill göra det möjligt för besökarna att prenumerera på de lediga jobben. På intranätet har vi lagt in Varbi i en I-frame, https://intra.regionhalland.se/aktuellt/lediga-jobb/Sidor/default.aspx, och där kommer knappen med. Kan vi lägga in samma knapp (fast med vårt utseende så klart) på externa webben?
De vill även lägga in knappen för att logga in på Varbi

# Acceptanskriterier
- [ ] Som besökare kan jag klicka på en knapp och komma till Varbis prenumerationsformulär, https://regionhalland.varbi.com/se/what:subscribeform/backToJobs:1/?token=70117c353fde97237ec4b71a130d841b
- [ ] Som besökare kan jag klicka på en knapp för att komma till inloggningen på Varbi, https://regionhalland.varbi.com/se/what:login/

**Comment by viktor-sarge** [comment]
Inlagt på stage som knappar, men blir inte bra. Vi låter det vara så i dev en stund medan vi funderar på bästa sättet att lösa det. Länkar direkt i texten eller länkar i högerspalt vore tydligare.

**Comment by viktor-sarge** [comment]
Lägger till QA - bara skicka tillbaka med nya instruktioner när vi vet hur det skall ändras.

**Comment by JohannaOlin** [comment]
@fridabergentoft Vad tycker du, http://stage-rh.regionhalland.se/jobb-och-karriar/lediga-jobb/? 
Jag tyckte inte att det blev riktigt bra. Skulle hellre se att vi lägger detta i texten ovanför listan med en förklaring till vad som menas. Logga in förstår man ju inte direkt. Om vi lägger det i texten så är det ju en redaktionell ändring som redaktionen själva kan fixa. 

Det finns endast två tjänster kvar i den gamla tjänsten och bägge går ut denna vecka så efter det kan de ju ta bort den länken. Samtidigt så ska ju filtreringen in.

**Comment by JohannaOlin** [comment]
Vi låter denna ligga, dvs produktionssätter den inte. De får lägga in länkarna redaktionellt istället

**Comment by JohannaOlin** [comment]
@regionhallandviktor  ag pratade med HR om detta igår och de tyckte också att det var bättre med vanliga länkar i texten och skulle kontakta redaktionen om detta. Vi kan stänga ärendet, men vi kanske ska ta bort knapparna först från stage?
