### ISSUE TITLE
Filtrering på Lediga jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#396]
# Beskrivning
Vi behöver lägga in filtrering på Lediga jobb listan. Dels för yrkesområde + yrke/titel och dels för Kommun.

# Skisser
https://www.figma.com/proto/JdrL2M8xMFlwOFUstErPYmqg/regionhalland.se?node-id=967%3A360&scaling=min-zoom

# Acceptanskriterier
- [ ] Ovanför Lediga jobb listan ska en droplista för yrkesområde visas
- [ ] I droplistan för Yrkesområde ska endast de områden som har lediga tjänster visas
- [ ] Ovanför Lediga jobb listan ska en droplista för Yrke/titel visas
- [ ] Det ska endast gå att filtrera på Yrke/Titel om du har gjort en filtrering på Yrkesområde innan
- [ ] I droplistan för Yrke/Titel ska endast de yrken/titlar som har lediga tjänster visas
- [ ] Ovanför lediga jobb listan ska en droplista för Ort visas
- [ ] Droplistan för ort kan vara hårdkodad med följande alternativ, Falkenberg, Halmstad, Hylte, Kungsbacka, Laholm, Varberg
- [ ] När besökaren har gjort en filtrering så ska antalet tjänster som visas stå ovanför listan, se skiss.
- [ ] När besökaren har gjort en filtrering så ska listan ändra sig utifrån filtreringen.
- [ ] När besökaren har gjort en filtrering så ska det finnas ett alternativ att gå tillbaka till hela listan igen

**Comment by viktor-sarge** [comment]
Roland jobbar med denna och har kommit långt. Jag lägger i pågående.
