### ISSUE TITLE
Skisser på Handböcker på Vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#398]
# Beskrivning
När vi lägger över de nya komponenterna på Vårdgivarwebben så kommer de sk handböckerna också att förändras. I dagsläget har vi två handböcker på Vårdgivarwebben, Terapirekommendationerna och Avgiftshandboken. Vi behöver ta fram ett koncept på hur handböcker kan presenteras. Utgå från de tidigare skisserna på Terapirekommendationerna.

# Acceptanskriterier
- [x] Gör ett exempel till på startsida för Terapirekommendationerna fast utan navigationstexten på navigationskorten
- [x] Gör ett exempel på startsida för Avgiftshandboken, https://vardgivare.regionhalland.se/patientadministration/avgiftshandboken/. Denna ska även innehålla puffar
- [ ] Gör ett exempel på startsidan för Avgiftshandboken med Snabblänkar bredvid textfältet (som ligger ovanför navigationen)
- [ ] Gör ett exempel på startsidan för Terapirekommendationer med Snabblänkar bredvid fältet med sökrutan och texten.
- [ ] Gör ett exempel på A-Ö sida på denna sida https://vardgivare.regionhalland.se/patientadministration/avgiftshandboken/avgifter-oppen-vard-avgiftshandboken/. Lägg även in en möjlighet att visa dokument på denna sida 
- [ ] Gör ett exempel på A-Ö sida på denna sida https://vardgivare.regionhalland.se/patientadministration/avgiftshandboken/bosatta-i-utlandet-avgiftshandboken/hitta-bland-lander-a-o-avgiftshandboken/

**Comment by JohannaOlin** [comment]
Jag tycker att det ser bra ut, men det slog mig nu att vi nog måste lägga in Hitta på sidan också, den används en hel del på Terapirekommendationerna. Fixar du det @fridabergentoft? Sen har ju Terapirekommendationerna en hel del extra layout på sina sidor som vi måste ta hänsyn till när vi lägger in våra komponenter, men det kan vi titta på separat och speca ner vad som behöver tas fram.

**Comment by JohannaOlin** [comment]
@fridabergentoft Ska vi förresten göra ett förslag på startsidan utan snabblänkarna och flytta upp nyheterna dit istället? Eller kanske ta bort puffarna och lägga dit nyheterna? Snabblänkar och puffar känns lite som samma sak.

**Comment by JohannaOlin** [comment]
@fridabergentoft Är denna klar för Viktor att titta på?

**Comment by viktor-sarge** [comment]
Lämnat kommentarer på terapirek i Figma. Lite smått att kika på men inte några riktigt besvärliga saker på skiss-stadiet att fånga upp

**Comment by viktor-sarge** [comment]
@fridabergentoft Kan du se om det är någon av kommentarerna som du tycker kräver ändringar eller om vi bara lägger den här till färdiga. (Minns inte ens längre vad jag kommenterade nämligen :) )
