### ISSUE TITLE
Prototyp - Komponent för Topplänkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#40]
# Beskrivning
Vi behöver en komponent för topplänkar på webbplatserna. Topplänkarna är länkar som besökarna ska kunna nå oavsett var de befinner sig på webbplatsen.

# Acceptanskriterier
- [ ] Komponenten ska innehålla en ikon och en länk
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Visa hur topplänken ser ut när den är i fokus respektive ej i fokus
- [ ] Komponenten ska gå att förstora till 200% utan att utseendet spricker
- [ ] Prototypen ska visa hur det ser ut med 5 topplänkar

**Comment by viktor-sarge** [comment]
Värt att notera är att den ljusgröna mot vitt bara ger 1.46:1 i kontrast och alltså egentligen är godkänd. Å andra sidan så det det inte avgörande för funktionen att kunna se ikonens färgplatta så vi behöver inte nödvändigtvis göra något åt det. Men vill man vara petig så kan man isf ta t.ex. "Djupblå" eller "Skogsgrön" med vit ikon istället.
