### ISSUE TITLE
Ändring på 404-sidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#400]
# Beskrivning
Ansökningstiden till skolorna har nu gått ut så därför kan vi ta bort denna text från 404-sidan

# Acceptanskriterier
- [ ] Ta bort texten Ansökningsperiod skolor
Information och ansökan till naturbruksgymnasium och folkhögskolor (samt länken) från 404-sidan

**Comment by viktor-sarge** [comment]
Fixat. Ligger i master och väntar på release 1.3.0 av regionhalland.se
