### ISSUE TITLE
Ändra ingressen på Kulturkatalogen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#403]
# Beskrivning
På Kulturkatalogen, https://www.regionhalland.se/kulturprogram/, finns en inlagd ingress som behöver justeras.

# Acceptanskriterier
- [x] Lägg till en punkt efter "...offentliga föreställningar i Halland"
- [x] Lägg en blankrad innan länkarna
- [x] Lägg till texten "Priset som anges är det subventionerade priset exklusive moms."

**Comment by viktor-sarge** [comment]
Alla tre fixade och ligger i master-branchen på regionhalland.se och inväntar release 1.3.0

Priset anges nu i en egen paragraf efter den text om pris som hämtas ur databasen.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Ingressen verkar inte ha hängt med till produktion. Priset är ok däremot. Jag lägger tillbaka den till In progress

**Comment by viktor-sarge** [comment]
Dubbelkollat och ser ut som att commiten inte hann med in i releasen trots att den ligger med i tidslinjen före releasen. Bör av allt att döma komma med när vi släpper 1.4.0 imorgon.
