### ISSUE TITLE
Lägg till info i Cookie-notisen på vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#405]
# Beskrivning
Vi behöver lägga till lite text och en länk i cookie-notisen på Vårdgivarwebben.

# Acceptanskriterier
- [ ] Lägg in texten "Information om cookies" länkat till https://www.regionhalland.se/om-region-halland/om-webbplatsen/ i cookie-notisen

**Comment by viktor-sarge** [comment]
Fixat och driftsatt på vårdgivarwebben.
