### ISSUE TITLE
Ansök-knapp på Lediga jobb ska ligga längst ner också

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#408]
# Acceptanskriterier
- [ ] Knappen för att söka en tjänst ska även ligga längst ner när man är inne på ett ledigt jobb

**Comment by viktor-sarge** [comment]
Finns upplagd i master på regionhalland.se och inväntar release 1.3.0 av regionhalland. Jag kan testa det i stage också.

**Comment by viktor-sarge** [comment]
Den finns nu också på stage-servern
