### ISSUE TITLE
Skiss sidhuvud

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#409]
# Beskrivning
Sidhuvudet behöver tänkas om

# Acceptanskriterier
- [x] Logga
- [x] Sökknapp
- [x] Eventuellt Meny-knapp

**Comment by fridabergentoft** [comment]
Länk till skiss: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=80%3A157&viewport=460%2C424%2C0.5412787199020386&scaling=min-zoom

**Comment by fridabergentoft** [comment]
Var det så vi tänkte oss?

**Comment by JohannaOlin** [comment]
Jag tycker att det ser bra ut, men vi skulle behöva få in texten "Vårdgivare Halland" även i mobil.

**Comment by JohannaOlin** [comment]
Jag stänger denna och lägger till synpunkterna på Issue 468 istället. Gör om den till att gälla även komponenten Sidhuvud.
