### ISSUE TITLE
Lägg in komponenterna på driftsajten

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#410]
# Beskrivning
Vi behöver lägga in komponenterna på sajten för driftinformation så att det är rätt komponenter som används

# Skisser
- [ ] Desktop: https://www.figma.com/proto/QkTSfoJrMkchPdJo2Jj7zk3D/driftinfo?node-id=17%3A278&scaling=min-zoom
- [ ] Tablet: https://www.figma.com/proto/QkTSfoJrMkchPdJo2Jj7zk3D/driftinfo?node-id=18%3A1938&scaling=min-zoom
- [ ] Mobil: https://www.figma.com/proto/QkTSfoJrMkchPdJo2Jj7zk3D/driftinfo?node-id=18%3A1939&scaling=min-zoom

# Acceptanskriterier
- [ ] Se skisser för vilka komponenter som ska läggas in

**Comment by viktor-sarge** [comment]
Jobbat huvudsakligen med detta denna sprint. Börjar bli färdigt så smått, men att vi tog nya designbeslut försenade färdigställandet.

**Comment by JohannaOlin** [comment]
@regionhallandviktor  Vi förstår att du inte är färdig än så en del av detta kanske du håller på med redan, men här är Fridas och mina synpunkter
- [x] Listan känns för bred, den blir svårläst, jämför med skissen
- [x] Det är för många färger nu, ändra de mörkgröna till mörkblå istället (linjen vid pagineringen samt hoover vid pagineringen
- [x] Testa att lägga de övre tabbarna smalare
- [ ] I Fridas skiss hänger de undre tabbarna mer ihop med listan, det är lättare att se vilken flik man är på
- [x] Rubriken Driftinformation borde vara större, i alla fall lika stor som loggan
- [x] Vi vill kunna klicka på rubriken Driftinformation och komma till startsidan
- [x] Vi tycker att ordningen Pågående, Kommande, Avslutade är mer logiskt
- [ ] Lägg in favicon
- [x] Kan det stå "Driftinformation - Region Halland" på flikarna i webbläsaren (på alla sidor)?
- [x] Under flikarna Avslutade och Kommande behövs inga labels, där ska alla vara Avslutade respektive enligt plan
- [x] Beskrivningen ska vara ihopfälld default
- [x] I IE är loggan liten, flikarna (IT/telefoni etc) centrerade samt sidfoten i två-spalt
- [x] Ta bort Hallandstrafiken från listan med webbplatser i sidfoten
- [x] Måste kolumnrubrikerna vara med på varje kort, det ger ett lite rörigt intryck

**Comment by viktor-sarge** [comment]
Gröna avdelar är blå. 
Grönt i pagineringen behöver ändras i komponenten - fixar det. 
Testar att centera pagineringen. 
Visar bara pagineringen om det är mer än 1 sida

**Comment by viktor-sarge** [comment]
Ordningen på tabbarna för nivå 1 är fixad.

**Comment by viktor-sarge** [comment]
Titeln som visas i flikarna är ändrat till "Driftinformation - Region Halland"

**Comment by viktor-sarge** [comment]
Bredden på tabbarna justerad

**Comment by viktor-sarge** [comment]
(Tog ned rubriken i storlek på sidorna som hanterar inga driftstörningar. Och man får ett specifikt meddelande för respektive område att man vet att man är på rätt ställe)

**Comment by viktor-sarge** [comment]
Ändrat storleken på namnet för sajten + gett loggan lite mer luft i y-led.

**Comment by viktor-sarge** [comment]
Tagit bort hallandstrafiken från footern

**Comment by viktor-sarge** [comment]
Länkat sajtnamnet så det också leder till förstasidan.

**Comment by viktor-sarge** [comment]
Tightat till textboxen för själva beskrivningen lite så ser vi om det känns bättre. vill vi ha ihop hela sidan lite mer kan vi behöva lägga titel på en egen rad.

**Comment by viktor-sarge** [comment]
Jobbar med öppna/stänga-funktionen och har grunderna på plats. inte långt kvar till färdigt.

**Comment by viktor-sarge** [comment]
Rubrik måste inte vara med överallt, men eftersom de skall synas i mobilen på det sättet så fick de ligga så just nu. Sedan skall det bli en utility som döljer dem i tablet o desktop och visar en enda rad överst istället.

**Comment by viktor-sarge** [comment]
Beskrivningen är ihofälld per default och kan expanderas med toggle knapp. Lite finslipning på utseendet + byta pil när man klickar.

**Comment by viktor-sarge** [comment]
Toggle-knapparna är nu justerade visuellt.

**Comment by viktor-sarge** [comment]
Toggle-knapparna byter nu också pil när man klickar på dem.

**Comment by viktor-sarge** [comment]
Taggarna borttagna på flikarna "kommande" och "avslutade"

**Comment by viktor-sarge** [comment]
Kvar att göra torsdag: 
* Blå aktive state på paginering. (görs i styleguide, liten ändring för ett fulhack)
* Favicon. Lånar den från Region Halland. Ganska snabbt gjort.
* En "visa bara på tablet och desktop"-utility så att mobil kan ha rubriker i korten medan större viewports bara har en rubrikrad överst. 
* IE-buggarna. (loggans storlek, att flex inte stöds ordentligt för responsiv positionering av knapparna, sidfoten har troligen någon dum margin/padding)

**Comment by JohannaOlin** [comment]
@regionhallandviktor 
- Ändra så att siffrorna på flikarna är ljusblå också. 
- Jag lägger ett nytt kort på att rubrikerna inte ska visas på alla kort på desktop och tablett så att vi kommer ihåg det. Jag tror dessutom att vi ska se över vad som visas på korten i mobilen, kanske inte att all information behöver ses direkt där.

**Comment by viktor-sarge** [comment]
Liten logga i IE är fixad. (Bytte från svg till samma jpg som på regionhalland.se)

**Comment by viktor-sarge** [comment]
Tvåspalt för sidfot i IE är fixat.

**Comment by viktor-sarge** [comment]
(Knapparna som hade grå bakgrund i IE är nu fixade så de har avsett utseende)

**Comment by viktor-sarge** [comment]
Nu ligger buttongroup komponenten till vänster i desktop även i IE. Flexboxar är lite fläckvis implementerat i IE så justify-content:left fungerade inte utan är bytt till flex-start.

**Comment by viktor-sarge** [comment]
Aktiv tab syns för dåligt så nu är texten fetstilad i den aktiva taben.

**Comment by viktor-sarge** [comment]
Tagit bort understrykning på fokuserad knapp i buttongroup

**Comment by viktor-sarge** [comment]
Ändrat färgen på gul label till orange.

**Comment by viktor-sarge** [comment]
Hoverstate pagineringen är ändrat.

**Comment by viktor-sarge** [comment]
Jag har flyttat in uppdateringar till beskrivningsboxen, det kändes skumt att de låg utanför. 

Uppdaterat toggle-funktionen så att den ligger som en bar ovanpå kortet. Blev riktigt bra, men färgerna kan man jobba på.

**Comment by viktor-sarge** [comment]
Det enda som är kvar är att kolla varför faviconen inte laddar fast den finns som bildfiler nu + att lägga ut en rubrikrad som ersätter rubriker direkt på korten när man är på desktop.

**Comment by viktor-sarge** [comment]
Sedan är det mer städjobb som att använda det nya arbetsflödet i styleguiden för att kompilera ihop korrekta komponenter.

**Comment by viktor-sarge** [comment]
Sådär - nu är rubrikraden som bara skall synas i tablet och desktop implementerad. Layouten är också densamma när man skalar ned från desktop till tablet.
