### ISSUE TITLE
Skiss - rundade hörn på puffar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#412]
# Beskrivning
Vi har en önskan om lite "mjukare" puffar, dvs med rundade hörn. Vi har dessutom problem med puffarnas storlek nu där de på en sektionssida på regionhalland.se blir mindre än på startsidan. Detta behöver utredas så att vi har en puffkomponent som fungerar och ser bra ut i alla storlekar.

# Acceptanskriterier
- [ ] Skissen ska visa hur puffen ser ut på desktop, tablet och mobil
- [ ] Skissen bör också ta hänsyn till när sidan skalas så att puffen ser bra ut i alla lägen, både på höjden och på bredden

**Comment by fridabergentoft** [comment]
Länk till skiss: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2065%3A4374&viewport=-251%2C1286%2C0.1902312934398651&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Ok för mig

**Comment by JohannaOlin** [comment]
Stänger denna, review får ske på den byggda komponenten istället, läggs ihop med 302
