### ISSUE TITLE
Skiss - rundade hörn på vänsternavigationen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#413]
# Beskrivning
För att få ett mjukare intryck av komponenten så rundar vi hörnen på komponenten för vänsternavigering

# Acceptanskriterier
- [ ] Skissen ska visa hur komponenten ser ut i desktop, tablet och mobil

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=52%3A2&viewport=465%2C1820%2C0.5978204011917114&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Ser bra ut tycker jag, lägger över den till Viktor så får han säga sitt också.

**Comment by JohannaOlin** [comment]
Stänger denna och lägger ett nytt kort på att bygga komponenten och lägga in den på de webbplatser som använder vänstermeny idag.
