### ISSUE TITLE
Formatering av text från Varbi

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#418]
# Beskrivning
När redaktörerna har lagt in punktlistor i texten i Varbi så visas detta inte som en punktlista på regionhalland.se, se t ex https://www.regionhalland.se/jobb-och-karriar/lediga-jobb/lista-lediga-jobb/?id=267389

# Acceptanskriterier
- [ ] Den formatering som är inlagt i Varbi ska följa med och presenteras på samma sätt på regionhalland.se

**Comment by viktor-sarge** [comment]
Fixad i dev + master-branch. Finns att kolla på stage-rh. Om Roland uppdaterar test-www så kan vi kolla masterbranchen också. Lägger till QA

**Comment by viktor-sarge** [comment]
(Saknades en rh-article som behövs för att ge listor sina bullets)
