### ISSUE TITLE
Byt typsnitt på stage-rh

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#420]
# Beskrivning
Kommunikationsavdelningen vill se om det går att använda ett annat typsnitt på webbplatserna. När vi har uppfyllt acceptanskriterierna så kommer vi att lämna över detta till Kommunikationsavdelningen för koll, förutsatt att typsnittet är ok enligt tillgänglighet/användbarhet samt prestandamässigt. Sen är det upp till dem att kontrollera resten och komma med en åtgärdslista samt ett beslut på vilket typsnitt som vi ska köra vidare på.

# Kontaktperson
X
Kontakta X för att få info om vilket typsnitt samt hur det ska läggas in

# Acceptanskriterier
- [x] Byt typsnitt på stage-rh
- [ ] Kontrollera så att typsnittet uppfyller krav på tillgänglighet
- [ ] Gå igenom och ändra storleken där det behövs för att det ska bli tillgängligt
- [ ] Mät prestandan

**Comment by viktor-sarge** [comment]
Proxima-nova finns nu på stage.
