### ISSUE TITLE
Förändringar för driftstörningar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#423]
# Beskrivning
Vi har en del ändringar som måste göras för driftstörningarna innan vi kan lansera.

# Kontaktpersoner
Mona Nyman och Håkan Hansson

# Acceptanskriterier
- [x] Slå ihop områdena IT och Telefoni till valet IT/Telefoni
- [x] Ändra rubrik från Uppföljning till Uppdateringar
- [x] Gör det möjligt att ange ett datum och klockslag för uppdateringen
- [x] Gör det möjligt att lägga till flera uppdateringar med tillhörande datum/tid-fält
- [x] Flytta de avslutade som visas på startsidan (avslutade inom senaste 2 timmarna) till en egen rubrik längst ner
- [x] Lägg till ett fält för att ange kontaktperson på driftstörningen, detta ska dock inte visas mer än i backend
- [x] Lägg in versionshistorik på sidorna så att redaktörerna kan se vem som ändrat vilken version
- [x] De driftstörningar som är markerade med Akut ska visas som Akut på sajten, nu visas alla som Enligt plan
- [x] Beskrivningen och uppdateringarna ska inte visas förrän man fäller ner informationen
- [x] På sidan ska inte skapat datum och tid visas, däremot om driftstörningen är uppdaterad så ska det senaste datumet/tiden för uppdateringen visas. Detta ska inte hämtas från när "sidan" är uppdaterad utan från datumet som tillhör fältet Uppdateringar
- [x] Om området för driftstörningen är satt till IT/Telefoni så ska texten "Vid frågor kontakta Servicedesk 010-476 19 00" visas under beskrivningen
- [x] På startsidan ska alla driftstörningar som har startat och som är satta till Akut eller Enligt plan visas samt de som är satta till Avslutade inom de senaste 2 timmarna
- [x] På fliken Avslutad (samt de flikar som är Avslutade inom respektive område) ska alla driftstörningar som är satta som Avslutade visas
- [x] På fliken Kommande (samt de flikar som är Kommande inom respektive område) ska alla driftstörningar där starttiden ännu inte inträffat visas.
- [x] På flikarna för Kommande och Avslutade ska taggarna inte visas

**Comment by JohannaOlin** [comment]
@RolandHyden och @regionhallandviktor 
Tanken är att vi ska lansera driftinfosajten denna veckan. Jag tänker att det vore bra om vi kunde göra det på fredag, men att den inte länkas in förrän IT har lagt in sina befintliga driftstörningar.

Vad jag kan se så är mycket av de ovanstående punkterna klara och jag flyttar denna story till In progress, men följande verkar återstå samt de kommentarer Frida och jag la på story 410.
- [x] Flytta de avslutade som visas på startsidan (avslutade inom senaste 2 timmarna) till en egen rubrik längst ner - De är flyttade, men inte stylade som resten
- [x] Lägg till ett fält för att ange kontaktperson på driftstörningen, detta ska dock inte visas mer än i backend - Detta kan vara ett vanligt textfält till en början, med ledtexten "Kontaktperson". Det ska som sagt inte visas för besökarna.
- [x] De driftstörningar som är markerade med Akut ska visas som "Akut" och de som är markerade med Enligt plan ska visas som "Enligt plan" och de som är markerade med Avslutad ska visas som "Avslutad"
- [x] På flikarna för Kommande och Avslutade ska taggarna inte visas
- [x] Beskrivningen och uppdateringarna ska inte visas förrän man fäller ner informationen
- [x] Om området för driftstörningen är satt till IT/Telefoni så ska texten "Vid frågor kontakta Servicedesk 010-476 19 00" visas under beskrivningen
- [ ] Det är viktigt att tiden på sajten är rätt, nu går klockan 2 timmar fel och det ställer till det en hel del när det gäller denna sajt.

**Comment by viktor-sarge** [comment]
(De avslutade fixar jag - jag behövde bara bli färdig med mallen först och så kopierar jag över dem till avslutade-sektionen och ser till att det går mot rätt data som Roland redan lagt ut)

Fält för kontaktperson - Roland.

Labels - det är fel färger nu, men jag skall kolla om det är något fel på datat också. Färgerna fixar jag. 

Inga labels på kommande och avslutade - jag fixar med en if-sats. 

Ihopfällt som default är fixat. 

Området IT/Telefoni med särskild text. Bör jag lätt kunna fixa med en if-sats. 

Tiden på sajten - Möjligen Roland, men annars Oskar/David.

**Comment by viktor-sarge** [comment]
Taggarna borttagna på flikarna "kommande" och "avslutade"

**Comment by viktor-sarge** [comment]
Korrigerat labels innehåll och färg så att det fungerar. Verkar vara en bug i pluginet just nu, när vi har fixat det så kan vi flytta tillbaka logiken från blade-filerna till pluginet igen. Användarna märker hur eller hur ingen skillnad.

**Comment by viktor-sarge** [comment]
IT/tele har den angivna texten underst i sina beskrivningar nu.

**Comment by viktor-sarge** [comment]
Avslutade är nu korrekt stylade med likadana kort som övriga och ligger i en egen grupp längst ned.

**Comment by viktor-sarge** [comment]
(Roland diskuterar tidsbuggen med David/Oskar)

**Comment by viktor-sarge** [comment]
Roland har uppdaterat med ett fält för kontaktperson samt en anmärkning om att det inte visas externt.

**Comment by viktor-sarge** [comment]
Jag av-assignar mig från storyn då det bara är tidsbuggen kvar.

**Comment by RolandHyden** [comment]
Eftersom Oskar/David inte får ordning på tiden, dvs php-tiden är 2 timmar fel, så justerade jag i pluginen så att NU = NU + 2 timmar. Detta gör att det blir rätt just nu. Vi får dock inte glömma att justera pluginen när Oskar/David får rätt på php-tiden.
