### ISSUE TITLE
Justeringar på skisser för Musik Hallandia

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#424]
# Beskrivning
Skisserna för Musik Hallandia behöver justeras enligt önskemål från intressenterna.

**Comment by fridabergentoft** [comment]
Länk till prototype: https://www.figma.com/proto/FAbN8b1miI00Sfl3TtNWtVhX/MusikHallandia?node-id=14%3A196&viewport=-1492%2C321%2C0.16338373720645905&scaling=min-zoom

**Comment by JohannaOlin** [comment]
@regionhallandviktor Vi kanske kan stänga denna? Musikhallandia är ju byggt nu.
