### ISSUE TITLE
Ändring 404-sida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#427]
# Beskrivning
Redaktionen vill lägga till mer information på 404-sidan

# Acceptanskriterier
- [x] Lägg till texten "Kontaktuppgifter, öppettider och övrig information om vård- och tandvårdsmottagningar hittar du på www.1177.se/Halland/hitta-vard/." på sidan
- [x] Texten ska ligga överst på sidan, under rubriken

**Comment by viktor-sarge** [comment]
Fixat i dev + master-branch. Ändringen i dev syns på stage. Lägger till QA.
