### ISSUE TITLE
Justera komponenten Sidfot med loggor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#428]
# Beskrivning
Alla webbplatser behöver ha länkar till information om cookies samt hur vi behandlar personuppgifter tydligt synligt. Vi behöver därför göra om sidfoten som enbart innehåller loggor till att även innehålla dessa länkar.

# Acceptanskriterier
- [x] Visa på skiss hur länkarna "Information om cookies" samt "Behandling av personuppgifter" kan presenteras på desktop, tablet och mobil
- [ ] Komponenten "Sidfot med loggor" (RH Footer Logo) ska ändras i stilguide.regionhalland.se enligt skiss, https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=151%3A459&scaling=min-zoom.
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari
- [ ] Komponenten läggs in på vuxhalland.se
- [ ] Länken för Cookies ska gå till https://www.vuxhalland.se/om-oss/#cookies (ej skapad ännu)
- [ ] Länken för personuppgifter ska gå till https://www.regionhalland.se/om-region-halland/dataskydd/

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=151%3A459&scaling=min-zoom

**Comment by JohannaOlin** [comment]
@regionhallandviktor Är denna ok så att vi kan bygga om komponenten?

**Comment by JohannaOlin** [comment]
Jag lägger tillbaka den i sprintbackloggen så att vi bygger komponenten och lägger över den på vuxhalland.se också.

**Comment by JohannaOlin** [comment]
Flyttad till DevOps, 2484
