### ISSUE TITLE
Ta bort streck vid knappen Töm urval

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#432]
# Beskrivning
Vild knappen "Töm urval" vid filtreringen på Lediga jobb visas ett kort streck (inte i IE).

# Acceptanskriterier
- [ ] Ta bort strecket

**Comment by viktor-sarge** [comment]
Gjorde ändringar idag som borde få bort strecket. (Men paddingen som jag lade som ersättare verkade inte bita ordentligt. Skall kika igen på den)

**Comment by viktor-sarge** [comment]
Ser ut på både test-www och stage-rh som att strecket är borta. Lägger till QA så länge.

**Comment by JohannaOlin** [comment]
@regionhallandviktor På stage har jag fortfarande strecket i chrome, men det är borta på test.
