### ISSUE TITLE
Ändra filtreringsknapparna Lediga jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#434]
# Beskrivning
Filtreringsknapparna på Lediga jobb är blå, men resten av knapparna på sajten är gröna

# Acceptanskriterier
- [ ] Ändra knapparna så att de blir gröna

**Comment by viktor-sarge** [comment]
Fixat knapparna. Master och dev hade lite olika kod men ligger nu i bägge. Lägger till QA
