### ISSUE TITLE
Koppla på Google Analytics på Vuxhalland

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#435]
# Beskrivning
Vi behöver lägga in Vuxhalland i GA så att intressenterna kan se statistik

**Comment by viktor-sarge** [comment]
Vuxhalland har analytics. Inte uppladdat ännu men funkar även på stage.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Hur gör vi för att nå statistiken?

**Comment by viktor-sarge** [comment]
Jag har lagt in dig med full behörighet @JohannaOlin
