### ISSUE TITLE
Koppla på Google Analytics på Musik Hallandia

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#436]
# Beskrivning
Vi behöver lägga in Musik Hallandia i GA så att intressenterna kan se statistik

# Acceptanskriterier
- [x] Gör så att Musik Hallandia finns med bland webbplatser inne i GA
- [x] Ge Helena Nöjd behörighet att se statistik för Musik Hallandia

**Comment by viktor-sarge** [comment]
Jag har satt upp ett konto för MusikHallandia i Google analytics och lagt in spårningskoden i masterbranchen på repot så den kommer med så fort vi uppdaterar.

**Comment by viktor-sarge** [comment]
Helenas epost var inte registrerad för ett google-konto så jag kunde inte ge henne behörighet just nu. Jag tar kontakt med henne och ber att hon ger mig en adress med ett konto kopplat.

**Comment by viktor-sarge** [comment]
(Mailat Helena - inte fler actions jag kan göra på denna story men lämnar den i "pågående")

**Comment by viktor-sarge** [comment]
Helena fått access till sitt gmail-konto så lägger denna till QA
