### ISSUE TITLE
Sidor som delas på ex Facebook får felaktig beskrivning

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#437]
# Beskrivning
Om man delar en sida på ex Facebook så visas texten som vi har lagt in som Metadescription på sajten. Vi vill att sidans ingress/början på textfältet visas istället. Detta gäller egentligen alla sajter.

# Kontaktperson
Linda Tillander

# Acceptanskriterier
- [ ] När jag delar en sida på Facebook så ska ingressen för sidan visas.
- [ ] Om det inte finns någon ingress så ska början av textfältet visas.
- [ ] När det gäller startsidan för regionhalland.se så ska Metadescription visas
- [ ] För sidor som inte har något innehåll alls (varken ingress eller textfält), t ex https://www.regionhalland.se/jobb-och-karriar/lediga-jobb/lista-lediga-jobb/, så ska metadescription visas

**Comment by RolandHyden** [comment]
Jag har skapat en plugin för detta ändamål:

https://github.com/RegionHalland/region-halland-meta-data-region-halland

Denna plugin är uppladdad på test-www.regionhalland.se för QA.
