### ISSUE TITLE
Pagineringen på Lediga jobb fungerar inte

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#438]
# Beskrivning
Om jag klickar på en sida i pagineringen utan att ha gjort en filtrering först så får jag endast "I det urval du gjort finns det inga lediga jobb"

# Acceptanskriterier
- [x] Det ska gå att använda pagineringen utan att man har gjort en filtrering först
- [ ] När jag har gjort en filtrering och sen använder pagineringen så ska urvalet vara kvar

**Comment by RolandHyden** [comment]
Ok, nu fungerar pagineringen som tänkt. Detta är uppladdat på test.

https://www.regionhalland.se/jobb-och-karriar/lediga-jobb/
