### ISSUE TITLE
Sorteringen av lediga jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#439]
# Beskrivning
De lediga jobben sorteras inte i någon logisk ordning. Vi behöver fixa detta och intressenterna vill att de visas senast publicerad överst

# Acceptanskriterier
- [ ] De lediga jobben ska visas med senast publicerad överst
- [ ] Detta gäller även efter att besökaren har gjort en filtrering

**Comment by RolandHyden** [comment]
Detta är åtgärdat i och med version 1.5.0 av pluginen region-halland-varbi-works

https://github.com/RegionHalland/region-halland-varbi-works/releases

Vi kan ta med detta i nästa release av regionhalland
