### ISSUE TITLE
Cookienotisen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#443]
# Beskrivning
Cookie-notisen ser ut att gå utanför webbplatsens bredd, behöver ändras i själva komponenten och sedan läggas in på webbplatserna

# Acceptanskriterier
- [ ] Lägg notisen på två rader istället så att ikonen och knappen hamnar innanför webbplatsen
- [ ] Komponenten ska sedan läggas in på regionhalland.se
- [ ] Komponenten ska läggas in på musikhallandia.se

**Comment by viktor-sarge** [comment]
Ser den omarbetade cookie notice i styleguiden med separata settings. Snyggt jobbat @nguyenkhois! 

Jag tycker gott vi kan testa den i dev på regionhalland och musikhallandia om det inte redan är gjort. Jag lägger storyn till sprint backlog eftersom jag inte ser det som ett QA jobb längre tills dess att den finns att testa skarpt. (Förutser inte heller några problem)

**Comment by JohannaOlin** [comment]
Stänger denna, tas med i den allmänna genomgången av komponenterna
