### ISSUE TITLE
Justering av article-komponenten

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#446]
# Beskrivning
Vi behöver göra en del justeringar för article-komponenten. Dels så går inte att placera bilder till höger om/ till vänster om text. När man gör detta val så får det ingen effekt mer än inne i redigeringsläget. Dels behöver vi säkra upp att vi får en bra utskrift när besökaren väljer att skriva ut.

# Acceptanskriterier
- [ ] Valen man gör med bilden i admin ska återspeglas på visningen av sidan. Dvs om jag väljer att bilden ska visas till höger så ska den göra det även när jag tittar på sidan.
- [ ] Utskrift av sidan ska inte ta med sidhuvud, sidfot och vänstermeny eller hitta på sidan.
- [ ] Komponenten är uppdaterad i stilguiden
- [ ] Komponenten läggs in på regionhalland.se

**Comment by RolandHyden** [comment]
Detta beror på att det inte finns stöd för detta i styleguiden. Komponenten "article" har inget stöd alls för att placera ut bilder höger/vänster. Vi kan ju diskutera kring detta, dvs om komponenten "article" behöver byggas om

**Comment by JohannaOlin** [comment]
Justeras i och med Vårdgivarwebben, läggs in på rh.se efter det. Ligger i DevOps 2633
