### ISSUE TITLE
Ändring av komponent Hitta på sidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#453]
# Beskrivning
Vi funderade på om det går att rama in komponenten Hitta på sidan för att det ska bli tydligare

# Acceptanskriterier
- [x] Ta fram skiss på hur detta kan se ut på desktop, tablet och mobil

**Comment by fridabergentoft** [comment]
Jag har försökt med lite olika alternativ men kommer alltid tillbaka till samma sak. Att rama in hitta på sidan fungerar inte på vår webbplatser eftersom vi har en "kantig" vänsternavigering vilket inte passar ihop. Jag har försökt göra hitta på sidan tydligare och funderar på följande alternativ, vad tror ni om det?

Länk: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3563%3A3675&viewport=174%2C260%2C0.46457037329673767&scaling=min-zoom

**Comment by fridabergentoft** [comment]
Länk till komponenterna i komponentblioteket: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=150%3A133&viewport=-2543%2C-1751%2C0.5256571173667908&scaling=min-zoom

**Comment by viktor-sarge** [comment]
Värt ett försök! Tror jag kommenterade i figma innan jag såg det här att för återvändande användare så är det opraktiskt om den är ihopfälld per default om man använder den mycket. För sällan-användare är den däremot en rätt bra bonusfunktion för att orientera sig.
