### ISSUE TITLE
Ändringar för sidan som listar Lediga jobb

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#454]
# Beskrivning
Sidan som listar de lediga jobben ser lite tråkig ut, vi behöver fundera på ett annat utseende.
Det är inte klockrent med filtreringsfunktionen på Lediga jobb. Den fungerar funktionsmässigt, men det är inte så visuellt snygg. Intressenterna önskar att det grupperas ihop på ett snyggare sätt. De är väldigt förtjusta i vgrs lösning https://www.vgregion.se/jobba-i-vgr/sok-jobb-i-vgr/?IsPost=true

# Acceptanskriterier
- [x] Gruppera filtreringen
- [ ] Fundera på ett utseende där det fungerar med en enda Visa knapp
- [x] Ändra Töm urval till Rensa filter
- [x] Fundera på om det går att utnyttja bredden på sidan bättre eftersom det inte kommer att finnas någon Hitta på sidan
- [x] Ändra innehållet i träfflistekorten till att endast innehålla rubrik, ort och sista ansökningsdag. De vill tighta till listningen som att man ser fler tjänster åt gången.
- [x] Ta fram skiss på hur sidan ska se ut i desktop, tablet och mobil

**Comment by fridabergentoft** [comment]
Skulle vi kunna göra såhär istället? https://www.figma.com/file/JdrL2M8xMFlwOFUstErPYmqg/regionhalland.se?node-id=2054%3A847

**Comment by JohannaOlin** [comment]
Detta funkar, jag lägger ett nytt kort på att ändra detta på sidan sen när vi har fått ett ok angående omstrukturering av sidorna.
