### ISSUE TITLE
Komponent för att dela, kommentera mm information

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#455]
# Beskrivning
HR önskar möjlighet att dela lediga jobb och det finns ett intresse även från annat håll för dela-funktion. HR har tittat på VGRs lösning, se bild. 
![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/2ed24f2d-f797-4b76-ba78-31c58ee6f155)

Även Terapirekommendationerna har behov av dela-funktionalitet

Fundera på om det går att slå ihop detta med gilla-funktionalitet samt Kommentera/Lämna synpunkt

# Acceptanskriterier
- [x] Det ska finnas möjlighet att dela till Facebook, Instagram, Twitter och LinkedIn. Även att skicka via mail och skriv ut skulle kunna ligga med som ikoner/funktioner.
- [x] Om besökaren klickar på Kommentera så fälls ett fält ut. Lägg in en text om mailadress vid återkoppling samt gdpr.
- [x] Det ska finnas en möjlighet att gilla sidan, antalet gillningar ska visas
- [x] Ta fram skiss på hur komponenten ser ut i desktop, tablet, mobil 
- [ ] Komponenten finns i stilguiden för desktop, tablet och mobil
- [ ] Komponenten fungerar i IE, Edge, Safari och Chrome

**Comment by fridabergentoft** [comment]
Länk till komponenten: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2241%3A0&viewport=-3620%2C818%2C0.3815915882587433&scaling=min-zoom

https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2241%3A548&viewport=-3620%2C818%2C0.3815915882587433&scaling=min-zoom

https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2241%3A549&viewport=-3620%2C818%2C0.3815915882587433&scaling=min-zoom

https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2241%3A550&viewport=-3620%2C818%2C0.3815915882587433&scaling=min-zoom

**Comment by JohannaOlin** [comment]
@fridabergentoft 
När jag har gillat en sida så får jag upp info om att jag och x antal andra gillat sidan. Det ser ut som att denna info är länkad, vart kommer man om man klickar?
Sen är det frågan om det ska stå Kommentera eller Ge feedback (eller något annat), men det kanske vi inte behöver bestämma nu.

En petitess, e-postadressen är inte obligatorisk för feedbacken. Det räcker att vi ha en * vid obligatorisk uppgift, den kan vara samma för alla fält tänker jag.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Du behöver också titta på denna innan vi ger Khoi uppdraget att bygga komponenten.
