### ISSUE TITLE
Dropplistor för filtrering - icke-val

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#456]
# Beskrivning
På listningen av lediga jobb så har vi tre dropplistor. Om jag som besökare gör en filtrering i alla tre listorna, men sen endast vill ta bort en av mina filtreringar så går inte det idag utan jag måste tömma hela urvalet och sedan börja om.

# Acceptanskriterier
- [ ] Som besökare kan jag enkelt rensa valet i endast en droplista genom att välja valet "Välj..."

**Comment by RolandHyden** [comment]
Detta är fixat och uppladdat på test-www.regionhalland.se för QA

https://test-www.regionhalland.se/jobb-och-karriar/lediga-jobb/lista-lediga-jobb/
