### ISSUE TITLE
Komponent för huvudmeny

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#46]
# Beskrivning
Vi behöver koda en komponent för huvudmenyn som ska användas på våra webbplatser enligt Fridas skisser. Komponenten ska användas på Musik Hallandia.

# Skiss
- [ ] Desktop -
- [ ] Tablet -
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Huvudmenyn ska visas enligt skisser
- [ ] Om antalet ingångar i huvudmenyn är för många så ska denna visas på två rader

**Comment by viktor-sarge** [comment]
Snabb visuell QA med Frida: 
* Är den tidigare huvudmenyn som är byggd. Behöver uppdateras till rätt utseende.

**Comment by fridabergentoft** [comment]
Länk till komponent desktop: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=211%3A0&viewport=361%2C185%2C0.459788&scaling=min-zoom

Länk till komponent tablet: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=269%3A56&viewport=-1410%2C1021%2C0.638343&scaling=min-zoom

Länk till komponent mobile: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=62%3A0&viewport=-1410%2C1021%2C0.638343&scaling=min-zoom

Hur delarna ser ut tillsammans för tablet och mobile kan du se här: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=40%3A84&viewport=257%2C-59%2C0.67808&scaling=min-zoom

**Comment by brightjennie** [comment]
Jag har lagt alla versioner i samma vy. Jag har inte tagit hänsyn till brytpunkter mellan desktop-meny och mobil-meny. Det antar jag att ni löser sen :)

Den heter Main Nav.

**Comment by viktor-sarge** [comment]
Jag lämnar det visuella till @fridabergentoft . Jag tycker markupen ser smidig ut och skall kika ett varv till på CSSen, men tror inte det är några stora saker där. Däremot slår det mig att man nog vill kunna tabba till "knapparna" med pil som ligger i menyn. Tror ni det är snabbt gjort? Skickar tillbaka den för en bedömning av det.
