### ISSUE TITLE
Möjligt att ha samma rubrik mer än en gång i Hitta på sidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#460]
# Beskrivning
I Terapirekommendationerna har man ibland använt samma rubrik mer än en gång på en sida. Detta har ställt till det i Hitta på sidan som då inte visar rubriken på bägge ställen. Detta är inget problem på vårdgivarwebben idag, men vi måste verifiera att det fungerar när vi lägger in komponenten på Terapirekommendationerna.

# Acceptanskriterier
- [ ] Som redaktör kan jag använda samma rubrik mer än en gång på en sida
- [ ] Som besökare ser jag alla rubriker i Hitta på sidan

**Comment by viktor-sarge** [comment]
Har också tänkt på detta. Problemet är att det idag skapas ID som utgår från att rubrikerna är unika ID = "detta-ar-min-rubrik" ungefär. Men det är nog ganska snabbt gjort att lägga till ett uniqueid

**Comment by RolandHyden** [comment]
Hej på er.
Jag har fixat detta genom att lägga på ett löpnummer efter slugen, dvs det ser ut enligt:

mitt-exempel-1
mitt-exempel-2
ett-annat-exempel-3
osv.

Tack var löpnumret så blir alla slugar unika oavsett om det redan finns eller inte

Version 1.2.0
https://github.com/RegionHalland/region-halland-prepare-the-content

Version 2.0.0
https://github.com/RegionHalland/region-halland-find-on-page

**Comment by viktor-sarge** [comment]
@RolandHyden Gött! Kör någon av sajterna den nya koden? Om vi har det på typ test eller stage kan vi ju snabbt verifiera att det funkar och släcka den. (Har svårt att tänka mig att löpnummer inte skulle lösa problemet, men får väl ändå dubbelkolla)

**Comment by RolandHyden** [comment]
Tjena. Jod, vi kör koden på regionhalland.se och det funkar fint :)

**Comment by viktor-sarge** [comment]
+1 på det :) Bryr vi oss om att flytta de gamla här på zenhub till closed @JohannaOlin ?

**Comment by JohannaOlin** [comment]
@regionhallandviktor Ja, vi stänger dem, så ser vi sen när allt är tomt :)
