### ISSUE TITLE
Ljusa upp komponenten för Viktigt meddelande

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#462]
# Beskrivning
Komponenten för Viktigt meddelande är lite för mörk.

# Acceptanskriterier
- [ ] Ljusa upp komponenten så att den stämmer överens med Fridas skisser, https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=126%3A0&scaling=min-zoom
- [ ] Komponenten är uppdaterad i stilguiden
- [ ] Lägg in den nya komponenten på regionhalland.se

**Comment by viktor-sarge** [comment]
Såg ändringar från cleanup tidigare i somras, men är färgen ändrad? :) Finns den på någon av test-sajterna att kolla på? @nguyenkhois

**Comment by JohannaOlin** [comment]
Stänger denna, den tas med i den allmänna genomgången av komponenterna
