### ISSUE TITLE
Skisser för design.regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#465]
# Beskrivning
Vi ska lyfta in design.regionhalland.se i vår miljö och med våra komponenter. Sajten har idag lite konstig navigering på första sidan så vi behöver tänka till vad det gäller navigeringen också. Det som ligger på första sidan nu borde vara en ingång i huvudmenyn.

# Acceptanskriterier
- [ ] Ta fram skisser på startsidan, sektionssida samt vanlig sida
- [ ] Ta fram skisser som visar hur dessa ser ut i desktop, tablet och mobil

**Comment by fridabergentoft** [comment]
Länk till desktop: https://www.figma.com/proto/agkpIHLpRndMruDGxlioIsOt/Design.regionhalland.se?node-id=66%3A0&viewport=356%2C185%2C0.10684002190828323&scaling=min-zoom

Länk till tablet: https://www.figma.com/proto/agkpIHLpRndMruDGxlioIsOt/Design.regionhalland.se?node-id=28%3A1239&viewport=394%2C553%2C0.08872002363204956&scaling=min-zoom

Länk till mobil: https://www.figma.com/proto/agkpIHLpRndMruDGxlioIsOt/Design.regionhalland.se?node-id=52%3A13&viewport=644%2C559%2C0.09318958967924118&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Ser ok ut för min del. @regionhallandviktor tittar du på denna så att vi kan planera in utvecklingen av den.

**Comment by viktor-sarge** [comment]
* Dra upp storleken på klickmål från 30x30 till 44x44 om vi skall använda länkade ikoner. 
* Vi tar antagligen bort "Bidra på github" pga att funktionen försvinner. 
* Ikonerna till andra sajter byts från uppåt till extern länk. 

I övrigt inga ändringar.
