### ISSUE TITLE
Ändra komponenten Tillbaka-länk

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#467]
# Beskrivning
Tillbaka-komponenten visar en tillbaka-pil (pil åt vänster), men för att vara tydlig så behöver vi ändra denna till en uppåt-pil eftersom det är upp en nivå man kommer

# Acceptanskriterier
- [x] Komponenten ska använda en uppåt-pil

**Comment by fridabergentoft** [comment]
Min del av uppgiften är nu klar: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=40%3A0&viewport=1241%2C4874%2C1.5281054973602295&scaling=min-zoom

**Comment by JohannaOlin** [comment]
Ser bra ut för min del. Tittar du på den @regionhallandviktor så att vi kan lägga den till Khoi sen?

**Comment by viktor-sarge** [comment]
Jag har inga synpunkter på ändringen med ikonen, det blir bra. Bra att veta är att komponenten som ligger i styleguiden idag är gammal. Ser ut såhär:

```
<div class="rh-label-previous">
    <span class="rh-label-previous-icon"></span>
    <p class="rh-label-previous-title">
        Link to previous page
    </p>
</div>
```

Jag har nu börjat använda round-button atomen + rh-link--navigation istället. (Så att vi inte definierar en rund knapp direkt i molekylen utan återanvänder atomer). För närvarande kan det se ut tex såhär: 

```
<div class="mb2">
    <a href="../" class="rh-round-button rh-round-button--small icon-arrow-left"></a>
    <strong>
        <a href="../" class="h3 rh-link--navigation">
            Tillbaka till föregående sida
         </a>
     </strong>
</div>
```
Det enda som egentligen hör till själva molekylen rh-label-previous är isf "mb2". Eventuella paddings och margins man vill ha på molekylen blir då settings medan huvuddelen av jobbet görs av atomerna.

**Comment by viktor-sarge** [comment]
Jag är färdig med min bit och av-assignar mig och lägger på Khoi och i sprint backlog enligt ovan.

**Comment by JohannaOlin** [comment]
Flyttad till Devops 2633
