### ISSUE TITLE
Mobile-first-navigering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#468]
# Beskrivning
Navigeringen i mobilen är inte klockren. Vi behöver göra det möjligt för användarna att nå undersidorna på ett enkelt sätt utan att behöva klicka sig fram. Se ex hur Upplands Väsby har gjort det. Detta kort handlar bara om skissandet och byggandet av komponenten samt ändring av sidhuvudet, jag lägger nya kort på när det ska läggas in på sajterna.

När det gäller sidhuvudet så kan du utgå från https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=80%3A157&viewport=460%2C424%2C0.5412787199020386&scaling=min-zoom

Komponenten behöver läggas in på musikhallandia innan lanseringen 19/8, story för detta finns i DevOps.

# Acceptanskriterier
- [x] Ta fram skiss på hur menyn ser ut i mobil, men också tablet och desktop
- [x] Skissen ska även visa placeringen i sidhuvudet
- [x] Som användare kan jag nå huvudmenyn från vilken sida jag än står på
- [x] När jag som användare öppnar menyn så är aktuell sida markerad
- [x] Som användare kan jag klicka mig ner i menyn utan att behöva byta sida
- [ ] Den färdiga komponenten ska ligga i stilguide.regionhalland.se
- [ ] Komponenten för sidhuvudet justeras i stilguide.regionhalland.se

**Comment by fridabergentoft** [comment]
Länk till komponenterna: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=2482%3A0&viewport=465%2C480%2C0.09601137042045593&scaling=min-zoom

Länk till exempel på desktop: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=4193%3A463&viewport=692%2C426%2C0.028965642675757408&scaling=min-zoom

Länk till exempel på tablet: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3349%3A367&viewport=406%2C-1794%2C0.41464680433273315&scaling=scale-down

Länk till exempel på mobil: https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=3356%3A276&viewport=641%2C-1140%2C0.056659843772649765&scaling=scale-down
