### ISSUE TITLE
Komponent för sekundär navigation

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#47]
# Beskrivning
De sidor som ligger på nivå två (dvs direkt under startsidan) samt de sidor som är startsidor för områden, section page (ex Läkemedel) ska ha en speciell navigationskomponent. De ska med andra ord inte ha någon vänsternavigation. Genom denna komponent når besökarna de sidor som ligger under aktuell sida. Besökarna kan också få en beskrivning om respektive undersida.

# Skisser
- [ ] Desktop - 
- [ ] Tablet -
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera i Desktop, Tablet och Mobil
- [ ] Komponenten ska visa rubrikerna på barnen till aktuell sida
- [ ] Komponenten ska visa ett utdrag ur den text redaktörerna skriver in på barnen
- [ ] Barnens rubriker ska vara länkade i komponenten och leda till respektive barn

**Comment by viktor-sarge** [comment]
Visuellt QA: 

* Ikonen täcker rubriker + text på rad två i vissa lägen. 
* Texten i rutan skall inte vara understruken
* Active state är inte i linje med det Frida ritat. 
* Röd färg (felaktigt)  på understrykning och ikon på stage-vg.regionhalland.se idag

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=54%3A11&viewport=-397%2C994%2C0.570615&scaling=min-zoom

**Comment by brightjennie** [comment]
Jag la en max-width på diven för annars flyter pilen i väg till andra sidan och det ser inte så snyggt ut. :)

**Comment by viktor-sarge** [comment]
Ser bra ut. Jag lägger den som färdig tills vidare :)
