### ISSUE TITLE
Tillgänglighetskontroll för regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#470]
# Beskrivning
Vi behöver gå igenom regionhalland.se inför webbtillgänglighetsdirektivet 23/9.

# Acceptanskriterier
- [ ] Speca ner en lista uppdelad på vad som måste fixas samt vad som bör fixas

**Comment by viktor-sarge** [comment]
Jag har påbörjat denna story.

- [x] Jump to content fungerar (lagt till `<main id="main">` överallt där det saknades i mallarna.

- [x] Aria labels på footern

**Förstasidan** 
- [x] Koppla runda knappar som är länkar till det element som innehåller länktexten med aria-labelledby. I nuläget saknar länkade runda knappar en länktext. 

- [x] Alt-text på bilder. Kan vi hämta ut bildobjektet med beskrivning osv från wordpress istället för URL:en. Gäller särskilt tex puffar på förstasidan. 

- [x] Den vita texten "Sök" har inte tillräcklig kontrast mot grönt om man räknar det som text och inte ett grafiskt element/gränssnittsdel. Eftersom webperf använder Axe som klagar här kan det vara klokt att ändra. 

- [x] H1 saknas på förstasidan. (Vi kan nog göra puffarna till strukturella h1:or åtminstone)

- [x] Allt innehåll skall ligga inuti en landmark/semantisk html5-tagg. Det är inte kopplat till en specifik riktlinje i WCAG utan en best practice-faktor men Axe som webperf använder klagar så klokt att fixa det. 

- [x] Anpassa jump to content så att Axe förstår den? Den är korrekt för användarna idag, men det verkar inte som att Axe-verktyget som webperf förväntar sig en specifk namngivning. Å andra sidan används även Pa11y och jag är inte säker på hur det verktyget vill att det skall se ut. 

- [x] Aria label på puffar som berättar vad det är man hamnat på behövs

**Undersidor nivå 2**

- [x] Publiceringsdatum för nyheter har för låg kontrast

- [x] Alt-text på bilder saknas även här. 

- [x] Nyheter har tomma `<a>` taggar efter `<li>` elementet som inte validerar och Axe klagar på

- [x] Felaktig nästling av rubriknivåer vilket Axe klagar på. Ex. våra skolor där puffar har h3. 

- [x] Allt skall ligga i landmärken

**Page-sidor**

- [x] Vänsternavigationen länkar hela li-elementet vilket axe klagar på då det inte är korrekt. Gjorde så för att få hela ytan skulle bli klickbar. Vi får hitta en annan lösning. 

- [x] Felaktig nästling av rubriknivåer vilket Axe klagar på

- [x] Allt skall ligga i landmärken



**Ändringar i styleguiden** 

- [ ] Den gröna färgen på regionhalland.se skall vara den lite mörkare #34872d istället för att ge tillräcklig kontrast. (Gäller t.ex. knappar, men även andra element för konsekvensens skull - ändra i settings)

- [ ] A till Ö-komponenten behöver bättre kontrast på bokstäver. Prova t.ex. #595959 på alfabetet (ger AAA)

- [ ]  A till Ö behöver bättre hoverstate. Vita bokstäver.

- [ ] Focus-state behöver fixas på alla komponenterna som man kan tabba till

**Comment by viktor-sarge** [comment]
Hittat felet med tomma <a>-taggar efter li. Det var stängningstaggen som inte var ok. Fixat och pushat till master.

**Comment by viktor-sarge** [comment]
Stylat om kontrasten för publiceringsdatumet direkt i mallen. Vi tar in det i styleguiden sedan när vi går igenom komponenterna. Pushat till master

**Comment by viktor-sarge** [comment]
Har gått igenom section landing (nivå 2) och fixat så allt ligger i landmärken. Pushat till master.

**Comment by viktor-sarge** [comment]
Jag kör Axe och Pa11y kontinuerligt eftersom det är det som Webperf använder. Utöver det behöver vi såklart köra en del manuella tester också. Kul att de tar med yellowlab tools, dataskydd.net m.fl. Bra fusklapp finns på https://webperf.se/site/regionhalland_se/

**Comment by viktor-sarge** [comment]
Rubriknivåer: 
* Puffar på förstasidan är nu `<h1 class="h3"> `för att funka både visuellt och strukturellt. 
* Puffar på nivå två är nu `<h2 class="h3"> `av samma anledning. 
(pushat till master)

**Comment by viktor-sarge** [comment]
Jag släckte anmärkningen om att anpassa jump to content. Sedan jag fixade så den fungerar överallt så klagar Axe faktiskt inte längre. Verkar som den är smart nog att förstå även annan uppmärkning än sin egen favorit.

**Comment by viktor-sarge** [comment]
(Allt ligger i landmärken även på förstasidan, släckt den med)

**Comment by viktor-sarge** [comment]
Vänsternavigationen fixad. Pushat till master.

**Comment by viktor-sarge** [comment]
Rubriknivåer på page-sidor ok. Vi lägger ut topnivån fr content som h1 och sedan hänger det på redaktörerna att få strukturen rätt.

**Comment by viktor-sarge** [comment]
Jag har lagt knutit alla listor till sin rubrik i footern. Pushat till master.

**Comment by viktor-sarge** [comment]
Har fixat aria label på puffar. Pushat till master.

**Comment by viktor-sarge** [comment]
Jag lade ett title-attribut på round button länken för talande webb så att den är förståelig när man lyssnar på sidan. Pushat till master.

**Comment by viktor-sarge** [comment]
Gav sökknappen tillräckligt kontrast för att hålla Axe och Ka11y nöjda. Liten aning mörkare grön, men inte märkbart. Pushat till master.

**Comment by viktor-sarge** [comment]
Har labbat lite med att migrera regionhalland.se till styleguie 5.0.0 i en egen branch. 

Det finns en del valideringsfrågor för html och css som inte påverkar rankningen för just tillgänglighet i webperf men väl andra betyg. Samma sak med antal nätverksrequests, storlekar osv. Det är nog bra om vi ser över även dessa.

**Comment by viktor-sarge** [comment]
När det gäller bilderna hade det varit bra att stämma av med Roland eftersom jag har för mig att han ändrade i backend på musikhallandia, men jag skall se om jag kan kolla vad han gjorde där. För vi vill nog hellre ha ut objektet än bara url:en eftersom vi vill ha med alt-texten.

**Comment by viktor-sarge** [comment]
Hittade alt-texterna tillgängliga i blurbspluginets API. Fixat och pushat till master.

**Comment by viktor-sarge** [comment]
Fixat cookie-notisens knapp och "visa fler nyheter" som också har en rh-button--secondary som var för dålig kontrast.

**Comment by viktor-sarge** [comment]
Fixade en bugg där det skapades en överflödig ul som gav en vit sektion om man inte knutit några puffar till en sektionssida. Var kontrollen isset som var fel för det här caset.

**Comment by viktor-sarge** [comment]
Både axe och Koa11y är nöjda och glada på ett antal sidor jag kollar igenom. Tror att vi kan lägga den här till QA i väntan på att vi pushar till produktionsservrarna och kontrollerar på live-servern. Det vi behöver göra är också att kolla igenom att det faktiskt ligger alt-texter på alla bilder från redaktörernas sida.

**Comment by viktor-sarge** [comment]
Lägger över den här på er @RolandHyden och @JohannaOlin för uppdatering av master på server och sedan koll om allt är grönt.

**Comment by viktor-sarge** [comment]
Focus-states behöver fortfarande arbetas igenom så att man ser var man är när man tabbar, men det hör mer till styleguiden än den enskilda webbplatsen.
