### ISSUE TITLE
Tillgänglighetskoll på Vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#471]
# Beskrivning
Vi behöver gå igenom vårdgivarwebben inför webbtillgänglighetsdirektivet 23/9. Detta ska göras efter att vi har flyttat den och lagt in de nya komponenterna.

# Acceptanskriterier
- [ ] Speca ner en lista uppdelad på vad som måste fixas samt vad som bör fixas

**Comment by viktor-sarge** [comment]
(Avvaktar med den här tills vi har något konkret att jobba med. Men eftersom Roland har utgått från regionhalland.se så tror jag att det i mångt och mycket kommer vara kända saker vi ser. Förutser inte några stora och väsenskilda problem)

**Comment by JohannaOlin** [comment]
Flyttar till DevOps 2660
