### ISSUE TITLE
Tillgänglighetskoll för Terapirekommendationerna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#472]
# Beskrivning
Vi behöver gå igenom terapirekommendationerna inför webbtillgänglighetsdirektivet 23/9. Detta ska göras efter att vi har flyttat den och lagt in de nya komponenterna.

# Acceptanskriterier
- [ ] Speca ner en lista uppdelad på vad som måste fixas samt vad som bör fixas

**Comment by viktor-sarge** [comment]
(Avvaktar med denna tills vi har den nya implementationen)

**Comment by JohannaOlin** [comment]
Flyttad till DevOps 2661
