### ISSUE TITLE
Tillgänglighetskoll för vuxhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#473]
# Beskrivning
Vi behöver gå igenom vuxhalland inför webbtillgänglighetsdirektivet 23/9.

# Acceptanskriterier
- [ ] Speca ner en lista uppdelad på vad som måste fixas samt vad som bör fixas

**Comment by viktor-sarge** [comment]
- [x] Alt-text på puffarna (startsidan)
 
- [x] Runda ikonknappar (startsidan) behöver en aria-label så att länken blir läsbar

- [x] Flytta ut h1 ur ul. 

- [x] Gå igenom rubriknivåerna

- [x] Lägg semantiska taggar i app.blade.php (saknas tex main landmark på startsidan)

- [x] Saknas en h1 på vissa sidor (tex https://www.vuxhalland.se/hitta-din-grej/yrkesvux-och-larling/) Funkar det att göra caption på hero till h1, det är ju trots allt själva rubriken där?

- [ ] Redaktionellt: https://www.vuxhalland.se/prata-med-en-expert/ Listan innehåller en massa p-taggar som inte validerar. Samma med https://www.vuxhalland.se/hitta-din-grej/yrkeshogskola/  https://www.vuxhalland.se/sa-soker-du/

- [x] Se till att rubriker på puffar bara visas när rubriken har ett innehåll

- [x] Se om vi kan dölja ikonlänkarna på puffar i tabindex eftersom länken är en dublett till huvudlänken i text. 

- [x] Ge breadcrumbs en aria label som förklarar vad det är man är på 

- [x] Puffar behöver en aria label

- [ ] Hur skall vi göra med ikonlänk + länk som är ett återkommande mönster. Jag har kodat dem så de har en korrekt aria-labelledby men Koa11y klagar på dem ändå. Satte aria-hidden="true" för att helt dölja dublettlänkarna för skärmläsare men Koa11y klagar fortfarande. Axe är nöjd efter att jag lagt på aria-labelledby som var en förelsagen teknik fr Axe själva. Det är inte ett användarproblem utan snarare ett problem med verktyget Koa11y och frågan är om vi skall ändra vår design för att passa verktyget som webperf använder. Alternativet är ju att bygga något i javascript som gör att båda atomerna aktiveras även om man bara hovrar på ena av ikonknapp/länk.

**Comment by viktor-sarge** [comment]
(Passade på att städa upp lite och gruppera upp partials i mappar som vi gjort med andra webbarn. Går ganska fort eftersom phpstorm i de flesta fall själv kan hitta referenser till filerna och refaktorera de filer som anropar det man flyttar)
