### ISSUE TITLE
Tillgänglighetskoll för Musikhallandia

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#474]
# Beskrivning
Vi behöver gå igenom musikhallandia inför webbtillgänglighetsdirektivet 23/9. 

# Acceptanskriterier
- [ ] Speca ner en lista uppdelad på vad som måste fixas samt vad som bör fixas

**Comment by viktor-sarge** [comment]
- [x] Alt-texter på loggorna

- [x] Allt skall ligga i landmärken (axe)

- [x] main skall finnas på alla mallar

- [x] main får inte ligga inuti ett annat landmärke (vad vi gör)

- [x] Listor i sidfoten skall ha aria labelled by kopplade till sin rubrik

- [x] Rubriknivåerna behöver gås igenom. Det saknas t.ex. en nivå 2 - "Nyheter" på "Press och media" som logiskt sett borde finnas där. 

- [x] Länkarna för jobbanonserna behöver bättre uppläst länktext

- [x] Flytta in ingressen under` <main>`

- [x] Ul får bara ha li som barn. (Press o Media puffarna)

- [x] Puffarna behöver alt-text på bilderna.

- [x] (alt-text på hero-komponenten) Behövdes inte eftersom den är en CSS background

- [x] Pufflänkar skall bara visas om det finns url + text och target-attributet bara visas om det är ifyllt.

- [x] Duplicerat id main på enskilda nyheter?

- [x] Ge round-button länken bakåt en aria labelled-by och knyt till textlänken

- [x] Uppdatera plugin så alt-text finns för evenemangspuffar + visa på sidan.

- [x] Nyhetspuffarna behöver alt-text. Behöver uppdateras i pluginet.

**Comment by viktor-sarge** [comment]
@RolandHyden Jag upptäckte att jag inte kunde alt-texten för contact card-bilderna. Lade till det i pluginet och släppte en ny version (1.6.0) som ger access till det i API:et. Men bara på github än så länge - ger mig inte på devops just nu. Så bra om vi kollar att vi är i synk sedan.

**Comment by viktor-sarge** [comment]
@RolandHyden Verkar vara samma med simple news att alt-texten inte finns tillgänglig. Men här var det svårare att lista ut hur man får ut den. Du får nog hjälpa mig med denna :)

**Comment by viktor-sarge** [comment]
@RolandHyden Jag uppdaterade evenemangspluginet till 2.8.0 med stöd för alt-text på puffbilderna. Släppt den på github, ändrat i readmen och ändrat i excelarket.

**Comment by viktor-sarge** [comment]
@RolandHyden Tack för hjälpen, nu har jag releasat 1.5.0 av page news simple och uppdaterat den i listan också. Det var det sista som axe klagade på.

**Comment by viktor-sarge** [comment]
Både axe och Koa11y är nöjda så jag lägger den här till QA nu.
