### ISSUE TITLE
Tillgänglighetskoll för design.regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#475]
# Beskrivning
Vi behöver gå igenom designsajten inför webbtillgänglighetsdirektivet 23/9. Detta ska göras efter att vi har flyttat den och lagt in de nya komponenterna.

# Acceptanskriterier
- [ ] Speca ner en lista uppdelad på vad som måste fixas samt vad som bör fixas

**Comment by viktor-sarge** [comment]
(Lämnar den här tills vidare eftersom vi inte har den nya sajten ännu)

**Comment by JohannaOlin** [comment]
Stänger denna och flyttar till Devops 2659
