### ISSUE TITLE
Tillgänglighetskoll driftinfo.regionhalland.se

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#476]
# Beskrivning
Vi behöver gå igenom driftinfosajten inför webbtillgänglighetsdirektivet 23/9. 

# Acceptanskriterier
- [ ] Speca ner en lista uppdelad på vad som måste fixas samt vad som bör fixas

**Comment by viktor-sarge** [comment]
- [x] Knappar måste ha urskiljbar text. Jag har gett "+" knapparna en aria label som inkluderar vilken driftstörning de hör till

- [x] Cookie knappen ser trasig ut och har dessutom för dålig kontrast

- [x] För dålig kontrast på siffrorna i cirklarna

- [x] lang attribut saknas på html taggen

- [x] Felaktigt nästlade rubriknivåer

- [x] Allt innehåll skall ligga i landmarks

**Comment by viktor-sarge** [comment]
(Fixat rubriknivåerna, men nu ligger alla titlarna direkt under "Driftinformation" och det vore bättre om strukturen var "Driftinformation / Pågående / Alla / Titlar" så att det var tydligare vilken information man såg. Det blev dock en del visuella buggar med tabbarna så det kan kräva lite extra eftertanke.

**Comment by viktor-sarge** [comment]
Note to self - anledningen att knappen i cookies såg konstig ut var att button inte är med i den site-specifika releasen av styleguiden. Fixar det imorgon så bör granskningen vara klar.

**Comment by viktor-sarge** [comment]
Lagt in button i driftinfo styleguide 1.2.0 och cookienotisen i 1.3.0 + anpassat cookie notisen lite till sin miljö så. Det var det sista som axe och Koa11y klagar på så lägger den här till QA tills vidare.

**Comment by viktor-sarge** [comment]
Flyttade också upp semantiska taggar till app.blade.php
