### ISSUE TITLE
Ändra typsnitt på Musikhallandia

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#483]
# Beskrivning
Typsnittet på Musikhallandia ska vara Helvetica. Helena har skickat typsnittet till Viktor, Frida och Johanna

# Acceptanskriterier
- [x] Typsnittet på hela musikhallandia.se är Helvetica

**Comment by viktor-sarge** [comment]
Fixat, men skall uppdatera test-servern.

**Comment by viktor-sarge** [comment]
Lagt till bold-varianten också så att den slår igenom på <strong>, h-taggar och h-klasser
