### ISSUE TITLE
Kontaktpuffar ska leda till Kontaktsidor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#484]
# Beskrivning
Puffarna på Kontaktsidan, https://test-www.musikhallandia.se/om-oss/kontakt/, ska leda till vanliga sidor

# Acceptanskriterier
- [x] Som besökare kan jag klicka på en puff och komma till en informationssida om kontakten
- [x] Lägg in Tillbaka-länken på informationssidorna

**Comment by viktor-sarge** [comment]
Roland har fixat den nya funktionaliteten med att puffarna länkas till andra sidor. Jag stylar upp det.

**Comment by viktor-sarge** [comment]
Tillbaka-länken är inlagd.

Jag har gjort ett föreslaget utseende på kontaktsidorna som är ok:at med Frida och kommunicerat med Martin.
