### ISSUE TITLE
Snabb granskning av Musik Hallandias grafiska profil

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#49]
Johanna bett att jag tar en titt på Musik Hallandias grafiska profil ur tillgänglighetsperspektiv.

**Comment by viktor-sarge** [comment]
@JohannaOlin Här kommer några snabba synpunkter baserat på det som ligger i den grafiska profilen som Frida skickade. Alltså ej utifrån skisserna. 

En snabb titt på Musik Hallandias grafiska profil: 

- Streck som ligger bakom text stör läsarens identifiering av ordets och bokstävernas form och gör det därmed väldigt besvärligt för t.ex. dyslektiker som har det svårt redan med vanligt text och besvärligt nog med t.ex. understrykningar och text i versaler. Jag rekommenderar att man har solida färgplattor med tillräcklig kontrast under all text. Dvs - inga streck under rubriker, namnet och inte några trianglar direkt under text. 

- Trianglarna är snygga på t.ex. affischer, men problematiska på sidor där man väntas koncentrera sig på att hitta och läsa information. De stjäl uppmärksamheten då de är asymmetriska och i starka färger. För användare med t.ex. ADHD eller OCD kan de bli en avsevärd distraktion. (I ärlighetens namn blir jag själv sjösjuk och lätt illamående av framsidan på den grafiska profilen)

- Washi-tejp idén med notstrecken fungerar väl på affischer, men på webb så krockar de med den numera ganska välkända konventionen om ”hamburgermeny” bestående av tre eller fler streck. Därmed fungerar de inte för webb

- Profilfärgerna erbjuder som allra minst kontrast på AA-nivå mot normalstor svart text och kommer inte innebära ett problem.

- Teckensnitten Helvetica neue 87 heavy condensed och Open sans avviker från Arial som definieras i Region Hallands grafiska profil (sid. 4)

- Är den nya grafiska profilen för Musik Hallandia godkänd att använda? Enligt gällande grafisk manual krävs godkännande för att ens påbörja arbete med en egen logotyp. 

> ”I enstaka fall kan ett projekt eller en verksamhet ha anledning att ta fram en egen logotyp som inte har en direkt koppling till Region Hallands grafiska profil. Det kan exempelvis vara verk- samheter eller projekt som ska knoppas av, eller som bygger på ett nätverk av företag.     Innan en sådan, egen, logotyp tas fram måste detta godkännas av Region Hallands kommunikationsavdelning.”  

>  Region Halland (2011) Grafisk profil Region Halland. s. 15 [https://intra.regionhalland.se/stod-och-service/information-och-kommunikation/logotyper/Documents/Grafisk%20profilmanual%20-%20maj%202011.pdf] 2018-11-29

**Comment by viktor-sarge** [comment]
Ping @fridabergentoft för kännedom.

**Comment by viktor-sarge** [comment]
Lägger den till dig i QA @JohannaOlin

**Comment by JohannaOlin** [comment]
Jag skickat iväg frågan angående logotyp och typsnitt till Charlotte. Resten tänker jag att vi kan ta hand om i skisserna och meddela dem varför vi gjort så.
