### ISSUE TITLE
Granska Oasis workflow

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#494]
# Beskrivning
Vi har köpt ny licens för Oasis workflow, gäller för två siter och detta behöver granskas innan vi lägger in det. Information om inloggning finns i Kunskapsbanken.

**Comment by viktor-sarge** [comment]
Får tyvärr erkänna att jag inte är riktigt säker på scope för denna story. Om det är funktionalitet,  tillgänglighet, något annat.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Issuen gäller att kontrollera så att plugin:et är ok att lägga in, t ex så att det inte pajar prestandan eller något.
