### ISSUE TITLE
Viktigt meddelande utan länk

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#495]
# Beskrivning
Om man inte anger en länk i det viktiga meddelandet så får man error på hela startsidan på sajten

# Acceptanskriterier
- [ ] Uppdatera plug-in:et så att det viktiga meddelandet fungerar även utan länk

**Comment by RolandHyden** [comment]
Hej. Jag har skapat version 1.2.0 av pluginen:

https://github.com/RegionHalland/region-halland-acf-options-page-site-message

Denna version kontrollerar om det finns en angiven länk.
Finns det ingen så returneras tomma värden, dvs inte error.

**Comment by viktor-sarge** [comment]
Gött! Färdig för QA-spalten?

**Comment by RolandHyden** [comment]
Ja, denna är redan inlagd i Composer och inlagd i master på test-www.regionhalland.se.
