### ISSUE TITLE
Komponent för vänstermeny

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#50]
# Beskrivning
Vänstermeny ska användas efter nivå två, om inte sidan är en section page, samt efter en section page.

# Skisser
- [ ] Desktop - 
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Vänstermenyn ska starta efter en Section Page
- [ ] Barnen fällt ut när jag går till respektive sida

**Comment by viktor-sarge** [comment]
Snabb visuell QA ihop med Frida: 

Navigation 

* avdelarna mellan navigationsval är fetare än på skissen
* den blå linjen på sidan skall vara solid
* den blå linjen på sidan skall ha 90 graders vinkel (sned i botten i nuläget)
* plus och minus-tecken i cirklarna skall vara mer fetade
* cirkel på ljusblå botten skall vara vit
* blå aktivt val skall ha en blå ram enligt skiss (ej grå)

* nav mobile "fällbar box": cirkeln är inte korrekt alignad i höjdled

nav mobile "box--active"
* cirkeln skall ha minus tecken på aktiv komponent
* cirkeln är för stor jämfört med inaktiva läget
* cirkeln är inte korrekt alignad i höjdled

rh-nav-mob__subpage
* saknas en variant (utan pil) 
* läget med pil skall ha en avdelare till vänster om pilen

**Comment by JOHNREGIONHALLAND** [comment]
FIXAD: rh-nav-mob__subpage 
JOHN: placering på pilen är lite fel...
saknas en variant (utan pil)
läget med pil skall ha en avdelare till vänster om pilen

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=52%3A2&viewport=400%2C2026%2C0.665427&scaling=min-zoom

Hur helheten ser ut kan du se här: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=40%3A84&viewport=368%2C225%2C0.255463&scaling=min-zoom

**Comment by brightjennie** [comment]
Denna är nu upplagd men har inte lagt på aria-labels. Den heter secondary-nav efter figma.

**Comment by viktor-sarge** [comment]
Jag har labbat lite med den på sajten. Ser inga uppenbara problem med CSSen, men däremot skall jag nog krångla lite med att få rätt data på rätt ställe :) Men jag behåller den öppen en stund till för att se om Frida har några synpunkter. I och med att de fortfarande jobbar på designen för regionhalland.se så kan det hända att det finns något ytterligare utseende som de vill ha med.

**Comment by fridabergentoft** [comment]
Jag är nöjd! Hade varit kul om den var klickbar men den ser rätt ut så vi nöjer oss med det nu
