### ISSUE TITLE
Flera roller på en webbplats

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#52]
# Beskrivning
I Terapirekommendationerna finns ett arbetsflöde som bland annat innebär att redaktörerna får mail när författarna sparar en version. En av redaktörerna önskar även vara administratör. Vi behöver göra det möjligt att ha två roller på en webbplats.

Detta gäller alla webbplatser, dvs Terapirekommendationerna, Vårdgivarwebben och Regionhalland.se

# Acceptanskriterier
- [ ] Som användare kan jag ha mer än en roll för Terapirekommendationerna
- [ ] Som användare kan jag ha mer än en roll på Vårdgivarwebben
- [ ] Som användare kan jag ha mer än en roll på regionhalland.se

**Comment by viktor-sarge** [comment]
Detta går att lösa med "User role editor"-pluginet som vi har installerat sedan innan (men inte aktiverat per default). Då får man följande dropdown som tänder en lista med checkboxar där man markerar vilka ytterligare roller en användare skall ha. 
![image](https://user-images.githubusercontent.com/3371823/49284897-3c600e80-f496-11e8-9143-f4d1fa352946.png)

PS) Wordpress har stöd i kod för flera roller per användare, men det finns inte i GUI. Man kan sätta extra roller i koden, men om man sedan redigerar rollerna i GUI igen så blir det bara en enda igen. Därför är det lämpligast att aktivera "User role editor" och sköta det den vägen. Jag har aktiverat tillfälligt i stage-vardgivare.

@JohannaOlin

**Comment by JohannaOlin** [comment]
Vi kommer att behöva detta för alla webbplatser. På vårdgivarwebben och regionhalland.se behöver man kunna vara både nyhetsredaktör och redaktör för viktiga meddelanden.

**Comment by viktor-sarge** [comment]
Startar denna eftersom den hänger med på den andra storyn om att separera ut nyhetsredaktör som en egen roll.

**Comment by viktor-sarge** [comment]
Möjligheten att ha flera roller får vi med "User role editor" som ger en "Other roles" på wp-admin/user-edit.php där man kan välja alla de extra roller som man vill att anävndarna skall ha. Så där det saknas kan vi göra kort på att lägga in och aktivera user role editor. 

Separationen av behörigheten till funktionerna som kommer från custom post types från enskilda plugins löses bäst genom att lägga kort till Roland att lägga in separata "capabilities" på alla berörda plugins (viktigt meddelande m.fl.). För nyheter finns det redan och det var ganska snabbt gjort. Vi uppdaterade en fil, gjorde en ny release av pluginet, uppdaterade composerfilen för sajten, synkade upp till github och körde composer update. Att göra det lokalt (för att verifiera att det funkar) och sedan på servern tar en liten stund men inga evigheter.

**Comment by viktor-sarge** [comment]
Lägger till QA med tanken att det är *metoden* som levereras. Medan genomförandet av den kan få egna kort. Men är helt beredd att ta det vidare i denna story om det är enklare.
