### ISSUE TITLE
Installera pluginbaserad vårdgivarwebb på vår egen stage-server

### ISSUE THREAD

**Issue by viktor-sarge** [RegionHalland/general#54]
För att flytta vårdgivarwebben skarpt så behöver vi först testa att den nya pluginbaserade setupen fungerar på regionens stage-server. 

**Acceptanskriterier**

- [x] Databasen importerad från den skarpa vårdgivarwebben på azure.

- [ ] Den nya pluginbaserade kodbasen är avlusad och installerad.

**Comment by viktor-sarge** [comment]
Slår mig att vi behöver tidssätta den här också @RolandHyden   :)

**Comment by JOHNREGIONHALLAND** [comment]
![plugin-vg](https://user-images.githubusercontent.com/42959033/49719110-7d0d1400-fc5c-11e8-9c87-197c48e26ea6.jpg)
Dump på inlagda plugind
