### ISSUE TITLE
Ändring av driftinformationen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#55]
# Beskrivning
Idag finns ett embryo till webbplatsen för driftinformation, driftinfo.regionhalland.se. Vi behöver göra en del justeringar, se acceptanskriterierna, för att vi ska kunna börja använda den.

# Skisser
- [ ] Ikon för topplänk https://www.figma.com/proto/efXn6orglDUSZqMBkxiPfK3H/vardgivare.regionhalland.se?node-id=0%3A134&scaling=min-zoom Uppe bland topplänkarna finns ikonen för Driftinfo
- [ ] Skiss för driftinfosajten,

# Kontaktperson 
Mona Nyman

# Acceptanskriterier
- [ ] Lägg in driftinformationen i den nya set-upen
- [x] Lägg över denna på rätt server
- [ ] Se till så att den använder https när den ligger på rätt server
- [x] Som redaktör vill jag kunna fylla i en beskrivande text om driftstörningen
- [ ] Som besökare kan jag klicka på driftstörningens rubrik för att se den beskrivande texten
- [ ] Dölj fältet med kontaktinformation
- [ ] Lägg in en topplänk på Vårdgivarwebben till Driftinformation. Länken ska vara https://driftinfo.regionhalland.se, Texten som ska visas ska vara "Driftinformation" och ikonen finns under Skisser.
- [ ] De vill även ha in område för driftstörningarna, se skissen som Frida gjort, men vi kan börja med följande områden IT, Telefoni, Fastighet.

**Comment by viktor-sarge** [comment]
Hej! Vet inte riktigt vilken nivå jag skall köra QA på här. Hittar inte skissen som @fridabergentoft har gjort men tänker att det nästan är lättast att vi pratar om det öga mot öga. Inte någon diskussion i tråden heller så vet inte hur ni stämt av innan. Men jag gör en snabb koll utifrån det som listats ovan + en jämförelse med driftinfo.regionhalland.se. 

* Jag tror att informationen skall grupperas mer så att det inte blir tre knappar per område. Minns inte hur skisserna såg ut men gissar att vi kan låna friskt av https://driftinfo.skane.se/Sidor/list_all.aspx och först gruppera per akut/planerad/avslutad och sedan per område. 
* Driftstörningarna skall nog vara ihopfällda per default och expandera vid klick på rubrik om jag läser acceptanskriterierna rätt. 
* Https: nej finns inte just nu. (Vem vet status?)
* Beskrivande text: Jag kryssar i denna. 
* "Dölj fältet kontaktinformation". Om det avser "Har du frågor eller vill anmäla..." i den blå plattan så är det kvar att göra. Men mycket snabbt gjort. 
* Topplänk på vårdgivarwebben - inte gjort men bör nog heller inte göras innan den här storyn är klar. Kanske gör sig bättre som eget kort som blockas av detta så vi inte slussar in trafik innan själva driftinfo är färdig. 
* Lägg in driftinfo i nya setupen: Skulle bedöma att svaret är ja/nja. Den är byggd enligt tänket med plugins så vitt jag även om det är en lite unik plugin i botten. Däremot kan den ju inte använda komponenterna från nya styleguiden innan de är byggda. Därav "nja" - vi bör rimligtvis lägga in komponenterna här när de blir färdiga. 
* Lägg över på rätt server. Ja den ligger på rätt server - jag krysser i detta. Däremot behöver vi bättre setup kring servern. Deploy skall ske automatiskt utan manuell FTP. När vi får riktig deploy på plats behöver testservern ominstalleras så vi har kontroll över felkällor.

**Comment by viktor-sarge** [comment]
Lägger den som "failed QA" och flyttar tillbaka till sprint backlog för resterande punkter.

**Comment by JohannaOlin** [comment]
Vi har en del ändringar som vi behöver göras i funktionen för att det ska fungera som intressenterna vill. Utseendeförändringarna tar vi när komponenterna är klara och läggs på ett eget kort.
- [ ] Dölj inforutan med kontaktinformationen
- [ ] I redigeraläget ska status Pågående heta Akut istället
- [ ] I redigeraläget ska status Planerad heta Enligt plan istället
- [ ] På utsidan ska tabben Planerad byta till Enligt plan
- [ ] Flikarna som heter Akut ska heta Pågående istället och där ska alla (både akuta och enligt plan) där starttiden har inträffat men sluttiden inte har inträffat visas.
- [ ] Flikarna som heter Planerade ska byta namn till Kommande ska visa alla där varken starttiden eller sluttiden har inträffat
- [ ] Flikarna Avslutade ska visa alla där sluttiden har inträffat 

Sen när vi lägger in komponenterna och därmed delar upp IT, telefoni, fastighet samt Pågående, Kommande och Avslutade så kommer startsidan att vara fliken Pågående, men utan område (IT, telefoni och fastighet) vald.

**Comment by JohannaOlin** [comment]
@RolandHyden Jag har lagt in ett par riktiga driftstörningar så att du får ett hum om hur det blir. Det är Driftavbrott TeleQ och Driftstörning Tele2 och Comviq mobiltelefoni.

**Comment by RolandHyden** [comment]
Ok, jag har fixat alla ändringarna enligt ovan, även framsidan. Så nu ska det "bara" fattas layout innan vi kan lansera.
