### ISSUE TITLE
Prototyp - Komponent för Sidfot med loggor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#58]
# Beskrivning
På sajter där regionen inte är ensam avsändare behövs en annan sidfot som kan visa upp loggorna för samtliga avsändare

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska gå att förstora till 200% utan att utseendet spricker

**Comment by viktor-sarge** [comment]
Gillar sidfoten. Två synpunkter: 
* De blå strecken behövs inte i mitt tycke. 
* Det är snyggt med de matta logotyperna, men har vi ok att göra så? (Sedan blir de såklart rätt svåra att identifiera också för en del användare då kontrasten blir låg)
