### ISSUE TITLE
Prototyp - Komponent för logga + sajtnamn

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#59]
# Beskrivning
På de allra flesta webbplatser behöver vi förutom Region Hallands logga även visa upp vilken sajt besökarna är på (ex intranät, webbplats för vårdgivare, driftinfo)

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska gå att förstora 200% utan att utseendet spricker
- [ ] Komponenten ska visa logga samt info om vilken sajt besökaren är på

**Comment by viktor-sarge** [comment]
Inga synpunkter på denna.
