### ISSUE TITLE
Prototyp - Komponent för Sökruta

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#60]
# Beskrivning
Vi behöver en sökruta som dels ska kunna visas uppe i sidhuvudet och dels kunna läggas in där redaktören väljer det. Denna PBI handlar dock endast om själva rutan

# Acceptanskriterier
- [ ] Komponenten ska kunna användas på Desktop, tablet och mobil
- [ ] Komponenten ska gå att förstora till 200% utan att utseendet spricker
- [ ]

**Comment by viktor-sarge** [comment]
Utseendet och kontrasterna är godkända, men placeholdertexten behöver vara riktigt menlös. Eftersom texten försvinner när man aktiverar rutan så kan man inte ha någon ledtext där som faktiskt är viktig. Kanske bättre att vi alltid har den tom och placerar text där folk har en chans att faktiskt läsa när de fyller i och börjar undra vad som stod från början.
