### ISSUE TITLE
Prototyp- Komponent för puffar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#62]
# Beskrivning
Komponenten ska användas för att ge besökarna en snabbväg till ett viktigt innehåll. Användningsområdet är det samma som för snabblänkarna.

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska gå att förstora 200% utan att utseendet spricker

**Comment by viktor-sarge** [comment]
Kikat på denna om det är "Shortcuts" i PDF:en. Värt att stämma av är varför länkar inte är blå.
