### ISSUE TITLE
Prototyp - Komponent för Snabblänkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#64]
# Beskrivning
Komponenten har samma användningsområde som puffarna, men denna komponent innehåller endast en länksymbol och en rubrik.

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska gå att förstora 200% utan att utseendet spricker
- [ ] Komponenten ska gå att lägga in på startsidan, Översiktsida och Section Page

**Comment by viktor-sarge** [comment]
Ser ingen länksymbol i den här puffen så som den är ritad i PDF:en. Värt att diskutera också varför länkar inte defaultar till blått.
