### ISSUE TITLE
Prototyp - Komponent för Viktigt meddelande

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#66]
# Beskrivning
Komponenten ska användas då regionen behöver nå ut till besökarna med viktig information. Det kan t ex gälla stora driftstörningar

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska gå att förstora till 200% utan att utseendet spricker
- [x] Komponenten ska synas tydligt
- [x] Komponenten ska innehålla en rubrik, textfält samt länk för att läsa mer information
- [x] Komponenten ska innehålla datum och tid

**Comment by viktor-sarge** [comment]
Mätte kontrasten mellan rött och rosa till 7.66:1 så den flyger igenom galant. Jag har dock lite svårt att avkoda symbolen. Tolkar det som "Klockan är 12:00" på en analog klocka och jag är inte säker på att det är avsikten.

**Comment by viktor-sarge** [comment]
(Drog tillbaka den här och satte label "failed QA". Tänker att vi kan använda den för fall när det är något som behöver kollas igen efter QA så att det blir lätt att urskilja varför de kommit tillbaka)

**Comment by JohannaOlin** [comment]
@fridabergentoft Lägg in en länk också i prototypen. Tänker mig en Läs-mer-länk.

**Comment by viktor-sarge** [comment]
Vi bestämde oss för att använda ett vitt utropstecken i en röd cirkel som ikon istället. Det är då inte en faktiskt ikon utan ett vanligt tecken. Själva symbolen blir tydligare än den förra ikonen. Kruxet är att Frida inte har så mycket att välja på om man bara vill använda "feather icons"-kittet.

**Comment by viktor-sarge** [comment]
Tar bort failed qa label och så kan du släcka den om du är nöjd @JohannaOlin . 

Vi diskuterade också "Läs mer"-länk och avgjorde att den inte skall heta "Läs mer" utan vara mer fritextbetonad. Antingen att man kan länka fritt direkt i själva meddelandetexten eller att man har ett fält för URL och ett för länknamn där man utforma texten mer som "Ytterligare information om störningarna i Personec finns att läsa på XXX"
