### ISSUE TITLE
Visa upp alla Gäller för-taggar på ett styrt dokument

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#67]
# Beskrivning
Vissa styrda dokument taggas med mer än en enhet i Gäller för. Nu visar vi endast upp en enhet vid Gäller för-taggningen. Detta dokument http://styrdadokument.regionhalland.se/doc/C7708588-B769-476E-8981-78FFDBEB6CFE är till exempel taggat med både Närsjukvården Halland och Kommuner, men på vårdgivarwebben visas endast Närsjukvården Halland

# Acceptanskriterier
- [ ] Hämta och visa upp alla enheter som ett styrt dokument är taggat med

**Comment by viktor-sarge** [comment]
För tydlighet: jag gör ingen QA på denna utan lämnar till Johanna som har koll på storyns scope.
