### ISSUE TITLE
Stora/Tunga styrda dokument

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#68]
# Beskrivning
Riktigt stora/tunga styrda dokument fungerar inte optimalt på sajten. En del av dem går inte att öppna och någon går att öppna men visar inte några bilder. Titta t ex på http://styrdadokument.regionhalland.se/doc/36DD8248-046C-4165-9DF6-40402A3C85B7 här visas inga bilder.

# Acceptanskriterier
- [ ] Som besökare vill jag kunna öppna även tunga dokument samt se bilderna i dem.

**Comment by JOHNREGIONHALLAND** [comment]
Update 
-  Alla dok som är större än 800-900 Kb verka vara problem att öppna, beror nog inte på innehållet
- Ska kika på php.ini och SQL med linda

**Comment by JOHNREGIONHALLAND** [comment]
FIXAD!
Källa
ODBC blob data är standard inläsning 4096 - https://stackoverflow.com/questions/18893756/retrieving-blob-from-database-loses-part-of-the-file
Öka inläsningen av BLOB data så att stora dok kan öppnas från SQL ändra i php.ini
sudo nano /etc/php/7.2/apache2/php.ini
odbc.defaultlrl = 4090 till 10000000
