### ISSUE TITLE
Genomgång av Vårdgivarwebben på vår interna testserver

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#69]
# Beskrivning
Vårdgivarwebben ska flyttas in på vår interna server. Vi behöver gå igenom sajten så att den fungerar som den ska.

# Acceptanskriterier
- [ ] Genomgång av alla sidtyper och vanligt förekommande uppgifter.

**Comment by viktor-sarge** [comment]
Går igenom med främst IE och Edge. 

**Kollat och ok:at:** 

* Sortering av styrda dokument via dropdown (funkar)

**Hittat buggar:** 
* Hitta på sidan fungerar inte. Många gånger verkar det inte finnas ett id att scrolla till + tänder inte upp den blå flashen

* Styrda dokument - filer som pekar mot uploads finns inte med. Se ex. http://stage-vg.regionhalland.se/behandlingsstod/funktionsnedsattning/hjalpmedel/forskriva-hjalpmedel/barnhjalpmedel/#ovriga-dokument

* Bilder som inte syns. Hittat fler ställen som t.ex. https://vardgivare.regionhalland.se/behandlingsstod/funktionsnedsattning/hjalpmedel/  och http://stage-vg.regionhalland.se/utveckling-forskning/halsoinformatik/halsoinformatikgruppen/referensgrupp-journaldokumentation/   samt http://stage-vg.regionhalland.se/service-it/analys-uppfoljning-och-statistik/

* Nyheter - "Continued"-länkar kvar på nyheterna. 

* Nyheter - Nyheter visas på sidor som inte har några nyheter i prod. T.ex. http://stage-vg.regionhalland.se/service-it/it-stod-och-system/ och http://stage-vg.regionhalland.se/patientadministration/avgiftshandboken/

* Nyheter - Shortcode visas i utrdaget för nyheter. Se t.ex. http://stage-vg.regionhalland.se/behandlingsstod/

* Breadcrumbs. Hittat ett ställe där det ännu krångar. http://stage-vg.regionhalland.se/behandlingsstod/funktionsnedsattning/hjalpmedel/   samt http://stage-vg.regionhalland.se/nyheter/nyheter/hjalpmedelscentrum-natverksfel/ som båda genererar en identisk breadcrumb. Verkar vara på vissa vanliga sidor + alla nyheter.

**Värt att notera även om man inte fixar:**  
* Teckenstorleken och ev vikten är annorlunda och det påverkar en del saker som t.ex. hur länksymboler alignas vertikalt, hur de tvåfärgade strecken renderas osv.

**Comment by viktor-sarge** [comment]
Jag har kollat främst på redaktörsgränssnittet idag och har följande findings för stage-vg.regionhalland.se-sajten.

# Översiktssida
**Testat för översiktssida som funkade väl:** 
- Lagt till text (som visades korrekt)
- Lagt till bild från mediabiblioteket
- Lagt till textmodul (både som separat och inbäddad i article), länkgrupp och RSS-flöde från modularity. 
- Bäddat in en iframe med regionens livevideo. 
- Återställt sidan genom att ta bort allting igen. 
- Ändrat sidans synlighet till privat och åter till offentlig.
- Bytt mall på sidan. (Dock ger "standardmall" inte någon vänsternav till barnen. 


Testat för översiktssida som **inte** fungerade: 
- Lagt till innehållsansvarig (visade varken förvald eller manuellt ifylld). Visade sig att det inte visas på Azure heller.  LÖST. 
- Borde standardmall på "Medicinska områden" ge en vänsternavigation?    Ger inte vänsternavigation på Azure heller. LÖST.
- Verkar inte kunna återställa en tidigare version.   Kunde inte replikera buggen. LÖST TILLS VIDARE
- Hittar inte hur jag lägger till nyheter på en översiktssida. Tittar jag kanske på fel mall?  LÖST. Man behövde byta till en annan mall. Testade och det fungerade att lägga till de nyheter som jag ville. 

# Vanlig sida - "akut vård" 

**Testat som funkar:** 
- Att lägga till utvald bild (visas inte, vilket är helt korrekt)
- Att visa innehållsansvarig. (förvald + manuellt ifylld)
- Dölja/visa sida. 
- Byta tillbaka till ursprungsmallen när man bytt till en mall som inte fungerar. 
- Återställa en tidigare version.
- Bytt publiceringstid
- Kunde lägga till moduler under article och under vänstermenyn. Men ej till höger. 

Testat som **inte** funkar:
- Byta mall - barnen visas inte när man byter från standardmall till översikt.  LÖST. Kunde inte replikera buggen. Det var troligen syskonen jag såg i vänstermenyn och inte barnen. 
- Skall man alls kunna lägga till moduler till vänster under menyn?   LÖST. Samma beteende på Azure.

# Ny sida/or
**Testat som funkar:**
- går att skapa en ny sida som funkar under "Akut vård" med en barnsida och byta den från standardmall till översikt. 
- infoga bilder
- Återställa en tidigare version.
- Infoga moduler
- Sortera om och/eller ta bort sidor (men nested pages pluginet hänger sig dock)

**Comment by viktor-sarge** [comment]
Roland har levererat ett gäng buggfixar som jag testat. Dokumenterar och släcker dem i story #53

**Comment by viktor-sarge** [comment]
Jämfört med Azure och hittar inget i backend som är unikt för den plugin-baserade stage-vg. Däremot så finns det en del beteenden som vi kanske skall se över generellt. Stämmer av med Johanna och lägger stories på det som skall fixas.

**Comment by JohannaOlin** [comment]
Detta är vad jag har hittat. Jag vet inte om en del av detta måste ändras redaktionellt, annars kanske vi behöver surfa igenom alla sidor ordentligt för att se så att det inte finns fler tokigheter.

- På sidor som visar en delmängd av nyheter så ska knappen för att se fler heta "Se alla nyheter inom områdets namn", ex sidan http://stage-vg.regionhalland.se/behandlingsstod/lakemedel/
- Nyhetsarkivet visar 3 nyheter sen kommer en knapp "Se alla nyheter" sen visas samma tre nyheter igen. Nyhetsarkivet ska lista samtliga nyheter
- Filmerna som visas på sidan http://stage-vg.regionhalland.se/service-it/it-stod-och-system/vas/vas-utbildningsssida/vas-filmer/ blir för breda
- Stora rubriker i Hitta på sidan på sidan http://stage-vg.regionhalland.se/service-it/it-stod-i-varden/om-it-stod-i-varden/
- Interna länkar, ex sidan http://stage-vg.regionhalland.se/uppdrag-samverkan/socialtjanst-och-naraliggande-halso-och-sjukvard/trygg-och-effektiv-utskrivning/ fungerar inte. Länkarna till Lifecare
- Alla bilder har inte kommit med på sidan http://stage-vg.regionhalland.se/uppdrag-samverkan/socialtjanst-och-naraliggande-halso-och-sjukvard/samverkan/
- När jag klickar på taggen för nyheten (ex på sidan http://stage-vg.regionhalland.se/service-it/it-stod-i-varden/) så kommer jag bara till samma sida, jag ska komma till arkivet för dessa nyheter.
- Cookienotisen (testat i Edge) ser märklig ut, men det kanske är för att vi inte lagt in något innnehåll? ![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/81854c2c-0a5b-48ec-b0d7-6655beea13ca)
