### ISSUE TITLE
Flytta Vårdgivarwebben till vår interna server

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#70]
# Acceptanskriterier
- [ ] Flytta databas
- [ ] Flytta kod
- [ ] Flytta bilder
- [ ] Flytta domän
- [ ] Se till så att https://vardgivare.regionhalland.se/terapirek fortfarande fungerar

**Comment by JOHNREGIONHALLAND** [comment]
Har kopierat  till RH utv server.
- Databas
- Upload
-Héla sajten
-Kännedom: vg-azure

Har kikat igenom och gjort några ändrat för att hålla sig till standard.

**Comment by JohannaOlin** [comment]
Vi avvaktar med denna tills vi kan flytta Terapirekommendationerna.
