### ISSUE TITLE
Komponent för Tillbaka-navigering

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#71]
# Beskrivning
Länk för att nå sidan ovanför

# Skisser
- [ ] Desktop - 
- [ ] Tablet - 
- [ ] Mobil -

# Acceptanskriterier
- [ ] Komponenten ska fungera i desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge och Chrome, Safari

**Comment by JOHNREGIONHALLAND** [comment]
class= rh-button__goback

http://demo.regionhalland.se/rh-cdn/styleguide/

**Comment by viktor-sarge** [comment]
Tar en första QA-vända: 

- [ ] BEM:a namngivningen. ´button´ tror jag är överflödigt. Blocket är inte "knapp" utan snarare "åter"-funktionaliteten. Samma med ´title´ - den är inte en modifier. Prova hellre med rh-goback och .rh-goback__description 

- [ ] Byt statiska pixelmått mot relativa mått.

- [ ] Använd variabler för avstånd och mått där så är möjligt. Om det t.ex. återkommer en padding på 10px i många komponenter är det bättre att köra ´$rh-padding-top-a´ eller något liknande som i sin tur innehåller ´1ex´ eller något liknande. 

- [ ] Linta gärna. Syntaxen är lite svajig med varierande indentering, dubbla semikolon, varierande regler för blockavslutning med måsvingar och lite sådant. Kompilatorn tar nog hand om det mesta men lättare att läsa koden om det är striktare. 

- [ ] Använd variabler. Nu ligger t.ex. #000000 hårdkodat. 

- [ ] Tänk på att hålla DOMen platt. Vi vill ha så få noder som möjligt för snabb rendering.

**Comment by fridabergentoft** [comment]
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=40%3A0&viewport=-651%2C2076%2C0.782204&scaling=min-zoom

De två nedersta komponenterna. 
Tablet har samma storlek som Desktop.

**Comment by brightjennie** [comment]
Denna heter rh-label-previous.

**Comment by viktor-sarge** [comment]
Inte hunnit implementera men liten och enkel och ser bra ut i Fractal. Förutser inga problem. 

Jag av-assignar mig. Om du ser något Frida så hojta annars lägg till "ready for release"
