### ISSUE TITLE
Komponent för Topplänkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#72]
# Beskrivning
Topplänkarna är länkar som besökarna ska kunna nå oavsett var de befinner sig på webbplatsen. 

# Skisser
- [ ] Desktop
- [ ] Tablet

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop och tablet
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari
- [ ] Komponenten ska visas uppe i sidhuvudet

**Comment by JOHNREGIONHALLAND** [comment]
http://demo.regionhalland.se/rh-cdn/styleguide/design-editor.php#rh-toplink

Frida Skiss PDF
[https://app.zenhub.com/files/158801558/dedb28bb-3bd6-4382-8792-da5cb616bc3c/download](https://app.zenhub.com/files/158801558/dedb28bb-3bd6-4382-8792-da5cb616bc3c/download)
class: rh-toplink

**Comment by JOHNREGIONHALLAND** [comment]
class: rh-toplink

**Comment by brightjennie** [comment]
rh-toplinks

**Comment by viktor-sarge** [comment]
Jag har implementerat den här och det funkar bra. Jag av-assignar mig. Frida - lägg till "ready for release" om du är nöjd.
