### ISSUE TITLE
Komponent för sidhuvud

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#73]
# Beskrivning
Sidhuvudet ska innehålla komponenterna Logga + Sajtnamn, Topplänkar och Sökruta

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier 
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari
- [ ] Det ska gå att välja vilka av de ingående komponenterna man vill visa (Logga + sajtnamn, Topplänkar, Sökruta)

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=80%3A157&viewport=343%2C318%2C0.363748&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-header

**Comment by viktor-sarge** [comment]
@fridabergentoft hur gör vi här. Acceptanskriteriet är att topplänkar ingår, men skissen innehåller inte topplänkar. Har för mig att det också var så att de skulle flytta in i mobil-navigationen på små skärmar.

**Comment by viktor-sarge** [comment]
Av-assignar mig här och lämnar till Frida.

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd med komponenten!
