### ISSUE TITLE
Komponent för logga + sajtnamn

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#74]
# Beskrivning
Komponenten består av en logga och sajtens namn

# Skisser
- [ ] Desktop - 
- [ ] Tablet - 
- [ ] Mobil -

# Acceptanskriterier
- [ ] Komponenten ska gå att använda på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari
- [ ] Det ska gå att släcka en av delarna om du endast vill visa loggan respektive sajtnamnet på sajten

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=80%3A182&viewport=713%2C2538%2C1.47901&scaling=min-zoom

**Comment by brightjennie** [comment]
Denna gick inte att göra flytande.. Granska och återkoppla om det är helt fel ;)

**Comment by viktor-sarge** [comment]
Ok med mig. Kan kika på tillgängligheten och tweaka sedan.

Av-assignar mig tills vidare. Frida - hojta om du ser ngt och lägg till "ready for release" annars.

**Comment by fridabergentoft** [comment]
Jag är nöjd!
