### ISSUE TITLE
Komponent för länkstig

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#75]
# Beskrivning
Komponenten används för att visa besökaren var i strukturen aktuell sida befinner sig samt för att ge besökaren en möjlighet att snabbt nå sidorna högre upp i informationshierarkin.

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil -

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=67%3A35&viewport=-752%2C-1625%2C0.704495&scaling=min-zoom

**Comment by brightjennie** [comment]
Har inte lagt in aria-label. Går nog fortare om ni gör det själva sen?

**Comment by viktor-sarge** [comment]
Looking good. Jag lägger den som färdig tills vidare och så får du hojta om du ser något med det visuella @fridabergentoft
