### ISSUE TITLE
Komponent för sidfot

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#78]
# Beskrivning
Komponent för sidfot som används på våra övergripande sajter

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=69%3A2&viewport=401%2C-145%2C0.425849&scaling=min-zoom

**Comment by brightjennie** [comment]
Rh footer heter denna

**Comment by viktor-sarge** [comment]
Jag har implementerat denna och det funkar bra. Släcker tills vidare och av-assignar mig. Frida - hojta om du ser något tokigt nu och lägg annars till "ready for release". Senaste versionen funkar bra nu på min maskin nu.
