### ISSUE TITLE
Komponent för knapp

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#79]
# Beskrivning
Kodandet av komponenten Knapp

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by viktor-sarge** [comment]
Ser bra ut. Nytt är ikonhanteringen. Jag lägger till "ready for release". 

(Note to self: i teamet vill vi nog i förlängningen förbereda ett antal ytterligare knappar med färdiga ikoner + ev. en "--icon-inline" eller liknande där vi kan infoga ikonen direkt från blade-filen. Men den nuvarande konstruktionen abstraherar bort ikonerna helt från blade-filerna vilket vi vill ha så långt som möjligt)
