### ISSUE TITLE
Komponent för Sidfot med loggor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#80]
# Beskrivning
Kodandet av komponenten Sidfot med loggor

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by viktor-sarge** [comment]
Snabb visuell QA m Frida: 

* Loggorna ligger väldigt ihoptryckta och på två rader på demo.regionhalland.se när de enligt skissen skall fördelas ut på en rad
* mättnaden känns inte helt som 100% när man hovrar över dem(?)

**Comment by fridabergentoft** [comment]
Loggor: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=151%3A446&viewport=-1142%2C-222%2C0.490257&scaling=min-zoom

Komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=151%3A459&viewport=-425%2C-1428%2C0.549081&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-footer-logo

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd med komponenten!
