### ISSUE TITLE
Komponent för Sökruta

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#81]
# Beskrivning
Kodandet av komponenten Sökruta

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=80%3A259&viewport=5435%2C4211%2C0.279619&scaling=min-zoom

**Comment by brightjennie** [comment]
rh-search

**Comment by viktor-sarge** [comment]
Ser helt rimligt ut. Snyggt jobbat. Jag lämnar visuellt till Frida men lägger den i "ready for release" tills vidare.
