### ISSUE TITLE
Komponent för Label

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#83]
# Beskrivning
Kodandet av komponenten Label

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=126%3A96&viewport=41554%2C33360%2C2.27259&scaling=min-zoom

Endast de som heter Exempel

**Comment by brightjennie** [comment]
Denna är nu klar och heter rh labels

**Comment by viktor-sarge** [comment]
Ser ut att se rätt ut och inga synpunkter på markupen. Jag lägger till "ready for release". Vi kanske vill dra upp storleken lite, men det gör vi lätt själva.
