### ISSUE TITLE
Komponent för puffar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#84]
# Beskrivning
Kodandet av komponenten Puffar

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by JOHNREGIONHALLAND** [comment]
http://demo.regionhalland.se/rh-cdn/styleguide/design-editor.php#rh-article__box


<div class="rh-box__container" style="width: 100%;">
<div class="col sm-col-6 pr3">
<article class="rh-article__box " title="Articles information">
    <div class="rh-article__box--media bg-norepeat" style="background-image:url('http://regionhalland.se/PageFiles/37615/yrken300-150.jpg');"></div>
    <div class="rh-article__box--title">Articles information</div>
    <div class="rh-article__box--content">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation ullmaco laboris nisi ut aliquap ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolor eu fugiat nulla pariatur.
    </div>
</article>
</div>

<div class="col sm-col-6">
<article class="rh-article__box " title="Articles information">
    <div class="rh-article__box--title">Articles information</div>
    <div class="rh-article__box--content">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation ullmaco laboris nisi ut aliquap ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolor eu fugiat nulla pariatur.
    </div>
</article>
</div>
</div>

**Comment by viktor-sarge** [comment]
Assignade John på denna.

**Comment by viktor-sarge** [comment]
Måste stämma av med @fridabergentoft så att det är rätt skiss jag tittar på. Men några snabba synpunkter på markupen för rh-article__box

* Inline styling skall bort
* Platta till DOM:en och ta bort onödiga DIV:ar
* Ser ut som det är blandat utility-klasser från tailwind och basscss. Använd inte utility-klasser utan gör komponenter.
* article-taggen skall inte användas för puffar utan inbegriper innehåll som kan stå helt på egna ben som t.ex. en bloggpost. Om det är en puff på sidan kan dock aside-tagggen användas. Här ser det dock ut att vara mer en nyhetslistning som ligger i main-arean så den är inte heller lämplig här. 
* Gå igenom namngivningen och BEM:a. Ser ut som allt är förskjutet en nivå. --content är inte en modifier t.ex. 
* Gå igenom och linta markupen så att indentering, blanksteg osv tightas till. 
* En ul-lista behöver ett attribut aria-label eller aria-labelledby. 

Några snabba funderingar på CSS:en
* Varför valet av "display:table" i .rh-box__container?
* Fast pixelhöjd känns skakigt (.rh-article__box--media). Om det är nödvändigt att låsa höjden pga att bilder alltid skall vara en viss storlek så lägg höjden i en variabel så den kan administreras centralt.
* Jag tror inte det är lämpligt att infoga bilderna som bakgrundsbilder via inline css. De är en del av innehållet och inte endast dekoration. Använd vanliga img-taggar och lägg en alt-text på dem. 
* Använd variabler för storlekar och avstånd
* Använd inte fasta pixelmått för t.ex. padding

**Comment by JOHNREGIONHALLAND** [comment]
Ok... Ska gå igenom det och ändra.
Ja jag slopar px och kör med rem, em.

När det gäller table är en tillfällig lösning.
Då utility som Roland lagt upp från gamla styleguiden är skadad/inte ok. Vilseledande.

Tror bättre att du ser över när det är inlagt direkt på sajten. Håller på fintjustera rh komponenter och  den nya utility från tailwin utanför som vgsajten använder.

Jag återkommer så det inte blir missuppfattning.


______________________________________
John Stenlund RGS IT APP (webbutvecklare : -)
john.stenlund@regionhalland.se
072 084 28 77
Fiskaregatan 12.

________________________________

**Comment by viktor-sarge** [comment]
Ok. Lätt till review när du känner dig färdig. 

( Men varken basscss eller tailwind blir egentligen del av den nya RH-styleguide med tanke på att vi sagt att vi bygger komponenter istället för det som Frida designar. Utilityklasser använder vi i undantagsfall. )

**Comment by JOHNREGIONHALLAND** [comment]
Jo jag vet.
Utilityklasser ska lämnas ifred. Därför main.min.css som ni la upp från stylie2 var vilseledande. Rh css kommer att heta rh.comp.css

Jag har uppdaterat vg sajten och gått igenom det mer noggrann och använt nya komponenter, enklare för dig att se fungerande komp på sajten än på sidan jag har slängt in.

Efter att har granskat igenom vgsajten och stage-vg på utv i 2 dagar har jag några pålägg som jag gärna vill ta upp.
Kommer att pusha uppdateringar när vi är tillbaka.

______________________________________
John Stenlund RGS IT APP (webbutvecklare : -)
john.stenlund@regionhalland.se
072 084 28 77
Fiskaregatan 12.

________________________________

**Comment by fridabergentoft** [comment]
Länk till komponenter: 
https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=110%3A440&viewport=226%2C476%2C0.12392&scaling=min-zoom

**Comment by brightjennie** [comment]
Denna heter "block" efter figma-skissen. Jag har lagt komponenterna på samma sida med mellanrum för att visa med och utan bild.

**Comment by viktor-sarge** [comment]
Gott. Utseendet är korrekt, stämt av med Frida. 

En sak jag funderar på är de fasta bredderna. Jag tänker mig att vi hellre vill fylla 100% av en container + kanske en maxbredd (=bildens maxbredd) och så låter vi containern skala istället för att blocken själva har färdiga bredder. 

Vad tror du om att istället lägga maxbredd på dem, i övrigt fylla ut föräldracontainern och så lägga en demo-container som förälder?

**Comment by brightjennie** [comment]
Gött att utseendet stämde. 

Jag har lagt en demo-div och lagt max-width där. La widht 100% på komponenten. Kika och se om jag uppfattat dig korrekt.

**Comment by viktor-sarge** [comment]
Grunnat lite. Jag är snarare ute efter att komponenten har en total maxbredd och att den sedan är helt flytande för att skala nedåt. Så får containern istället ta hand om eventuella brytpunkter. Så ingen small, medium, large alls i själva rh-block utan bara en maxbredd där. 

Hojta om jag har otur när jag tänker här :)

**Comment by viktor-sarge** [comment]
Passed QA. 

Eventuellt ytterligare tweakande behöver vi inte gör här och nu utan det kan vi själva ta när vi implementerar komponenten på vår webb. Tack!
