### ISSUE TITLE
Komponent för snabblänkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#85]
# Beskrivning
Kodandet av komponenten Snabblänkar

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponenter: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Komponentbibliotek-2.0?node-id=131%3A0&viewport=-1148%2C-191%2C0.36392&scaling=min-zoom

**Comment by brightjennie** [comment]
Denna är uppe, igen utan aria-labels. Jag lägger krutet på utseendet så jag hinner med så mycket som möjligt. Det ligger en div över första för att den ska synas ;)

Sen är namnen med en 2:a bakom den andra ganska dåligt men vet inte vad de ska vara till så har ni bättre namn så säg till eller så ändrar ni det själva sen.

**Comment by viktor-sarge** [comment]
Gött! Jag släcker den här tills vidare. Hojta om du ser något visuellt @fridabergentoft
