### ISSUE TITLE
Komponent för Herobild

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#86]
# Beskrivning
Kodandet av komponenten Herobild

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till caption: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=158%3A28&viewport=4118%2C2901%2C0.208873&scaling=min-zoom

Länk till hela herobild-komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=158%3A0&viewport=-12%2C-162%2C0.29482&scaling=min-zoom

**Comment by brightjennie** [comment]
Atomen heter rh-caption-hero
Molekylen heter rh-image-hero

**Comment by viktor-sarge** [comment]
Inte hunnit implementera, men ser inga tokigheter och förutser inte några större hinder. Av-assignar mig tills vidare. Frida: skriv om du ser något och annars kan du lägga till "ready for release"
