### ISSUE TITLE
Komponent för Viktigt meddelande

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#87]
# Beskrivning
Kodandet av komponenten Viktigt meddelande
# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=126%3A0&viewport=-425%2C349%2C0.617714&scaling=min-zoom

**Comment by brightjennie** [comment]
heter rh-messages

**Comment by viktor-sarge** [comment]
Funkar bra. Har implementerat den och har inga problem med den. Jag av-assignar mig till vidare och låter Frida ha synpunkter på det visuella. Lägg till "ready for release" om det inte är något mer kvar Frida.

**Comment by fridabergentoft** [comment]
Komponenten ser rätt ut, något mörk bakgrund. Jag hade en opacitet på 70%

**Comment by JohannaOlin** [comment]
@regionhallandviktor Kan du ljusa upp komponenten?

**Comment by JohannaOlin** [comment]
Vi stänger denna så skapar jag ett nytt kort på att ljusa upp komponenten
