### ISSUE TITLE
Komponent för nyhetsflöde

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#88]
# Beskrivning
Kodandet av komponenten Nyhetsflöde

# Skisser
- [ ] Desktop -
- [ ] Tablet - 
- [ ] Mobil - 

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari

**Comment by fridabergentoft** [comment]
Länk till komponent: https://www.figma.com/proto/CMYZeVSIh8UkD2VUQvu3hAHb/Components-2.0?node-id=126%3A111&viewport=-651%2C2076%2C0.782204&scaling=min-zoom

Endast komponenterna till höger

**Comment by brightjennie** [comment]
heter rh-news-info

**Comment by viktor-sarge** [comment]
Har implementerat och den ser ut att göra vad den skall utan problem. Jag av-assignar mig och så får du hojta om du ser något Frida. Lägg till "ready for release" annars.

**Comment by fridabergentoft** [comment]
Jag känner mig nöjd med komponenten! Noterade dock att det saknat ett hoverstate?

**Comment by JohannaOlin** [comment]
@regionhallandviktor Lägger du till hoverstaten?

**Comment by viktor-sarge** [comment]
(Tror att vi bestämde att den här redan var färdig när vi pratade om den sist. Lägger till QA - skicka tillbaka om minnet sviker mig)
