### ISSUE TITLE
Prototyp - Komponent för bild och bildtext

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#89]
# Beskrivning
Komponent för att lägga in bild och bildtext i innehållet

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Komponenten ska fungera i IE, Edge, Chrome och Safari
- [ ] Komponenten ska visas i storlekarna liten, mellan och stor

**Comment by viktor-sarge** [comment]
Kikade på den som heter "Image & Video" i komponentbiblioteket. Ser inget som behöver ändras på den. 

Passerad QA för min del.
