### ISSUE TITLE
Prototyp - Komponent för modulen Länklista

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#90]
# Beskrivning
Denna komponent innehåller de länkar och dokument redaktören lägger in i en modul som visas under innehållet. 

# Acceptanskriterier
- Komponenten ska fungera på desktop, tablet och mobil
- Prototypen ska visa både länkar och olika sorters filer

**Comment by viktor-sarge** [comment]
Vill gärna stämma av med dig @fridabergentoft så jag tittar på rätt ställe.

**Comment by viktor-sarge** [comment]
Passerad QA. Vi ändrade till mörkblå med vitt kryss för expandera-ikonen.
