### ISSUE TITLE
Prototyp - Komponent för sidinformation

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#91]
# Beskrivning
Komponenten ska användas för att tala om för besökaren när en sida skapades, ändras senast samt vem som är ansvarig för innehållet

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Prototypen ska visa när sidan publicerades och när den ändrades
- [ ] Prototypen ska visa vem som är ansvarig för innehållet

**Comment by viktor-sarge** [comment]
Frida och jag diskuterade den här idag och jag har inga stora synpunkter. Enda vi funderade på var "Kontakta sidansvarig" som egentligen inte är en länk (i betydelsen "leder till en annan sida") utan kanske hellre skulle vara en knapp som heter "Visa kontaktformulär" eller liknande. Men om man vill ha en länk så är det helt ok, och den är nu understruken. 

Passerad QA för min del.
