### ISSUE TITLE
Prototyp - Komponent för tabell

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#93]
# Beskrivning
Komponenten används för att presentera innehåll som ligger i en tabell

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Prototypen ska visa hur tabellen fungerar dels när den är bred och dels när den är lång
- [ ] Prototypen ska visa hur man kan sortera om efter kolumnerna

**Comment by viktor-sarge** [comment]
Muntlig input från mig för ett tag sedan: vi bör kunna återanvända den design som vi redan hade, men lägga till funktionaliteten att sortera tabellen efter olika kolumner. Koden går nog att gräva fram igen om man vill - var en ganska enkel princip som man kan snygga till. Eller bara återimplementera.

**Comment by fridabergentoft** [comment]
@regionhallandviktor 
Nu har jag ändrat lite i tabellerna. Du hittar dem i komponentbiblioteket under Lists & Accordions.
De kolumner som går att sortera har en liten triangel till höger om rubriken. Hover-state är att pilen blir vit. Active-state innebär att pilen är vit och pekar neråt samt att rubriken är understruken.

**Comment by viktor-sarge** [comment]
Tack för uppdateringen @fridabergentoft . Några saker som slog mig: 
* Active state kan inte vara vilket håll pilen pekar. Åtminstone inte om sorteringen skall vara klassiska "stigande" / "fallande" som pil upp/ned brukar symbolisera. Däremot kan det fungera att mätta den till fullvit (kontrasten är riktigt låg på den inaktiva, men inaktiva komponenter har inte heller samma krav på sig). 
* Understrykning är också lite knepigt att använda som active state, det krockar med att understruken text signalerar länkar.
* Endast en kolumn kan ju vara sorterad åt gången så sorteringspilar på varje kolumn känns lite missvisande. 

Att köra understrykning på alla som är sorterbara och pil bara på den som är aktiv skulle vara det mest konsekventa. Men det blir inte överdrivet vackert. Vi kanske kan resonera en vända om hur vi gör?

**Comment by viktor-sarge** [comment]
Kikade i komponenbibliotek 2.0 under organism/table och det är passed QA för min del.

**Comment by JohannaOlin** [comment]
Ok för min del också. Jag vet att Joel och Mattias hade ett par synpunkter kring detta, men jag tycker att vi får ta det i steg två och då kanske göra en riktig användarundersökning.
