### ISSUE TITLE
Prototyp - Komponent för filmer

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#94]
# Beskrivning
Komponenten ska visa hur inbäddade filmer presenteras

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil

**Comment by viktor-sarge** [comment]
Tror inte jag har någon koll på var jag ser den här. Kan du länka/skicka PDF @fridabergentoft ?

**Comment by JohannaOlin** [comment]
@regionhallandviktor Jag ser komponenten om jag går in i Komponentbiblioteket och väljer Image & Video

**Comment by viktor-sarge** [comment]
Ser inget som behöver ändras. 

Passerad QA för min del.
