### ISSUE TITLE
Prototyp - Komponent för dokument

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#95]
# Beskrivning
Komponenten används för att visa upp en länk till ett dokument

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Prototypen ska visa ikon för dokumentet
- [ ] Prototypen ska visa Titel för dokumentet
- [ ] Prototypen ska visa dokumentets tyngd

**Comment by viktor-sarge** [comment]
Vi tog en avstämning idag och jag har inga invändningar just nu. Passerad QA för min del.
