### ISSUE TITLE
Prototyp - Komponent för Länkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#96]
# Beskrivning
Komponenten används för att visa hur länkar, både i löptext och i moduler presenteras

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Prototypen ska visa de olika states en länk finns i

**Comment by viktor-sarge** [comment]
Vi kikade på den här. Hade inga omedelbara synpunkter. Kan vara passerad Qa för min del även om länkfärg är en ständigt pågående diskussion :) Får kanske återkomma till det när vi ser helheten.
