### ISSUE TITLE
Prototyp - Komponent för Artikelsida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/general#98]
# Beskrivning
Komponenten används för att visa hur en artikelsida (nyhet) ser ut

# Acceptanskriterier
- [ ] Komponenten ska fungera på desktop, tablet och mobil
- [ ] Prototypen ska visa en nyhets label/labels
- [ ] Prototypen ska visa komponenten Sidinformation högt upp

**Comment by viktor-sarge** [comment]
Vill gärna stämma av med dig @fridabergentoft så jag tittar på rätt ställe.

**Comment by viktor-sarge** [comment]
Datumformatet är bra om vi kör samma som i övrigt (som vi bestämde nyss muntligt.) 

Ramlinjen är väldigt diskret så om man vill att själva kortet skall vara tydligt så behöver man ha t.ex. en grå bakgrund bakom gruppen med kort. Men failar inte QA på det.
